/*
 * generated by Xtext 2.29.0
 * (c) Evoal Project
 */
package de.evoal.languages.model.base.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBaseLanguageScopeProvider extends DelegatingScopeProvider {
}
