module de.evoal.optimisation.constraint {
	/**
	 * Sets the variance of some data.
	 *
	 * <b>Parameters:</b>
	 * <ol>
	 *   <li>Reference to the data ...</li>
	 * </ol> 
	 */
	def void variance(data reference, real variance);
	
	def void connection(data ref1, data ref2, real connection);

	def void range (real lower, real upper);

	def void 'ranged-connection'(data ref1, expression range1, data ref2, expression range2, real connection);

	def void constraint(expression exp, string category);

	def void range(real lower, real upper);
}
