<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>de.evoal</groupId>
		<artifactId>releng.core</artifactId>
		<version>${revision}</version>
	</parent>

	<artifactId>core.junit</artifactId>
	<name>EvoAl - Core - JUnit Helpers</name>

	<dependencies>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>${slf4j.api.version}</version>
		</dependency>

		<dependency>
			<groupId>org.eclipse.xtext</groupId>
			<artifactId>org.eclipse.xtext</artifactId>
			<version>${xtext.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.antlr</groupId>
			<artifactId>antlr-runtime</artifactId>
			<version>3.2</version>
			<scope>compile</scope>
		</dependency>

		<!-- DSL dependencies -->
		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.ddl</artifactId>
			<version>${evoal.languages.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.dl</artifactId>
			<version>${evoal.languages.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.base</artifactId>
			<version>${evoal.languages.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.models</artifactId>
			<version>${evoal.languages.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.instance</artifactId>
			<version>${evoal.languages.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.ol</artifactId>
			<version>${evoal.languages.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.ddl.dsl</artifactId>
			<version>${evoal.languages.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.dl.dsl</artifactId>
			<version>${evoal.languages.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.base.dsl</artifactId>
			<version>${evoal.languages.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.mll.dsl</artifactId>
			<version>${evoal.languages.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.ol.dsl</artifactId>
			<version>${evoal.languages.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.generator.dsl</artifactId>
			<version>${evoal.languages.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.utils</artifactId>
			<version>${evoal.languages.version}</version>
			<scope>compile</scope>
		</dependency>

		<!-- Test dependencies -->
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
		</dependency>

		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-junit-jupiter</artifactId>
			<version>${mockito.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.instance.dsl</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
</project>
