/**
 * generated by Xtext 2.25.0
 */
package de.evoal.languages.model.pipeline;

import de.evoal.languages.model.base.Literal;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Literal Range</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.evoal.languages.model.pipeline.LiteralRange#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see de.evoal.languages.model.pipeline.PipelinePackage#getLiteralRange()
 * @model
 * @generated
 */
public interface LiteralRange extends Range {
	/**
	 * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
	 * The list contents are of type {@link de.evoal.languages.model.base.Literal}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Elements</em>' containment reference list.
	 * @see de.evoal.languages.model.pipeline.PipelinePackage#getLiteralRange_Elements()
	 * @model containment="true" required="true" ordered="false"
	 *        annotation="http://www.eclipse.org/OCL/Collection nullFree='false'"
	 * @generated
	 */
	EList<Literal> getElements();

} // LiteralRange
