/*
 * generated by Xtext 2.33.0
 * (c) EvoAl Project
 */
package de.evoal.languages.model.ddl.dsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import de.evoal.languages.model.base.dsl.services.BaseLanguageGrammarAccess;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class DataDescriptionLanguageGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class DataDescriptionModelRuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.evoal.languages.model.ddl.dsl.DataDescriptionLanguage.DataDescriptionModelRule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cImportsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cImportsImportRuleParserRuleCall_0_0 = (RuleCall)cImportsAssignment_0.eContents().get(0);
		private final Keyword cModuleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameQualifiedNameParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTypesKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cColonKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cTypesAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cTypesDataTypeDefinitionRuleParserRuleCall_4_2_0 = (RuleCall)cTypesAssignment_4_2.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDataKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cColonKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cDescriptionsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cDescriptionsDataDescriptionRuleParserRuleCall_5_2_0 = (RuleCall)cDescriptionsAssignment_5_2.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cConstraintsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cColonKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cConstraintsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cConstraintsStatementRuleParserRuleCall_6_2_0 = (RuleCall)cConstraintsAssignment_6_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//DataDescriptionModelRule returns DataDescriptionModule:
		//    (imports += BaseLanguage::ImportRule)*
		//    'module' name = QualifiedName '{'
		//        ('types' ':' (types += DataTypeDefinitionRule)* )?
		//        ('data' ':' (descriptions += DataDescriptionRule)* )?
		//        ('constraints' ':' (constraints += StatementRule)*)?
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//(imports += BaseLanguage::ImportRule)*
		//'module' name = QualifiedName '{'
		//    ('types' ':' (types += DataTypeDefinitionRule)* )?
		//    ('data' ':' (descriptions += DataDescriptionRule)* )?
		//    ('constraints' ':' (constraints += StatementRule)*)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//(imports += BaseLanguage::ImportRule)*
		public Assignment getImportsAssignment_0() { return cImportsAssignment_0; }
		
		//BaseLanguage::ImportRule
		public RuleCall getImportsImportRuleParserRuleCall_0_0() { return cImportsImportRuleParserRuleCall_0_0; }
		
		//'module'
		public Keyword getModuleKeyword_1() { return cModuleKeyword_1; }
		
		//name = QualifiedName
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//QualifiedName
		public RuleCall getNameQualifiedNameParserRuleCall_2_0() { return cNameQualifiedNameParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('types' ':' (types += DataTypeDefinitionRule)* )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'types'
		public Keyword getTypesKeyword_4_0() { return cTypesKeyword_4_0; }
		
		//':'
		public Keyword getColonKeyword_4_1() { return cColonKeyword_4_1; }
		
		//(types += DataTypeDefinitionRule)*
		public Assignment getTypesAssignment_4_2() { return cTypesAssignment_4_2; }
		
		//DataTypeDefinitionRule
		public RuleCall getTypesDataTypeDefinitionRuleParserRuleCall_4_2_0() { return cTypesDataTypeDefinitionRuleParserRuleCall_4_2_0; }
		
		//('data' ':' (descriptions += DataDescriptionRule)* )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'data'
		public Keyword getDataKeyword_5_0() { return cDataKeyword_5_0; }
		
		//':'
		public Keyword getColonKeyword_5_1() { return cColonKeyword_5_1; }
		
		//(descriptions += DataDescriptionRule)*
		public Assignment getDescriptionsAssignment_5_2() { return cDescriptionsAssignment_5_2; }
		
		//DataDescriptionRule
		public RuleCall getDescriptionsDataDescriptionRuleParserRuleCall_5_2_0() { return cDescriptionsDataDescriptionRuleParserRuleCall_5_2_0; }
		
		//('constraints' ':' (constraints += StatementRule)*)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'constraints'
		public Keyword getConstraintsKeyword_6_0() { return cConstraintsKeyword_6_0; }
		
		//':'
		public Keyword getColonKeyword_6_1() { return cColonKeyword_6_1; }
		
		//(constraints += StatementRule)*
		public Assignment getConstraintsAssignment_6_2() { return cConstraintsAssignment_6_2; }
		
		//StatementRule
		public RuleCall getConstraintsStatementRuleParserRuleCall_6_2_0() { return cConstraintsStatementRuleParserRuleCall_6_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class DataTypeDefinitionRuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.evoal.languages.model.ddl.dsl.DataDescriptionLanguage.DataTypeDefinitionRule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cConstraints2Assignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cConstraints2ConstraintRuleParserRuleCall_0_0 = (RuleCall)cConstraints2Assignment_0.eContents().get(0);
		private final Assignment cScaleAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cScaleScaleTypeEnumRuleCall_1_0 = (RuleCall)cScaleAssignment_1.eContents().get(0);
		private final Keyword cTypeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameStringOrIdParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cColonKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cDescriptionAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_4_2_0 = (RuleCall)cDescriptionAssignment_4_2.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cWithKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cConstraintsKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Keyword cColonKeyword_5_2 = (Keyword)cGroup_5.eContents().get(2);
		private final Assignment cConstraintsAssignment_5_3 = (Assignment)cGroup_5.eContents().get(3);
		private final RuleCall cConstraintsStatementRuleParserRuleCall_5_3_0 = (RuleCall)cConstraintsAssignment_5_3.eContents().get(0);
		private final Keyword cSemicolonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//DataTypeDefinitionRule returns DataTypeDefinition:
		//    (constraints2 += BaseLanguage::ConstraintRule)*
		//    scale = ScaleType 'type' name = StringOrId ('description' ':' description = STRING)? ('with' 'constraints' ':' (constraints += StatementRule)*)?
		//';'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//    (constraints2 += BaseLanguage::ConstraintRule)*
		//    scale = ScaleType 'type' name = StringOrId ('description' ':' description = STRING)? ('with' 'constraints' ':' (constraints += StatementRule)*)?
		//';'
		public Group getGroup() { return cGroup; }
		
		//(constraints2 += BaseLanguage::ConstraintRule)*
		public Assignment getConstraints2Assignment_0() { return cConstraints2Assignment_0; }
		
		//BaseLanguage::ConstraintRule
		public RuleCall getConstraints2ConstraintRuleParserRuleCall_0_0() { return cConstraints2ConstraintRuleParserRuleCall_0_0; }
		
		//scale = ScaleType
		public Assignment getScaleAssignment_1() { return cScaleAssignment_1; }
		
		//ScaleType
		public RuleCall getScaleScaleTypeEnumRuleCall_1_0() { return cScaleScaleTypeEnumRuleCall_1_0; }
		
		//'type'
		public Keyword getTypeKeyword_2() { return cTypeKeyword_2; }
		
		//name = StringOrId
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//StringOrId
		public RuleCall getNameStringOrIdParserRuleCall_3_0() { return cNameStringOrIdParserRuleCall_3_0; }
		
		//('description' ':' description = STRING)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'description'
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }
		
		//':'
		public Keyword getColonKeyword_4_1() { return cColonKeyword_4_1; }
		
		//description = STRING
		public Assignment getDescriptionAssignment_4_2() { return cDescriptionAssignment_4_2; }
		
		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_4_2_0() { return cDescriptionSTRINGTerminalRuleCall_4_2_0; }
		
		//('with' 'constraints' ':' (constraints += StatementRule)*)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'with'
		public Keyword getWithKeyword_5_0() { return cWithKeyword_5_0; }
		
		//'constraints'
		public Keyword getConstraintsKeyword_5_1() { return cConstraintsKeyword_5_1; }
		
		//':'
		public Keyword getColonKeyword_5_2() { return cColonKeyword_5_2; }
		
		//(constraints += StatementRule)*
		public Assignment getConstraintsAssignment_5_3() { return cConstraintsAssignment_5_3; }
		
		//StatementRule
		public RuleCall getConstraintsStatementRuleParserRuleCall_5_3_0() { return cConstraintsStatementRuleParserRuleCall_5_3_0; }
		
		//';'
		public Keyword getSemicolonKeyword_6() { return cSemicolonKeyword_6; }
	}
	public class DataDescriptionRuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.evoal.languages.model.ddl.dsl.DataDescriptionLanguage.DataDescriptionRule");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cTypedBaseDataDescriptionRuleParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cUntypedBaseDataDescriptionRuleParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cStructuredDataDescriptionRuleParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//DataDescriptionRule returns DataDescription:
		//    TypedBaseDataDescriptionRule | UntypedBaseDataDescriptionRule | StructuredDataDescriptionRule
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//TypedBaseDataDescriptionRule | UntypedBaseDataDescriptionRule | StructuredDataDescriptionRule
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//TypedBaseDataDescriptionRule
		public RuleCall getTypedBaseDataDescriptionRuleParserRuleCall_0() { return cTypedBaseDataDescriptionRuleParserRuleCall_0; }
		
		//UntypedBaseDataDescriptionRule
		public RuleCall getUntypedBaseDataDescriptionRuleParserRuleCall_1() { return cUntypedBaseDataDescriptionRuleParserRuleCall_1; }
		
		//StructuredDataDescriptionRule
		public RuleCall getStructuredDataDescriptionRuleParserRuleCall_2() { return cStructuredDataDescriptionRuleParserRuleCall_2; }
	}
	public class TypedBaseDataDescriptionRuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.evoal.languages.model.ddl.dsl.DataDescriptionLanguage.TypedBaseDataDescriptionRule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cConstraints2Assignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cConstraints2ConstraintRuleParserRuleCall_0_0 = (RuleCall)cConstraints2Assignment_0.eContents().get(0);
		private final Assignment cRepresentationAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cRepresentationRepresentationTypeEnumRuleCall_1_0 = (RuleCall)cRepresentationAssignment_1.eContents().get(0);
		private final Keyword cDataKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameStringOrIdParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cOfKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cTypeKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cTypeAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cTypeDataTypeDefinitionCrossReference_6_0 = (CrossReference)cTypeAssignment_6.eContents().get(0);
		private final RuleCall cTypeDataTypeDefinitionQualifiedNameParserRuleCall_6_0_1 = (RuleCall)cTypeDataTypeDefinitionCrossReference_6_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cWithKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cConstraintsKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Keyword cColonKeyword_7_2 = (Keyword)cGroup_7.eContents().get(2);
		private final Assignment cConstraintsAssignment_7_3 = (Assignment)cGroup_7.eContents().get(3);
		private final RuleCall cConstraintsStatementRuleParserRuleCall_7_3_0 = (RuleCall)cConstraintsAssignment_7_3.eContents().get(0);
		private final Keyword cSemicolonKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//TypedBaseDataDescriptionRule returns TypedBaseDataDescription:
		//    (constraints2 += BaseLanguage::ConstraintRule)*
		//    representation=RepresentationType 'data' name = StringOrId 'of' 'type' type = [DataTypeDefinition|QualifiedName] ('with' 'constraints' ':' (constraints += StatementRule)*)?
		//    ';'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//(constraints2 += BaseLanguage::ConstraintRule)*
		//representation=RepresentationType 'data' name = StringOrId 'of' 'type' type = [DataTypeDefinition|QualifiedName] ('with' 'constraints' ':' (constraints += StatementRule)*)?
		//';'
		public Group getGroup() { return cGroup; }
		
		//(constraints2 += BaseLanguage::ConstraintRule)*
		public Assignment getConstraints2Assignment_0() { return cConstraints2Assignment_0; }
		
		//BaseLanguage::ConstraintRule
		public RuleCall getConstraints2ConstraintRuleParserRuleCall_0_0() { return cConstraints2ConstraintRuleParserRuleCall_0_0; }
		
		//representation=RepresentationType
		public Assignment getRepresentationAssignment_1() { return cRepresentationAssignment_1; }
		
		//RepresentationType
		public RuleCall getRepresentationRepresentationTypeEnumRuleCall_1_0() { return cRepresentationRepresentationTypeEnumRuleCall_1_0; }
		
		//'data'
		public Keyword getDataKeyword_2() { return cDataKeyword_2; }
		
		//name = StringOrId
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//StringOrId
		public RuleCall getNameStringOrIdParserRuleCall_3_0() { return cNameStringOrIdParserRuleCall_3_0; }
		
		//'of'
		public Keyword getOfKeyword_4() { return cOfKeyword_4; }
		
		//'type'
		public Keyword getTypeKeyword_5() { return cTypeKeyword_5; }
		
		//type = [DataTypeDefinition|QualifiedName]
		public Assignment getTypeAssignment_6() { return cTypeAssignment_6; }
		
		//[DataTypeDefinition|QualifiedName]
		public CrossReference getTypeDataTypeDefinitionCrossReference_6_0() { return cTypeDataTypeDefinitionCrossReference_6_0; }
		
		//QualifiedName
		public RuleCall getTypeDataTypeDefinitionQualifiedNameParserRuleCall_6_0_1() { return cTypeDataTypeDefinitionQualifiedNameParserRuleCall_6_0_1; }
		
		//('with' 'constraints' ':' (constraints += StatementRule)*)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'with'
		public Keyword getWithKeyword_7_0() { return cWithKeyword_7_0; }
		
		//'constraints'
		public Keyword getConstraintsKeyword_7_1() { return cConstraintsKeyword_7_1; }
		
		//':'
		public Keyword getColonKeyword_7_2() { return cColonKeyword_7_2; }
		
		//(constraints += StatementRule)*
		public Assignment getConstraintsAssignment_7_3() { return cConstraintsAssignment_7_3; }
		
		//StatementRule
		public RuleCall getConstraintsStatementRuleParserRuleCall_7_3_0() { return cConstraintsStatementRuleParserRuleCall_7_3_0; }
		
		//';'
		public Keyword getSemicolonKeyword_8() { return cSemicolonKeyword_8; }
	}
	public class UntypedBaseDataDescriptionRuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.evoal.languages.model.ddl.dsl.DataDescriptionLanguage.UntypedBaseDataDescriptionRule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cConstraints2Assignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cConstraints2ConstraintRuleParserRuleCall_0_0 = (RuleCall)cConstraints2Assignment_0.eContents().get(0);
		private final Assignment cScaleAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cScaleScaleTypeEnumRuleCall_1_0 = (RuleCall)cScaleAssignment_1.eContents().get(0);
		private final Assignment cRepresentationAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cRepresentationRepresentationTypeEnumRuleCall_2_0 = (RuleCall)cRepresentationAssignment_2.eContents().get(0);
		private final Keyword cDataKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNameStringOrIdParserRuleCall_4_0 = (RuleCall)cNameAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cWithKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cConstraintsKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Keyword cColonKeyword_5_2 = (Keyword)cGroup_5.eContents().get(2);
		private final Assignment cConstraintsAssignment_5_3 = (Assignment)cGroup_5.eContents().get(3);
		private final RuleCall cConstraintsStatementRuleParserRuleCall_5_3_0 = (RuleCall)cConstraintsAssignment_5_3.eContents().get(0);
		private final Keyword cSemicolonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//UntypedBaseDataDescriptionRule returns UntypedBaseDataDescription:
		//    (constraints2 += BaseLanguage::ConstraintRule)*
		// (scale = ScaleType)? representation=RepresentationType 'data' name = StringOrId     ('with' 'constraints' ':' (constraints += StatementRule)*)?
		// ';'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//   (constraints2 += BaseLanguage::ConstraintRule)*
		//(scale = ScaleType)? representation=RepresentationType 'data' name = StringOrId     ('with' 'constraints' ':' (constraints += StatementRule)*)?
		//';'
		public Group getGroup() { return cGroup; }
		
		//(constraints2 += BaseLanguage::ConstraintRule)*
		public Assignment getConstraints2Assignment_0() { return cConstraints2Assignment_0; }
		
		//BaseLanguage::ConstraintRule
		public RuleCall getConstraints2ConstraintRuleParserRuleCall_0_0() { return cConstraints2ConstraintRuleParserRuleCall_0_0; }
		
		//(scale = ScaleType)?
		public Assignment getScaleAssignment_1() { return cScaleAssignment_1; }
		
		//ScaleType
		public RuleCall getScaleScaleTypeEnumRuleCall_1_0() { return cScaleScaleTypeEnumRuleCall_1_0; }
		
		//representation=RepresentationType
		public Assignment getRepresentationAssignment_2() { return cRepresentationAssignment_2; }
		
		//RepresentationType
		public RuleCall getRepresentationRepresentationTypeEnumRuleCall_2_0() { return cRepresentationRepresentationTypeEnumRuleCall_2_0; }
		
		//'data'
		public Keyword getDataKeyword_3() { return cDataKeyword_3; }
		
		//name = StringOrId
		public Assignment getNameAssignment_4() { return cNameAssignment_4; }
		
		//StringOrId
		public RuleCall getNameStringOrIdParserRuleCall_4_0() { return cNameStringOrIdParserRuleCall_4_0; }
		
		//('with' 'constraints' ':' (constraints += StatementRule)*)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'with'
		public Keyword getWithKeyword_5_0() { return cWithKeyword_5_0; }
		
		//'constraints'
		public Keyword getConstraintsKeyword_5_1() { return cConstraintsKeyword_5_1; }
		
		//':'
		public Keyword getColonKeyword_5_2() { return cColonKeyword_5_2; }
		
		//(constraints += StatementRule)*
		public Assignment getConstraintsAssignment_5_3() { return cConstraintsAssignment_5_3; }
		
		//StatementRule
		public RuleCall getConstraintsStatementRuleParserRuleCall_5_3_0() { return cConstraintsStatementRuleParserRuleCall_5_3_0; }
		
		//';'
		public Keyword getSemicolonKeyword_6() { return cSemicolonKeyword_6; }
	}
	public class StructuredDataDescriptionRuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.evoal.languages.model.ddl.dsl.DataDescriptionLanguage.StructuredDataDescriptionRule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDataKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameStringOrIdParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cOfKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cInstanceKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTypeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cTypeTypeDefinitionCrossReference_4_0 = (CrossReference)cTypeAssignment_4.eContents().get(0);
		private final RuleCall cTypeTypeDefinitionQualifiedNameParserRuleCall_4_0_1 = (RuleCall)cTypeTypeDefinitionCrossReference_4_0.eContents().get(1);
		private final Keyword cSemicolonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//StructuredDataDescriptionRule returns StructuredDataDescription:
		//    'data' name = StringOrId 'of' 'instance'  type = [base::TypeDefinition|QualifiedName] ';'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'data' name = StringOrId 'of' 'instance'  type = [base::TypeDefinition|QualifiedName] ';'
		public Group getGroup() { return cGroup; }
		
		//'data'
		public Keyword getDataKeyword_0() { return cDataKeyword_0; }
		
		//name = StringOrId
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//StringOrId
		public RuleCall getNameStringOrIdParserRuleCall_1_0() { return cNameStringOrIdParserRuleCall_1_0; }
		
		//'of'
		public Keyword getOfKeyword_2() { return cOfKeyword_2; }
		
		//'instance'
		public Keyword getInstanceKeyword_3() { return cInstanceKeyword_3; }
		
		//type = [base::TypeDefinition|QualifiedName]
		public Assignment getTypeAssignment_4() { return cTypeAssignment_4; }
		
		//[base::TypeDefinition|QualifiedName]
		public CrossReference getTypeTypeDefinitionCrossReference_4_0() { return cTypeTypeDefinitionCrossReference_4_0; }
		
		//QualifiedName
		public RuleCall getTypeTypeDefinitionQualifiedNameParserRuleCall_4_0_1() { return cTypeTypeDefinitionQualifiedNameParserRuleCall_4_0_1; }
		
		//';'
		public Keyword getSemicolonKeyword_5() { return cSemicolonKeyword_5; }
	}
	public class StatementRuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.evoal.languages.model.ddl.dsl.DataDescriptionLanguage.StatementRule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cExpressionRuleParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cSemicolonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//StatementRule returns base::Expression:
		//    BaseLanguage::ExpressionRule ';'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//BaseLanguage::ExpressionRule ';'
		public Group getGroup() { return cGroup; }
		
		//BaseLanguage::ExpressionRule
		public RuleCall getExpressionRuleParserRuleCall_0() { return cExpressionRuleParserRuleCall_0; }
		
		//';'
		public Keyword getSemicolonKeyword_1() { return cSemicolonKeyword_1; }
	}
	public class ReferenceRuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.evoal.languages.model.ddl.dsl.DataDescriptionLanguage.ReferenceRule");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cConstantReferenceRuleParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cDataReferenceRuleParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cSelfReferenceRuleParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//@Override
		//ReferenceRule returns base::ValueReference:
		//    ConstantReferenceRule | DataReferenceRule | SelfReferenceRule
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//ConstantReferenceRule | DataReferenceRule | SelfReferenceRule
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ConstantReferenceRule
		public RuleCall getConstantReferenceRuleParserRuleCall_0() { return cConstantReferenceRuleParserRuleCall_0; }
		
		//DataReferenceRule
		public RuleCall getDataReferenceRuleParserRuleCall_1() { return cDataReferenceRuleParserRuleCall_1; }
		
		//SelfReferenceRule
		public RuleCall getSelfReferenceRuleParserRuleCall_2() { return cSelfReferenceRuleParserRuleCall_2; }
	}
	public class DataReferenceRuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.evoal.languages.model.ddl.dsl.DataDescriptionLanguage.DataReferenceRule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDataKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cDefinitionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cDefinitionDataDescriptionCrossReference_1_0 = (CrossReference)cDefinitionAssignment_1.eContents().get(0);
		private final RuleCall cDefinitionDataDescriptionQualifiedNameParserRuleCall_1_0_1 = (RuleCall)cDefinitionDataDescriptionCrossReference_1_0.eContents().get(1);
		
		//DataReferenceRule returns DataReference:
		//    'data' definition = [DataDescription|QualifiedName]
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'data' definition = [DataDescription|QualifiedName]
		public Group getGroup() { return cGroup; }
		
		//'data'
		public Keyword getDataKeyword_0() { return cDataKeyword_0; }
		
		//definition = [DataDescription|QualifiedName]
		public Assignment getDefinitionAssignment_1() { return cDefinitionAssignment_1; }
		
		//[DataDescription|QualifiedName]
		public CrossReference getDefinitionDataDescriptionCrossReference_1_0() { return cDefinitionDataDescriptionCrossReference_1_0; }
		
		//QualifiedName
		public RuleCall getDefinitionDataDescriptionQualifiedNameParserRuleCall_1_0_1() { return cDefinitionDataDescriptionQualifiedNameParserRuleCall_1_0_1; }
	}
	public class SelfReferenceRuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.evoal.languages.model.ddl.dsl.DataDescriptionLanguage.SelfReferenceRule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSelfReferenceAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cValueKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//SelfReferenceRule returns SelfReference:
		//    {SelfReference}
		//    'value'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{SelfReference}
		//'value'
		public Group getGroup() { return cGroup; }
		
		//{SelfReference}
		public Action getSelfReferenceAction_0() { return cSelfReferenceAction_0; }
		
		//'value'
		public Keyword getValueKeyword_1() { return cValueKeyword_1; }
	}
	
	public class ScaleTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "de.evoal.languages.model.ddl.dsl.DataDescriptionLanguage.ScaleType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cNominalEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cNominalNominalKeyword_0_0 = (Keyword)cNominalEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cOrdinalEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cOrdinalOrdinalKeyword_1_0 = (Keyword)cOrdinalEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cCardinalEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cCardinalCardinalKeyword_2_0 = (Keyword)cCardinalEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cQuotientEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cQuotientQuotientKeyword_3_0 = (Keyword)cQuotientEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum ScaleType returns ScaleType:
		//    Nominal = 'nominal' |
		//    Ordinal = 'ordinal' |
		//    Cardinal = 'cardinal' |
		//    Quotient = 'quotient'
		//;
		public EnumRule getRule() { return rule; }
		
		//Nominal = 'nominal' |
		//Ordinal = 'ordinal' |
		//Cardinal = 'cardinal' |
		//Quotient = 'quotient'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Nominal = 'nominal'
		public EnumLiteralDeclaration getNominalEnumLiteralDeclaration_0() { return cNominalEnumLiteralDeclaration_0; }
		
		//'nominal'
		public Keyword getNominalNominalKeyword_0_0() { return cNominalNominalKeyword_0_0; }
		
		//Ordinal = 'ordinal'
		public EnumLiteralDeclaration getOrdinalEnumLiteralDeclaration_1() { return cOrdinalEnumLiteralDeclaration_1; }
		
		//'ordinal'
		public Keyword getOrdinalOrdinalKeyword_1_0() { return cOrdinalOrdinalKeyword_1_0; }
		
		//Cardinal = 'cardinal'
		public EnumLiteralDeclaration getCardinalEnumLiteralDeclaration_2() { return cCardinalEnumLiteralDeclaration_2; }
		
		//'cardinal'
		public Keyword getCardinalCardinalKeyword_2_0() { return cCardinalCardinalKeyword_2_0; }
		
		//Quotient = 'quotient'
		public EnumLiteralDeclaration getQuotientEnumLiteralDeclaration_3() { return cQuotientEnumLiteralDeclaration_3; }
		
		//'quotient'
		public Keyword getQuotientQuotientKeyword_3_0() { return cQuotientQuotientKeyword_3_0; }
	}
	public class RepresentationTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "de.evoal.languages.model.ddl.dsl.DataDescriptionLanguage.RepresentationType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cRealEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cRealRealKeyword_0_0 = (Keyword)cRealEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cIntegerEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cIntegerIntegerKeyword_1_0 = (Keyword)cIntegerEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cBooleanEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cBooleanBooleanKeyword_2_0 = (Keyword)cBooleanEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cStringEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cStringStringKeyword_3_0 = (Keyword)cStringEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum RepresentationType returns RepresentationType:
		//    Real = 'real' |
		//    Integer = 'integer' |
		//    Boolean = 'boolean' |
		//    String = 'string';
		public EnumRule getRule() { return rule; }
		
		//Real = 'real' |
		//Integer = 'integer' |
		//Boolean = 'boolean' |
		//String = 'string'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Real = 'real'
		public EnumLiteralDeclaration getRealEnumLiteralDeclaration_0() { return cRealEnumLiteralDeclaration_0; }
		
		//'real'
		public Keyword getRealRealKeyword_0_0() { return cRealRealKeyword_0_0; }
		
		//Integer = 'integer'
		public EnumLiteralDeclaration getIntegerEnumLiteralDeclaration_1() { return cIntegerEnumLiteralDeclaration_1; }
		
		//'integer'
		public Keyword getIntegerIntegerKeyword_1_0() { return cIntegerIntegerKeyword_1_0; }
		
		//Boolean = 'boolean'
		public EnumLiteralDeclaration getBooleanEnumLiteralDeclaration_2() { return cBooleanEnumLiteralDeclaration_2; }
		
		//'boolean'
		public Keyword getBooleanBooleanKeyword_2_0() { return cBooleanBooleanKeyword_2_0; }
		
		//String = 'string'
		public EnumLiteralDeclaration getStringEnumLiteralDeclaration_3() { return cStringEnumLiteralDeclaration_3; }
		
		//'string'
		public Keyword getStringStringKeyword_3_0() { return cStringStringKeyword_3_0; }
	}
	
	private final DataDescriptionModelRuleElements pDataDescriptionModelRule;
	private final ScaleTypeElements eScaleType;
	private final RepresentationTypeElements eRepresentationType;
	private final DataTypeDefinitionRuleElements pDataTypeDefinitionRule;
	private final DataDescriptionRuleElements pDataDescriptionRule;
	private final TypedBaseDataDescriptionRuleElements pTypedBaseDataDescriptionRule;
	private final UntypedBaseDataDescriptionRuleElements pUntypedBaseDataDescriptionRule;
	private final StructuredDataDescriptionRuleElements pStructuredDataDescriptionRule;
	private final StatementRuleElements pStatementRule;
	private final ReferenceRuleElements pReferenceRule;
	private final DataReferenceRuleElements pDataReferenceRule;
	private final SelfReferenceRuleElements pSelfReferenceRule;
	
	private final Grammar grammar;
	
	private final BaseLanguageGrammarAccess gaBaseLanguage;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public DataDescriptionLanguageGrammarAccess(GrammarProvider grammarProvider,
			BaseLanguageGrammarAccess gaBaseLanguage,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaBaseLanguage = gaBaseLanguage;
		this.gaTerminals = gaTerminals;
		this.pDataDescriptionModelRule = new DataDescriptionModelRuleElements();
		this.eScaleType = new ScaleTypeElements();
		this.eRepresentationType = new RepresentationTypeElements();
		this.pDataTypeDefinitionRule = new DataTypeDefinitionRuleElements();
		this.pDataDescriptionRule = new DataDescriptionRuleElements();
		this.pTypedBaseDataDescriptionRule = new TypedBaseDataDescriptionRuleElements();
		this.pUntypedBaseDataDescriptionRule = new UntypedBaseDataDescriptionRuleElements();
		this.pStructuredDataDescriptionRule = new StructuredDataDescriptionRuleElements();
		this.pStatementRule = new StatementRuleElements();
		this.pReferenceRule = new ReferenceRuleElements();
		this.pDataReferenceRule = new DataReferenceRuleElements();
		this.pSelfReferenceRule = new SelfReferenceRuleElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("de.evoal.languages.model.ddl.dsl.DataDescriptionLanguage".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public BaseLanguageGrammarAccess getBaseLanguageGrammarAccess() {
		return gaBaseLanguage;
	}
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//DataDescriptionModelRule returns DataDescriptionModule:
	//    (imports += BaseLanguage::ImportRule)*
	//    'module' name = QualifiedName '{'
	//        ('types' ':' (types += DataTypeDefinitionRule)* )?
	//        ('data' ':' (descriptions += DataDescriptionRule)* )?
	//        ('constraints' ':' (constraints += StatementRule)*)?
	//    '}'
	//;
	public DataDescriptionModelRuleElements getDataDescriptionModelRuleAccess() {
		return pDataDescriptionModelRule;
	}
	
	public ParserRule getDataDescriptionModelRuleRule() {
		return getDataDescriptionModelRuleAccess().getRule();
	}
	
	//enum ScaleType returns ScaleType:
	//    Nominal = 'nominal' |
	//    Ordinal = 'ordinal' |
	//    Cardinal = 'cardinal' |
	//    Quotient = 'quotient'
	//;
	public ScaleTypeElements getScaleTypeAccess() {
		return eScaleType;
	}
	
	public EnumRule getScaleTypeRule() {
		return getScaleTypeAccess().getRule();
	}
	
	//enum RepresentationType returns RepresentationType:
	//    Real = 'real' |
	//    Integer = 'integer' |
	//    Boolean = 'boolean' |
	//    String = 'string';
	public RepresentationTypeElements getRepresentationTypeAccess() {
		return eRepresentationType;
	}
	
	public EnumRule getRepresentationTypeRule() {
		return getRepresentationTypeAccess().getRule();
	}
	
	//DataTypeDefinitionRule returns DataTypeDefinition:
	//    (constraints2 += BaseLanguage::ConstraintRule)*
	//    scale = ScaleType 'type' name = StringOrId ('description' ':' description = STRING)? ('with' 'constraints' ':' (constraints += StatementRule)*)?
	//';'
	//;
	public DataTypeDefinitionRuleElements getDataTypeDefinitionRuleAccess() {
		return pDataTypeDefinitionRule;
	}
	
	public ParserRule getDataTypeDefinitionRuleRule() {
		return getDataTypeDefinitionRuleAccess().getRule();
	}
	
	//DataDescriptionRule returns DataDescription:
	//    TypedBaseDataDescriptionRule | UntypedBaseDataDescriptionRule | StructuredDataDescriptionRule
	//;
	public DataDescriptionRuleElements getDataDescriptionRuleAccess() {
		return pDataDescriptionRule;
	}
	
	public ParserRule getDataDescriptionRuleRule() {
		return getDataDescriptionRuleAccess().getRule();
	}
	
	//TypedBaseDataDescriptionRule returns TypedBaseDataDescription:
	//    (constraints2 += BaseLanguage::ConstraintRule)*
	//    representation=RepresentationType 'data' name = StringOrId 'of' 'type' type = [DataTypeDefinition|QualifiedName] ('with' 'constraints' ':' (constraints += StatementRule)*)?
	//    ';'
	//;
	public TypedBaseDataDescriptionRuleElements getTypedBaseDataDescriptionRuleAccess() {
		return pTypedBaseDataDescriptionRule;
	}
	
	public ParserRule getTypedBaseDataDescriptionRuleRule() {
		return getTypedBaseDataDescriptionRuleAccess().getRule();
	}
	
	//UntypedBaseDataDescriptionRule returns UntypedBaseDataDescription:
	//    (constraints2 += BaseLanguage::ConstraintRule)*
	// (scale = ScaleType)? representation=RepresentationType 'data' name = StringOrId     ('with' 'constraints' ':' (constraints += StatementRule)*)?
	// ';'
	//;
	public UntypedBaseDataDescriptionRuleElements getUntypedBaseDataDescriptionRuleAccess() {
		return pUntypedBaseDataDescriptionRule;
	}
	
	public ParserRule getUntypedBaseDataDescriptionRuleRule() {
		return getUntypedBaseDataDescriptionRuleAccess().getRule();
	}
	
	//StructuredDataDescriptionRule returns StructuredDataDescription:
	//    'data' name = StringOrId 'of' 'instance'  type = [base::TypeDefinition|QualifiedName] ';'
	//;
	public StructuredDataDescriptionRuleElements getStructuredDataDescriptionRuleAccess() {
		return pStructuredDataDescriptionRule;
	}
	
	public ParserRule getStructuredDataDescriptionRuleRule() {
		return getStructuredDataDescriptionRuleAccess().getRule();
	}
	
	//StatementRule returns base::Expression:
	//    BaseLanguage::ExpressionRule ';'
	//;
	public StatementRuleElements getStatementRuleAccess() {
		return pStatementRule;
	}
	
	public ParserRule getStatementRuleRule() {
		return getStatementRuleAccess().getRule();
	}
	
	//@Override
	//ReferenceRule returns base::ValueReference:
	//    ConstantReferenceRule | DataReferenceRule | SelfReferenceRule
	//;
	public ReferenceRuleElements getReferenceRuleAccess() {
		return pReferenceRule;
	}
	
	public ParserRule getReferenceRuleRule() {
		return getReferenceRuleAccess().getRule();
	}
	
	//DataReferenceRule returns DataReference:
	//    'data' definition = [DataDescription|QualifiedName]
	//;
	public DataReferenceRuleElements getDataReferenceRuleAccess() {
		return pDataReferenceRule;
	}
	
	public ParserRule getDataReferenceRuleRule() {
		return getDataReferenceRuleAccess().getRule();
	}
	
	//SelfReferenceRule returns SelfReference:
	//    {SelfReference}
	//    'value'
	//;
	public SelfReferenceRuleElements getSelfReferenceRuleAccess() {
		return pSelfReferenceRule;
	}
	
	public ParserRule getSelfReferenceRuleRule() {
		return getSelfReferenceRuleAccess().getRule();
	}
	
	//ExpressionRule returns Expression:
	//    OrExpressionRule
	//;
	public BaseLanguageGrammarAccess.ExpressionRuleElements getExpressionRuleAccess() {
		return gaBaseLanguage.getExpressionRuleAccess();
	}
	
	public ParserRule getExpressionRuleRule() {
		return getExpressionRuleAccess().getRule();
	}
	
	//OrExpressionRule returns OrExpression:
	//    subExpressions += XorExpressionRule ( "OR" subExpressions += XorExpressionRule )*
	//;
	public BaseLanguageGrammarAccess.OrExpressionRuleElements getOrExpressionRuleAccess() {
		return gaBaseLanguage.getOrExpressionRuleAccess();
	}
	
	public ParserRule getOrExpressionRuleRule() {
		return getOrExpressionRuleAccess().getRule();
	}
	
	//XorExpressionRule returns XorExpression:
	//    subExpressions += AndExpressionRule ( "XOR" subExpressions += AndExpressionRule )*
	//;
	public BaseLanguageGrammarAccess.XorExpressionRuleElements getXorExpressionRuleAccess() {
		return gaBaseLanguage.getXorExpressionRuleAccess();
	}
	
	public ParserRule getXorExpressionRuleRule() {
		return getXorExpressionRuleAccess().getRule();
	}
	
	//AndExpressionRule returns AndExpression:
	//    subExpressions += NotExpressionRule ( "AND" subExpressions += NotExpressionRule )*
	//;
	public BaseLanguageGrammarAccess.AndExpressionRuleElements getAndExpressionRuleAccess() {
		return gaBaseLanguage.getAndExpressionRuleAccess();
	}
	
	public ParserRule getAndExpressionRuleRule() {
		return getAndExpressionRuleAccess().getRule();
	}
	
	//NotExpressionRule returns NotExpression:
	//    ( negated ?= "!")? operand = ComparisonExpressionRule
	//;
	public BaseLanguageGrammarAccess.NotExpressionRuleElements getNotExpressionRuleAccess() {
		return gaBaseLanguage.getNotExpressionRuleAccess();
	}
	
	public ParserRule getNotExpressionRuleRule() {
		return getNotExpressionRuleAccess().getRule();
	}
	
	//ComparisonExpressionRule returns ComparisonExpression:
	//    leftOperand = AddOrSubtractExpressionRule ( comparison += PartialComparisonExpressionRule )*
	//;
	public BaseLanguageGrammarAccess.ComparisonExpressionRuleElements getComparisonExpressionRuleAccess() {
		return gaBaseLanguage.getComparisonExpressionRuleAccess();
	}
	
	public ParserRule getComparisonExpressionRuleRule() {
		return getComparisonExpressionRuleAccess().getRule();
	}
	
	//PartialComparisonExpressionRule returns PartialComparisonExpression :
	//    operator = ComparisonOperatorRule subExpression = AddOrSubtractExpressionRule
	//;
	public BaseLanguageGrammarAccess.PartialComparisonExpressionRuleElements getPartialComparisonExpressionRuleAccess() {
		return gaBaseLanguage.getPartialComparisonExpressionRuleAccess();
	}
	
	public ParserRule getPartialComparisonExpressionRuleRule() {
		return getPartialComparisonExpressionRuleAccess().getRule();
	}
	
	//enum ComparisonOperatorRule returns ComparisonOperator :
	//    GreaterThan = ">=" |
	//    GreaterEqual = ">" |
	//    Equal = "=" |
	//    Unequal = "!=" |
	//    LessEqual = "<" |
	//    LessThan = "<="
	//;
	public BaseLanguageGrammarAccess.ComparisonOperatorRuleElements getComparisonOperatorRuleAccess() {
		return gaBaseLanguage.getComparisonOperatorRuleAccess();
	}
	
	public EnumRule getComparisonOperatorRuleRule() {
		return getComparisonOperatorRuleAccess().getRule();
	}
	
	//AddOrSubtractExpressionRule returns AddOrSubtractExpression:
	//    leftOperand = MultiplyDivideModuloExpressionRule (operators+=AddOrSubtractOperatorRule operands += MultiplyDivideModuloExpressionRule)*
	//;
	public BaseLanguageGrammarAccess.AddOrSubtractExpressionRuleElements getAddOrSubtractExpressionRuleAccess() {
		return gaBaseLanguage.getAddOrSubtractExpressionRuleAccess();
	}
	
	public ParserRule getAddOrSubtractExpressionRuleRule() {
		return getAddOrSubtractExpressionRuleAccess().getRule();
	}
	
	//enum AddOrSubtractOperatorRule returns AddOrSubtractOperator:
	//    Add = '+' | Subtract = '-'
	//;
	public BaseLanguageGrammarAccess.AddOrSubtractOperatorRuleElements getAddOrSubtractOperatorRuleAccess() {
		return gaBaseLanguage.getAddOrSubtractOperatorRuleAccess();
	}
	
	public EnumRule getAddOrSubtractOperatorRuleRule() {
		return getAddOrSubtractOperatorRuleAccess().getRule();
	}
	
	//MultiplyDivideModuloExpressionRule returns MultiplyDivideModuloExpression :
	//    leftOperand = PowerOfExpressionRule (operators+= MultiplyDivideModuloOperatorRule operands += PowerOfExpressionRule)*
	//;
	public BaseLanguageGrammarAccess.MultiplyDivideModuloExpressionRuleElements getMultiplyDivideModuloExpressionRuleAccess() {
		return gaBaseLanguage.getMultiplyDivideModuloExpressionRuleAccess();
	}
	
	public ParserRule getMultiplyDivideModuloExpressionRuleRule() {
		return getMultiplyDivideModuloExpressionRuleAccess().getRule();
	}
	
	//enum MultiplyDivideModuloOperatorRule returns MultiplyDivideModuloOperator:
	//    Multiply = '*' | Divide = "/" | Modulo = '%'
	//;
	public BaseLanguageGrammarAccess.MultiplyDivideModuloOperatorRuleElements getMultiplyDivideModuloOperatorRuleAccess() {
		return gaBaseLanguage.getMultiplyDivideModuloOperatorRuleAccess();
	}
	
	public EnumRule getMultiplyDivideModuloOperatorRuleRule() {
		return getMultiplyDivideModuloOperatorRuleAccess().getRule();
	}
	
	//PowerOfExpressionRule returns PowerOfExpression :
	//    leftOperand = UnaryAddOrSubtractExpressionRule ('^' rightOperand = PowerOfExpressionRule)?
	//;
	public BaseLanguageGrammarAccess.PowerOfExpressionRuleElements getPowerOfExpressionRuleAccess() {
		return gaBaseLanguage.getPowerOfExpressionRuleAccess();
	}
	
	public ParserRule getPowerOfExpressionRuleRule() {
		return getPowerOfExpressionRuleAccess().getRule();
	}
	
	//UnaryAddOrSubtractExpressionRule returns UnaryAddOrSubtractExpression :
	//    ( operators+=AddOrSubtractOperatorRule )* subExpression = ValueRule
	//;
	public BaseLanguageGrammarAccess.UnaryAddOrSubtractExpressionRuleElements getUnaryAddOrSubtractExpressionRuleAccess() {
		return gaBaseLanguage.getUnaryAddOrSubtractExpressionRuleAccess();
	}
	
	public ParserRule getUnaryAddOrSubtractExpressionRuleRule() {
		return getUnaryAddOrSubtractExpressionRuleAccess().getRule();
	}
	
	//ValueRule returns Value:
	//    ArrayRule | CallRule | LiteralRule | ParanthesesRule | ReferenceRule;
	public BaseLanguageGrammarAccess.ValueRuleElements getValueRuleAccess() {
		return gaBaseLanguage.getValueRuleAccess();
	}
	
	public ParserRule getValueRuleRule() {
		return getValueRuleAccess().getRule();
	}
	
	//ArrayRule returns Array:
	//    {Array}
	//    '[' (values += ValueRule (',' values += ValueRule)* )? ']'
	//;
	public BaseLanguageGrammarAccess.ArrayRuleElements getArrayRuleAccess() {
		return gaBaseLanguage.getArrayRuleAccess();
	}
	
	public ParserRule getArrayRuleRule() {
		return getArrayRuleAccess().getRule();
	}
	
	//ParanthesesRule returns Parantheses:
	//    '(' subExpression = ExpressionRule ')'
	//;
	public BaseLanguageGrammarAccess.ParanthesesRuleElements getParanthesesRuleAccess() {
		return gaBaseLanguage.getParanthesesRuleAccess();
	}
	
	public ParserRule getParanthesesRuleRule() {
		return getParanthesesRuleAccess().getRule();
	}
	
	//CallRule returns Call:
	//    function=FunctionNameRule '(' (parameters += ExpressionRule (',' parameters += ExpressionRule)* )? ')'
	//;
	public BaseLanguageGrammarAccess.CallRuleElements getCallRuleAccess() {
		return gaBaseLanguage.getCallRuleAccess();
	}
	
	public ParserRule getCallRuleRule() {
		return getCallRuleAccess().getRule();
	}
	
	//ConstantReferenceRule returns ConstantReference:
	//    definition = [ConstantDefinition|QualifiedName]
	//;
	public BaseLanguageGrammarAccess.ConstantReferenceRuleElements getConstantReferenceRuleAccess() {
		return gaBaseLanguage.getConstantReferenceRuleAccess();
	}
	
	public ParserRule getConstantReferenceRuleRule() {
		return getConstantReferenceRuleAccess().getRule();
	}
	
	//LiteralRule returns Literal:
	//    NumberLiteralRule
	//        | StringLiteralRule
	//        | BooleanLiteralRule
	//        | InstanceLiteralRule
	//;
	public BaseLanguageGrammarAccess.LiteralRuleElements getLiteralRuleAccess() {
		return gaBaseLanguage.getLiteralRuleAccess();
	}
	
	public ParserRule getLiteralRuleRule() {
		return getLiteralRuleAccess().getRule();
	}
	
	//InstanceLiteralRule returns Instance:
	//    definition = [TypeDefinition|QualifiedName] '{'
	//      attributes += AttributeRule*
	//    '}'
	//;
	public BaseLanguageGrammarAccess.InstanceLiteralRuleElements getInstanceLiteralRuleAccess() {
		return gaBaseLanguage.getInstanceLiteralRuleAccess();
	}
	
	public ParserRule getInstanceLiteralRuleRule() {
		return getInstanceLiteralRuleAccess().getRule();
	}
	
	//AttributeRule returns Attribute:
	//    definition = [AttributeDefinition|StringOrId] ':=' value = ExpressionRule ';'
	//;
	public BaseLanguageGrammarAccess.AttributeRuleElements getAttributeRuleAccess() {
		return gaBaseLanguage.getAttributeRuleAccess();
	}
	
	public ParserRule getAttributeRuleRule() {
		return getAttributeRuleAccess().getRule();
	}
	
	//NumberLiteralRule returns NumberLiteral:
	//    RealLiteralRule | IntegerLiteralRule
	//;
	public BaseLanguageGrammarAccess.NumberLiteralRuleElements getNumberLiteralRuleAccess() {
		return gaBaseLanguage.getNumberLiteralRuleAccess();
	}
	
	public ParserRule getNumberLiteralRuleRule() {
		return getNumberLiteralRuleAccess().getRule();
	}
	
	//RealLiteralRule returns RealLiteral :
	//    literal = DOUBLE (factor = FactorRule)?
	//;
	public BaseLanguageGrammarAccess.RealLiteralRuleElements getRealLiteralRuleAccess() {
		return gaBaseLanguage.getRealLiteralRuleAccess();
	}
	
	public ParserRule getRealLiteralRuleRule() {
		return getRealLiteralRuleAccess().getRule();
	}
	
	//IntegerLiteralRule returns IntegerLiteral:
	//    literal = INT (factor = FactorRule)?
	//;
	public BaseLanguageGrammarAccess.IntegerLiteralRuleElements getIntegerLiteralRuleAccess() {
		return gaBaseLanguage.getIntegerLiteralRuleAccess();
	}
	
	public ParserRule getIntegerLiteralRuleRule() {
		return getIntegerLiteralRuleAccess().getRule();
	}
	
	//StringLiteralRule returns StringLiteral:
	//    value = STRING
	//;
	public BaseLanguageGrammarAccess.StringLiteralRuleElements getStringLiteralRuleAccess() {
		return gaBaseLanguage.getStringLiteralRuleAccess();
	}
	
	public ParserRule getStringLiteralRuleRule() {
		return getStringLiteralRuleAccess().getRule();
	}
	
	//enum FactorRule returns Factor:
	//    Yotta = 'Y' |
	//    Zetta = 'Z' |
	//    Exa = 'E' |
	//    Peta = 'P' |
	//    Tera = 'T' |
	//    Giga = 'G' |
	//    Mega = 'M' |
	//    Kilo = 'k' |
	//    Hecto = 'h' |
	//    Deka = 'da' |
	//    Deci = 'd' |
	//    Centi = 'c' |
	//    Milli = 'm' |
	//    Micro = 'µ' |
	//    Nano = 'n' |
	//    Piko = 'p' |
	//    Femto = 'f' |
	//    Atto = 'a' |
	//    Zepto = 'z' |
	//    Yocto = 'y'
	//;
	public BaseLanguageGrammarAccess.FactorRuleElements getFactorRuleAccess() {
		return gaBaseLanguage.getFactorRuleAccess();
	}
	
	public EnumRule getFactorRuleRule() {
		return getFactorRuleAccess().getRule();
	}
	
	//BooleanLiteralRule returns BooleanLiteral:
	//    {BooleanLiteral} (value ?= 'true' |  'false')
	//;
	public BaseLanguageGrammarAccess.BooleanLiteralRuleElements getBooleanLiteralRuleAccess() {
		return gaBaseLanguage.getBooleanLiteralRuleAccess();
	}
	
	public ParserRule getBooleanLiteralRuleRule() {
		return getBooleanLiteralRuleAccess().getRule();
	}
	
	//TypeDefinitionRule returns TypeDefinition:
	//    (constraints += ConstraintRule)*
	//    (abstract?='abstract')? 'type' name = StringOrId ('extends' superType = [TypeDefinition|QualifiedName])? '{'
	//        attributes += AttributeDefinitionRule*
	//    '}'
	//;
	public BaseLanguageGrammarAccess.TypeDefinitionRuleElements getTypeDefinitionRuleAccess() {
		return gaBaseLanguage.getTypeDefinitionRuleAccess();
	}
	
	public ParserRule getTypeDefinitionRuleRule() {
		return getTypeDefinitionRuleAccess().getRule();
	}
	
	//ConstraintRule returns Instance:
	//    '@' InstanceLiteralRule
	//;
	public BaseLanguageGrammarAccess.ConstraintRuleElements getConstraintRuleAccess() {
		return gaBaseLanguage.getConstraintRuleAccess();
	}
	
	public ParserRule getConstraintRuleRule() {
		return getConstraintRuleAccess().getRule();
	}
	
	//AttributeDefinitionRule returns AttributeDefinition:
	//    (constraints += ConstraintRule)*
	//    name = StringOrId ':' type = TypeRule (':=' initialisation = ExpressionRule)? ';'
	//;
	public BaseLanguageGrammarAccess.AttributeDefinitionRuleElements getAttributeDefinitionRuleAccess() {
		return gaBaseLanguage.getAttributeDefinitionRuleAccess();
	}
	
	public ParserRule getAttributeDefinitionRuleRule() {
		return getAttributeDefinitionRuleAccess().getRule();
	}
	
	//TypeRule returns Type:
	//    StringTypeRule | IntTypeRule | RealTypeRule | BooleanTypeRule | LiteralTypeRule | ArrayTypeRule | InstanceTypeRule | VoidTypeRule | ExpressionTypeRule | DataTypeRule
	//;
	public BaseLanguageGrammarAccess.TypeRuleElements getTypeRuleAccess() {
		return gaBaseLanguage.getTypeRuleAccess();
	}
	
	public ParserRule getTypeRuleRule() {
		return getTypeRuleAccess().getRule();
	}
	
	//LiteralTypeRule returns LiteralType:
	//    {LiteralType} 'literal'
	//;
	public BaseLanguageGrammarAccess.LiteralTypeRuleElements getLiteralTypeRuleAccess() {
		return gaBaseLanguage.getLiteralTypeRuleAccess();
	}
	
	public ParserRule getLiteralTypeRuleRule() {
		return getLiteralTypeRuleAccess().getRule();
	}
	
	//InstanceTypeRule returns InstanceType:
	//    {InstanceType}
	//    'instance' definition = [TypeDefinition|QualifiedName]
	//;
	public BaseLanguageGrammarAccess.InstanceTypeRuleElements getInstanceTypeRuleAccess() {
		return gaBaseLanguage.getInstanceTypeRuleAccess();
	}
	
	public ParserRule getInstanceTypeRuleRule() {
		return getInstanceTypeRuleAccess().getRule();
	}
	
	//StringTypeRule returns StringType:
	//    {StringType}
	//    'string'
	//;
	public BaseLanguageGrammarAccess.StringTypeRuleElements getStringTypeRuleAccess() {
		return gaBaseLanguage.getStringTypeRuleAccess();
	}
	
	public ParserRule getStringTypeRuleRule() {
		return getStringTypeRuleAccess().getRule();
	}
	
	//ExpressionTypeRule returns ExpressionType:
	//    {ExpressionType}
	//    'expression'
	//;
	public BaseLanguageGrammarAccess.ExpressionTypeRuleElements getExpressionTypeRuleAccess() {
		return gaBaseLanguage.getExpressionTypeRuleAccess();
	}
	
	public ParserRule getExpressionTypeRuleRule() {
		return getExpressionTypeRuleAccess().getRule();
	}
	
	//IntTypeRule returns IntType:
	//    {IntType}
	//    'int'
	//;
	public BaseLanguageGrammarAccess.IntTypeRuleElements getIntTypeRuleAccess() {
		return gaBaseLanguage.getIntTypeRuleAccess();
	}
	
	public ParserRule getIntTypeRuleRule() {
		return getIntTypeRuleAccess().getRule();
	}
	
	//RealTypeRule returns RealType:
	//    {RealType}
	//    'real'
	//;
	public BaseLanguageGrammarAccess.RealTypeRuleElements getRealTypeRuleAccess() {
		return gaBaseLanguage.getRealTypeRuleAccess();
	}
	
	public ParserRule getRealTypeRuleRule() {
		return getRealTypeRuleAccess().getRule();
	}
	
	//BooleanTypeRule returns BooleanType:
	//    {BooleanType}
	//    'boolean'
	//;
	public BaseLanguageGrammarAccess.BooleanTypeRuleElements getBooleanTypeRuleAccess() {
		return gaBaseLanguage.getBooleanTypeRuleAccess();
	}
	
	public ParserRule getBooleanTypeRuleRule() {
		return getBooleanTypeRuleAccess().getRule();
	}
	
	//VoidTypeRule returns VoidType:
	//    {VoidType}
	//    'void'
	//;
	public BaseLanguageGrammarAccess.VoidTypeRuleElements getVoidTypeRuleAccess() {
		return gaBaseLanguage.getVoidTypeRuleAccess();
	}
	
	public ParserRule getVoidTypeRuleRule() {
		return getVoidTypeRuleAccess().getRule();
	}
	
	//DataTypeRule returns DataType:
	//    {DataType}
	//    'data'
	//;
	public BaseLanguageGrammarAccess.DataTypeRuleElements getDataTypeRuleAccess() {
		return gaBaseLanguage.getDataTypeRuleAccess();
	}
	
	public ParserRule getDataTypeRuleRule() {
		return getDataTypeRuleAccess().getRule();
	}
	
	//ArrayTypeRule returns ArrayType:
	//    'array'     elements = TypeRule
	//;
	public BaseLanguageGrammarAccess.ArrayTypeRuleElements getArrayTypeRuleAccess() {
		return gaBaseLanguage.getArrayTypeRuleAccess();
	}
	
	public ParserRule getArrayTypeRuleRule() {
		return getArrayTypeRuleAccess().getRule();
	}
	
	//FunctionDefinitionRule returns FunctionDefinition:
	//    'def' type = TypeRule name = StringOrId '(' (parameters+=ParameterRule (',' parameters+=ParameterRule)*)? ')' ';'
	//;
	public BaseLanguageGrammarAccess.FunctionDefinitionRuleElements getFunctionDefinitionRuleAccess() {
		return gaBaseLanguage.getFunctionDefinitionRuleAccess();
	}
	
	public ParserRule getFunctionDefinitionRuleRule() {
		return getFunctionDefinitionRuleAccess().getRule();
	}
	
	//ConstantDefinitionRule returns ConstantDefinition:
	//    'const' type = TypeRule name = StringOrId ':=' value = ExpressionRule ';'
	//;
	public BaseLanguageGrammarAccess.ConstantDefinitionRuleElements getConstantDefinitionRuleAccess() {
		return gaBaseLanguage.getConstantDefinitionRuleAccess();
	}
	
	public ParserRule getConstantDefinitionRuleRule() {
		return getConstantDefinitionRuleAccess().getRule();
	}
	
	//ParameterRule returns Parameter:
	//    type = TypeRule name = StringOrId
	//;
	public BaseLanguageGrammarAccess.ParameterRuleElements getParameterRuleAccess() {
		return gaBaseLanguage.getParameterRuleAccess();
	}
	
	public ParserRule getParameterRuleRule() {
		return getParameterRuleAccess().getRule();
	}
	
	//ImportRule returns Import:
	//    'import' language=STRING 'from' importedNamespace=QualifiedName ";"
	//;
	public BaseLanguageGrammarAccess.ImportRuleElements getImportRuleAccess() {
		return gaBaseLanguage.getImportRuleAccess();
	}
	
	public ParserRule getImportRuleRule() {
		return getImportRuleAccess().getRule();
	}
	
	//FunctionNameRule returns DefinedFunctionName:
	//    definition = [FunctionDefinition|QualifiedName]
	//;
	public BaseLanguageGrammarAccess.FunctionNameRuleElements getFunctionNameRuleAccess() {
		return gaBaseLanguage.getFunctionNameRuleAccess();
	}
	
	public ParserRule getFunctionNameRuleRule() {
		return getFunctionNameRuleAccess().getRule();
	}
	
	//QualifiedName:
	//    StringOrId ('.' StringOrId)*
	//;
	public BaseLanguageGrammarAccess.QualifiedNameElements getQualifiedNameAccess() {
		return gaBaseLanguage.getQualifiedNameAccess();
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}
	
	//StringOrId:
	//    QUOTED_ID | ID;
	public BaseLanguageGrammarAccess.StringOrIdElements getStringOrIdAccess() {
		return gaBaseLanguage.getStringOrIdAccess();
	}
	
	public ParserRule getStringOrIdRule() {
		return getStringOrIdAccess().getRule();
	}
	
	//terminal fragment DIGIT: '0'..'9';
	public TerminalRule getDIGITRule() {
		return gaBaseLanguage.getDIGITRule();
	}
	
	//terminal fragment EXPONENT: 'e' ('+'|'-')? DIGIT+;
	public TerminalRule getEXPONENTRule() {
		return gaBaseLanguage.getEXPONENTRule();
	}
	
	//@Override
	//terminal INT returns ecore::EInt: '-'? DIGIT+;
	public TerminalRule getINTRule() {
		return gaBaseLanguage.getINTRule();
	}
	
	//terminal DOUBLE returns ecore::EDouble: INT EXPONENT | INT '.' DIGIT* EXPONENT?;
	public TerminalRule getDOUBLERule() {
		return gaBaseLanguage.getDOUBLERule();
	}
	
	//@Override
	//terminal STRING:
	//    '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"';
	public TerminalRule getSTRINGRule() {
		return gaBaseLanguage.getSTRINGRule();
	}
	
	//terminal QUOTED_ID:
	//    "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'";
	public TerminalRule getQUOTED_IDRule() {
		return gaBaseLanguage.getQUOTED_IDRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
