/**
 * generated by Xtext 2.25.0
 */
package de.evoal.languages.model.generator.impl;

import de.evoal.languages.model.generator.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class GeneratorFactoryImpl extends EFactoryImpl implements GeneratorFactory {
	/**
	 * Creates the default factory implementation.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static GeneratorFactory init() {
		try {
			GeneratorFactory theGeneratorFactory = (GeneratorFactory)EPackage.Registry.INSTANCE.getEFactory(GeneratorPackage.eNS_URI);
			if (theGeneratorFactory != null) {
				return theGeneratorFactory;
			}
		}
		catch (Exception exception) {
			EcorePlugin.INSTANCE.log(exception);
		}
		return new GeneratorFactoryImpl();
	}

	/**
	 * Creates an instance of the factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public GeneratorFactoryImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public EObject create(EClass eClass) {
		switch (eClass.getClassifierID()) {
			case GeneratorPackage.CONFIGURATION: return createConfiguration();
			case GeneratorPackage.USE: return createUse();
			case GeneratorPackage.PARAMETRIZED_FUNCTION_DEFINITION: return createParametrizedFunctionDefinition();
			case GeneratorPackage.GENERATOR_DEFINITION: return createGeneratorDefinition();
			case GeneratorPackage.STATEMENT: return createStatement();
			case GeneratorPackage.FOR_STATEMENT: return createForStatement();
			case GeneratorPackage.RANGE: return createRange();
			case GeneratorPackage.COUNTER_RANGE: return createCounterRange();
			case GeneratorPackage.FUNCTIONS: return createFunctions();
			case GeneratorPackage.FUNCTION_REFERENCES: return createFunctionReferences();
			case GeneratorPackage.GENERATORS: return createGenerators();
			case GeneratorPackage.GENERATOR_REFERENCES: return createGeneratorReferences();
			case GeneratorPackage.APPLY_STATEMENT: return createApplyStatement();
			case GeneratorPackage.GENERATOR_REFERENCE: return createGeneratorReference();
			case GeneratorPackage.GENERATOR_DEFINITION_REFERENCE: return createGeneratorDefinitionReference();
			case GeneratorPackage.FUNCTION_REFERENCE: return createFunctionReference();
			case GeneratorPackage.FUNCTION_DEF_REFERENCE: return createFunctionDefReference();
			case GeneratorPackage.LOOP_VARIABLE: return createLoopVariable();
			case GeneratorPackage.FUNCTION_DEFINITION_REFERENCE: return createFunctionDefinitionReference();
			case GeneratorPackage.PARAMETRIZED_FUNCTION_DEFINITION_REFERENCE: return createParametrizedFunctionDefinitionReference();
			default:
				throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
		}
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Configuration createConfiguration() {
		ConfigurationImpl configuration = new ConfigurationImpl();
		return configuration;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Use createUse() {
		UseImpl use = new UseImpl();
		return use;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ParametrizedFunctionDefinition createParametrizedFunctionDefinition() {
		ParametrizedFunctionDefinitionImpl parametrizedFunctionDefinition = new ParametrizedFunctionDefinitionImpl();
		return parametrizedFunctionDefinition;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public GeneratorDefinition createGeneratorDefinition() {
		GeneratorDefinitionImpl generatorDefinition = new GeneratorDefinitionImpl();
		return generatorDefinition;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Statement createStatement() {
		StatementImpl statement = new StatementImpl();
		return statement;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ForStatement createForStatement() {
		ForStatementImpl forStatement = new ForStatementImpl();
		return forStatement;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Range createRange() {
		RangeImpl range = new RangeImpl();
		return range;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public CounterRange createCounterRange() {
		CounterRangeImpl counterRange = new CounterRangeImpl();
		return counterRange;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Functions createFunctions() {
		FunctionsImpl functions = new FunctionsImpl();
		return functions;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public FunctionReferences createFunctionReferences() {
		FunctionReferencesImpl functionReferences = new FunctionReferencesImpl();
		return functionReferences;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Generators createGenerators() {
		GeneratorsImpl generators = new GeneratorsImpl();
		return generators;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public GeneratorReferences createGeneratorReferences() {
		GeneratorReferencesImpl generatorReferences = new GeneratorReferencesImpl();
		return generatorReferences;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ApplyStatement createApplyStatement() {
		ApplyStatementImpl applyStatement = new ApplyStatementImpl();
		return applyStatement;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public GeneratorReference createGeneratorReference() {
		GeneratorReferenceImpl generatorReference = new GeneratorReferenceImpl();
		return generatorReference;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public GeneratorDefinitionReference createGeneratorDefinitionReference() {
		GeneratorDefinitionReferenceImpl generatorDefinitionReference = new GeneratorDefinitionReferenceImpl();
		return generatorDefinitionReference;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public FunctionReference createFunctionReference() {
		FunctionReferenceImpl functionReference = new FunctionReferenceImpl();
		return functionReference;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public FunctionDefReference createFunctionDefReference() {
		FunctionDefReferenceImpl functionDefReference = new FunctionDefReferenceImpl();
		return functionDefReference;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public LoopVariable createLoopVariable() {
		LoopVariableImpl loopVariable = new LoopVariableImpl();
		return loopVariable;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public FunctionDefinitionReference createFunctionDefinitionReference() {
		FunctionDefinitionReferenceImpl functionDefinitionReference = new FunctionDefinitionReferenceImpl();
		return functionDefinitionReference;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ParametrizedFunctionDefinitionReference createParametrizedFunctionDefinitionReference() {
		ParametrizedFunctionDefinitionReferenceImpl parametrizedFunctionDefinitionReference = new ParametrizedFunctionDefinitionReferenceImpl();
		return parametrizedFunctionDefinitionReference;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public GeneratorPackage getGeneratorPackage() {
		return (GeneratorPackage)getEPackage();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @deprecated
	 * @generated
	 */
	@Deprecated
	public static GeneratorPackage getPackage() {
		return GeneratorPackage.eINSTANCE;
	}

} //GeneratorFactoryImpl
