grammar de.evoal.languages.model.instance.dsl.InstanceLanguage with de.evoal.languages.model.base.dsl.BaseLanguage

import "https://www.evoal.de/languages/instance/1.0.0" 

import "https://www.evoal.de/languages/ddl/1.0.0" as ddl
import "https://www.evoal.de/languages/base/1.0.0" as base

InstanceRule returns Instance:
	definition = [base::TypeDefinition|QualifiedName] ('{'
	  attributes += AttributeRule*
	'}')?
;

AttributeRule returns Attribute:
	definition = [base::AttributeDefinition|StringOrId] ':=' value = ValueRule ';'
;

ValueRule returns Value:
	ArrayRule | DataReferenceRule | InstanceRule | LiteralValueRule
;

ArrayRule returns Array:
	{Array}
	'[' (values += ValueRule (',' values += ValueRule)* )? ']' 
;

LiteralValueRule returns LiteralValue:
	literal = LiteralRule
;

DataReferenceRule returns DataReference:
	{DataReference}
	'data' definition = [ddl::DataDescription|StringOrId]
;