grammar de.evoal.languages.model.instance.dsl.InstanceLanguage with de.evoal.languages.model.base.dsl.BaseLanguage

import "https://www.evoal.de/languages/instance/1.0.0" 

import "https://www.evoal.de/languages/ddl/1.0.0" as ddl
import "https://www.evoal.de/languages/base/definitions/1.0.0" as defs
import "https://www.evoal.de/languages/base/expressions/1.0.0" as expr


// We do not need the instance language anymore ... This is only there for making Xtext happy
@Override
InstanceLiteralRule returns expr::Instance:
	definition = [defs::TypeDefinition|QualifiedName] '{'
	  attributes += AttributeRule*
	'}'
;
