/*
 * generated by Xtext 2.25.0
 * (c) EvolAl Project
 */
package de.evoal.languages.model.ddl.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DataDescriptionLanguageStandaloneSetup extends DataDescriptionLanguageStandaloneSetupGenerated {

	public static void doSetup() {
		new DataDescriptionLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
