grammar de.evoal.languages.model.ddl.dsl.DataDescriptionLanguage with de.evoal.languages.model.base.dsl.BaseLanguage

import "https://www.evoal.de/languages/dl/1.0.0" as dl
import "https://www.evoal.de/languages/ddl/1.0.0" 
import "http://www.eclipse.org/emf/2002/Ecore" as ecore
import "https://www.evoal.de/languages/base/1.0.0" as base
import "https://www.evoal.de/languages/base/types/1.0.0" as types
import "https://www.evoal.de/languages/base/definitions/1.0.0" as definitions
import "https://www.evoal.de/languages/base/expressions/1.0.0" as expressions


DataDescriptionModelRule returns DataDescriptionModule: 
	(imports += BaseLanguage::ImportRule)*
	'module' name = QualifiedName '{'
		('types' ':' (types += DataTypeDefinitionRule)* )?
		('data' ':' (descriptions += DataDescriptionRule)* )?
		('constraints' ':' (constraints += StatementRule)*)?
	'}'
;

enum ScaleType returns definitions::ScaleType:
	Nominal = 'nominal' |
	Ordinal = 'ordinal' |
	Cardinal = 'cardinal' |
	Quotient = 'quotient'
;

enum RepresentationType returns definitions::RepresentationType:
	Real = 'real' |
	Integer = 'integer' |
	Boolean = 'boolean' |
	String = 'string';

DataTypeDefinitionRule returns definitions::Definition:
	BaseDataTypeTypeDefinitionRule | EnumTypeDefinitionRule
;

BaseDataTypeTypeDefinitionRule returns definitions::DataTypeTypeDefinition:
	(constraints += BaseLanguage::ConstraintRule)*
	scale = ScaleType 
	'type' name = StringOrId  ('with' 'constraints' ':' (constraints += StatementRule)*)?
';'
;

EnumLiteralRule returns definitions::EnumLiteralDefinition:
	name = StringOrId
;

EnumTypeDefinitionRule returns definitions::EnumDefinition:
	(constraints += BaseLanguage::ConstraintRule)*
	scale = ScaleType 
	'enum' name = StringOrId '(' literals += EnumLiteralRule (',' literals += EnumLiteralRule)* ')'
	('with' 'constraints' ':' (constraints += StatementRule)*)?
';'
;


DataDescriptionRule returns definitions::DataDescription:
	TypedBaseDataDescriptionRule | UntypedBaseDataDescriptionRule | StructuredDataDescriptionRule
;

TypedBaseDataDescriptionRule returns definitions::TypedBaseDataDescription:
	representation=RepresentationType 'data' name = StringOrId 'of' 
	// ???
	('with' 'constraints' ':' (constraints += StatementRule)*)?
	';'
;

/**
 * A
 */
UntypedBaseDataDescriptionRule returns definitions::UntypedBaseDataDescription:
	(constraints += BaseLanguage::ConstraintRule)*
 (scale = ScaleType)? representation=RepresentationType 'data' name = StringOrId ('with' 'constraints' ':' (constraints += StatementRule)*)?
 ';'
;

StructuredDataDescriptionRule returns definitions::StructuredDataDescription:
	(constraints += BaseLanguage::ConstraintRule)*
	'data' name = StringOrId 'of' 'instance'  type = [definitions::TypeDefinition|QualifiedName] ';'
;

StatementRule returns expressions::Expression:
	BaseLanguage::ExpressionRule ';'
;


@Override
ReferenceRule returns expressions::ValueReference:
	ConstantReferenceRule | DataReferenceRule | SelfReferenceRule
;

SelfReferenceRule returns expressions::SelfReference:
	{expressions::SelfReference}
	'value'
;
