grammar de.evoal.languages.model.generator.dsl.GeneratorDSL with de.evoal.languages.model.instance.dsl.InstanceLanguage

import "https://www.evoal.de/languages/generator/1.0.0"
import "https://www.evoal.de/languages/base/1.0.0" as base
import "https://www.evoal.de/languages/base/expressions/1.0.0" as expressions

GeneratorModuleRule returns GeneratorModule:
	(imports += ImportRule)*
	
	"module" name = QualifiedName "{"
		(pipelines += PipelineDefinitionRule)*
	
		(statements	+= StatementRule)*
	"}"
;

PipelineDefinitionRule returns PipelineDefinition:
	'pipeline' name = StringOrId '['
		steps += StepRule*
	']'
;

StepRule returns Step:
	'step' '{'
 	    'component' instance = InstanceLiteralRule
 	    ('reads' '[' (reads += DataReferenceRule (',' reads += DataReferenceRule)*)? ']' ';')?
 	    ('writes' '[' (writes += DataReferenceRule (',' writes += DataReferenceRule)*)? ']' ';')?
	'}'
;

StatementRule returns Statement:
	ForStatementRule | ApplyStatementRule	
;

ForStatementRule returns ForStatement:
	'for' name = ID 'in' range = RangeRule 'loop'
		(statements += StatementRule)*
	'end'
;

RangeRule returns Range:
	CounterRangeRule | LiteralRangeRule
;

LiteralRangeRule returns LiteralRange:
	'[' elements += LiteralRule (',' elements += LiteralRule)* ']'
;


CounterRangeRule returns CounterRange:
	'[' start = IntegerLiteralRule 'to' end = IntegerLiteralRule ']'
;


ApplyStatementRule returns ApplyStatement:
	'write' file = STRING 'with' count = LiteralRule 'samples' 'from' 'executing' '[' pipelines += LiteralRule (',' pipelines += LiteralRule)* ']' ';'
;

@Override
LiteralRule returns expressions::Literal:
	NumberLiteralRule
		| StringLiteralRule
		| BooleanLiteralRule
		| InstanceLiteralRule
		| PipelineDefinitionReferenceRule
		| VariableReferenceRule
;

PipelineDefinitionReferenceRule returns PipelineDefinitionReference:
	'pipeline' pipeline = [PipelineDefinition|QualifiedName]
;

VariableReferenceRule returns VariableReference:
	loop = [ForStatement|ID]
;
