grammar de.evoal.languages.model.generator.dsl.GeneratorDSL with de.evoal.languages.model.instance.dsl.InstanceLanguage

import "https://www.evoal.de/languages/dl/1.0.0"
import "https://www.evoal.de/languages/generator/1.0.0"

ConfigurationRule returns Configuration:
	(uses += UseRule)*
	(pipelines += PipelineDefinitionRule)*

	(statements	+= StatementRule)*
;

UseRule returns Use:
	'use' importURI = STRING ';'
;

PipelineDefinitionRule returns PipelineDefinition:
	'pipeline' name = StringOrId '['
		(definitions += InstanceRule (',' definitions += InstanceRule)*)?
	']'
;

StatementRule returns Statement:
	ForStatementRule | ApplyStatementRule	
;

ForStatementRule returns ForStatement:
	'for' name = ID 'in' range = RangeRule 'loop'
		(statements += StatementRule)*
	'end'
;

RangeRule returns Range:
	PipelineArrayRule | CounterRangeRule
;

CounterRangeRule returns CounterRange:
	'[' start = INT 'to' end = INT ']'
;

PipelineArrayRule returns PipelineArray:
	{PipelineArray} 'pipelines' ('[' references += PipelineReferenceRule (',' references += PipelineReferenceRule)* ']')?
;

PipelineReferenceRule returns PipelineReference:
	pipeline = [PipelineDefinition|StringOrId]
;

ApplyStatementRule returns ApplyStatement:
	'write' file = STRING 'with' count = INT 'samples' 'from' 'executing' '[' pipelines += PipelineReferenceRule (',' pipelines += PipelineReferenceRule)* ']' 's;'
;