/*
 * generated by Xtext 2.25.0
 */
package de.evoal.languages.model.generator.dsl;

import java.util.Map;

import org.eclipse.xtext.Constants;
import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.scoping.IGlobalScopeProvider;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;
import org.eclipse.xtext.scoping.impl.DefaultGlobalScopeProvider;
import org.eclipse.xtext.scoping.impl.ImportUriResolver;
import org.eclipse.xtext.workspace.WorkspaceConfig;

import com.google.inject.Binder;
import com.google.inject.Inject;
import com.google.inject.name.Named;
import com.google.inject.name.Names;

import de.evoal.languages.model.generator.dsl.scoping.GeneratorClasspathGlobalScopeProvider;
import de.evoal.languages.model.generator.dsl.scoping.GeneratorDSLLocalScopeProvider;
import de.evoal.languages.model.utils.converter.ValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GeneratorDSLRuntimeModule extends AbstractGeneratorDSLRuntimeModule {
	@Override
	public void configureIScopeProviderDelegate(com.google.inject.Binder binder) {
		binder.bind(org.eclipse.xtext.scoping.IScopeProvider.class)
				.annotatedWith(
						com.google.inject.name.Names
								.named(AbstractDeclarativeScopeProvider.NAMED_DELEGATE))
				.to(GeneratorDSLLocalScopeProvider.class);
	}

	
    @Override
    public Class<? extends IValueConverterService> bindIValueConverterService() {
            return ValueConverterService.class;
    }
    
	public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
		if(System.getProperty("osgi.os") != null) {
			return DefaultGlobalScopeProvider.class;
		} else {
			return GeneratorClasspathGlobalScopeProvider.class;
		}
	}
    
}
