import "definitions" from de.evoal.optimisation.core;

module de.evoal.optimisation.pso.optimisation {
	type 'particle-swarm-optimisation' extends 'algorithm' {
	    'swarm' : instance 'swarm';
	    'size-of-population'  : int;
	    'number-of-generations' : int;
	    'neighborhood-size' : int;
	    'mover' : instance 'pso-mover';
	    //specify GLOBAL, STAR, RING, or SQUARE topology
	    'topology' : string;
	}

	abstract type 'swarm' {
	}

	type 'default-swarm' extends 'swarm' {
	}

	type 'arpso-swarm' extends 'swarm' {
        'diversity-low' : real; //example: 0.000005
        'diversity-high' : real; //example: 0.25
	}

    /**
     * Base type for all particle swarm moving strategies.
     */
	abstract type 'pso-mover' {
	    //specify WRAP, BOUNCE, or STICK boundary type
	    'boundary-type' : string;
	}

    /**
     * Basic PSO moving strategy.
     */
	type 'basic-mover' extends 'pso-mover' {
	    /**
	     * Starting value of inertia weight.
	     */
	    'inertia-start' : real;

	    /**
	     * Ending value of inertia weight.
	     */
	    'inertia-end' : real;

        /**
         * Parameter c1 of basic PSO kinematic equation. Weights influence of individual memory.
         */
        'c1' : real;

        /**
         * Paramter c2 of basic PSO kinematic equation. Weights influence of collective memory.
         */
         'c2' : real;
	}

    /**
     * Fully informed particle swarm (FIPS) mover of Rui Mendes.
     */
	type 'fips-mover' extends 'pso-mover' {
	    /**
	     * Parameter phi of FIPS mover.
	     */
	    phi : real;
	}

	type 'constriction-factor-mover' extends 'pso-mover' {
         /**
          * Parameter c1 of basic PSO kinematic equation. Weights influence of individual memory.
          */
         'c1' : real;

         /**
          * Paramter c2 of basic PSO kinematic equation. Weights influence of collective memory.
          */
          'c2' : real;
    }

    /**
     *  Attractive-repulsive PSO Mover (short ARPSOMover), based on the paper of
     *    Riget and Vesterstrom.
     */
    type 'arpso-mover' extends 'pso-mover' {
	    /**
	     * Starting value of inertia weight. Should be less than 1.
	     */
	    'inertia-start' : real;

	    /**
	     * Ending value of inertia weight.
	     */
	    'inertia-end' : real;

        /**
         * Parameter c1 of basic PSO kinematic equation. Weights influence of individual memory.
         */
        'c1' : real;

        /**
         * Parameter c2 of basic PSO kinematic equation. Weights influence of collective memory.
         */
         'c2' : real;
    }
}