grammar de.evoal.languages.model.ol.dsl.OptimisationLanguage with de.evoal.languages.model.base.dsl.BaseLanguage

import "https://www.evoal.de/languages/ol/1.0.0" 

import "https://www.evoal.de/languages/ddl/1.0.0" as ddl
import "https://www.evoal.de/languages/base/1.0.0" as base
import "https://www.evoal.de/languages/base/definitions/1.0.0" as definitions

OptimisationModelRule returns OptimisationModule:
	(imports += ImportRule)*
	
	"module" name = QualifiedName "{"
		(problem = ProblemRule)?
	
		(algorithm = AlgorithmInstanceRule)?
	"}"
;

ProblemRule returns ProblemInstance:
	"specify" definition=[definitions::TypeDefinition|QualifiedName] name = StringOrId "{"
		attributes+=AttributeRule*
	
		("documenting" ":=" documentation = ArrayRule ';')?
	"}"
;

AlgorithmInstanceRule returns AlgorithmInstance:
	"configure" definition=[definitions::TypeDefinition|QualifiedName] "for" problem = [ProblemInstance|QualifiedName] "{"
		attributes+=AttributeRule*
		
		("documenting" ":=" documentation = ArrayRule ';')?
	"}"
;