grammar de.evoal.languages.model.ol.dsl.OptimisationLanguage with de.evoal.languages.model.base.dsl.BaseLanguage

import "https://www.evoal.de/languages/ol/1.0.0" 

import "https://www.evoal.de/languages/ddl/1.0.0" as ddl
import "https://www.evoal.de/languages/base/1.0.0" as base
import "https://www.evoal.de/languages/base/definitions/1.0.0" as definitions

OptimisationModelRule returns OptimisationModule:
	(imports += ImportRule)*
	
	"module" name = QualifiedName "{"
		(problem = ProblemRule)?
	
		(algorithm = AlgorithmInstanceRule)?
	"}"
;

ProblemRule returns ProblemInstance:
	"specify" definition=[definitions::ClassDefinition|QualifiedName] name = StringOrId "{"
		'search' 'for' searchSpace+=TypeDefinitionReferenceRule (',' searchSpace+=TypeDefinitionReferenceRule)*
		
		'map' 'with' optimisationFunction=InstanceLiteralRule

		'and' optimisationSpace += OptimisationGoalRule (',' optimisationSpace += OptimisationGoalRule)* 
	
		("document" documentation = ArrayRule '.')?
	"}"
;

OptimisationGoalRule returns OptimisationGoal:
	MaximiseGoalRule | MinimiseGoalRule | TargetGoalRule
;

MaximiseGoalRule returns MaximiseGoal:
	'maximise' data=TypeDefinitionReferenceRule
;


MinimiseGoalRule returns MinimiseGoal:
	'minimise' data=TypeDefinitionReferenceRule
;


TargetGoalRule returns TargetGoal:
	'optimise' data=TypeDefinitionReferenceRule 'towards' value=LiteralRule
;

AlgorithmInstanceRule returns AlgorithmInstance:
	"configure" definition=[definitions::ClassDefinition|QualifiedName] "for" problem = [ProblemInstance|QualifiedName] "{"
		attributes+=AttributeRule*
		
		("document" ":=" documentation = ArrayRule ';')?
	"}"
;