grammar de.evoal.languages.model.ol.dsl.OptimisationLanguage with de.evoal.languages.model.instance.dsl.InstanceLanguage

import "https://www.evoal.de/languages/ol/1.0.0" 

import "https://www.evoal.de/languages/ddl/1.0.0" as ddl
import "https://www.evoal.de/languages/instance/1.0.0" as instance
import "https://www.evoal.de/languages/base/1.0.0" as base

OptimisationModelRule returns OptimisationModel:
	(imports += ImportRule)*

	(problem = ProblemRule)?

	(algorithm = AlgorithmInstanceRule)?
;

ProblemRule returns Problem:
	"declare" name = StringOrId "as"
		instance = InstanceLiteralRule
	("documenting" ":=" documentation = ArrayRule ';')?
;

AlgorithmInstanceRule returns AlgorithmInstance:
	"instance" "for" problem = [Problem|QualifiedName] "with" "algorithm"
		instance = InstanceLiteralRule
	("documenting" ":=" documentation = ArrayRule ';')?
;