/*
 * generated by Xtext 2.25.0
 */
package de.evoal.languages.model.generator.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class GeneratorDSLUiModule extends AbstractGeneratorDSLUiModule {

	public GeneratorDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
