/*
 * generated by Xtext 2.41.0
 * (c) EvoAl Project
 */
package de.evoal.languages.model.ddl.dsl.serializer;

import com.google.inject.Inject;
import de.evoal.languages.model.ddl.dsl.services.DataDescriptionLanguageGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class DataDescriptionLanguageSyntacticSequencer extends AbstractSyntacticSequencer {

	protected DataDescriptionLanguageGrammarAccess grammarAccess;
	protected AbstractElementAlias match_BaseDataTypeTypeDefinitionRule___WithKeyword_4_0_ConstraintsKeyword_4_1_ColonKeyword_4_2__q;
	protected AbstractElementAlias match_DataDescriptionModelRule___ConstraintsKeyword_6_0_ColonKeyword_6_1__q;
	protected AbstractElementAlias match_DataDescriptionModelRule___DataKeyword_5_0_ColonKeyword_5_1__q;
	protected AbstractElementAlias match_DataDescriptionModelRule___TypesKeyword_4_0_ColonKeyword_4_1__q;
	protected AbstractElementAlias match_EnumTypeDefinitionRule___WithKeyword_8_0_ConstraintsKeyword_8_1_ColonKeyword_8_2__q;
	protected AbstractElementAlias match_SelfReferenceRule_SelfKeyword_0_1_or_ValueKeyword_1_1;
	protected AbstractElementAlias match_TypedBaseDataDescriptionRule___WithKeyword_6_0_ConstraintsKeyword_6_1_ColonKeyword_6_2__q;
	protected AbstractElementAlias match_UntypedBaseDataDescriptionRule___WithKeyword_5_0_ConstraintsKeyword_5_1_ColonKeyword_5_2__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (DataDescriptionLanguageGrammarAccess) access;
		match_BaseDataTypeTypeDefinitionRule___WithKeyword_4_0_ConstraintsKeyword_4_1_ColonKeyword_4_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getBaseDataTypeTypeDefinitionRuleAccess().getWithKeyword_4_0()), new TokenAlias(false, false, grammarAccess.getBaseDataTypeTypeDefinitionRuleAccess().getConstraintsKeyword_4_1()), new TokenAlias(false, false, grammarAccess.getBaseDataTypeTypeDefinitionRuleAccess().getColonKeyword_4_2()));
		match_DataDescriptionModelRule___ConstraintsKeyword_6_0_ColonKeyword_6_1__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getDataDescriptionModelRuleAccess().getConstraintsKeyword_6_0()), new TokenAlias(false, false, grammarAccess.getDataDescriptionModelRuleAccess().getColonKeyword_6_1()));
		match_DataDescriptionModelRule___DataKeyword_5_0_ColonKeyword_5_1__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getDataDescriptionModelRuleAccess().getDataKeyword_5_0()), new TokenAlias(false, false, grammarAccess.getDataDescriptionModelRuleAccess().getColonKeyword_5_1()));
		match_DataDescriptionModelRule___TypesKeyword_4_0_ColonKeyword_4_1__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getDataDescriptionModelRuleAccess().getTypesKeyword_4_0()), new TokenAlias(false, false, grammarAccess.getDataDescriptionModelRuleAccess().getColonKeyword_4_1()));
		match_EnumTypeDefinitionRule___WithKeyword_8_0_ConstraintsKeyword_8_1_ColonKeyword_8_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getEnumTypeDefinitionRuleAccess().getWithKeyword_8_0()), new TokenAlias(false, false, grammarAccess.getEnumTypeDefinitionRuleAccess().getConstraintsKeyword_8_1()), new TokenAlias(false, false, grammarAccess.getEnumTypeDefinitionRuleAccess().getColonKeyword_8_2()));
		match_SelfReferenceRule_SelfKeyword_0_1_or_ValueKeyword_1_1 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getSelfReferenceRuleAccess().getSelfKeyword_0_1()), new TokenAlias(false, false, grammarAccess.getSelfReferenceRuleAccess().getValueKeyword_1_1()));
		match_TypedBaseDataDescriptionRule___WithKeyword_6_0_ConstraintsKeyword_6_1_ColonKeyword_6_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getTypedBaseDataDescriptionRuleAccess().getWithKeyword_6_0()), new TokenAlias(false, false, grammarAccess.getTypedBaseDataDescriptionRuleAccess().getConstraintsKeyword_6_1()), new TokenAlias(false, false, grammarAccess.getTypedBaseDataDescriptionRuleAccess().getColonKeyword_6_2()));
		match_UntypedBaseDataDescriptionRule___WithKeyword_5_0_ConstraintsKeyword_5_1_ColonKeyword_5_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getUntypedBaseDataDescriptionRuleAccess().getWithKeyword_5_0()), new TokenAlias(false, false, grammarAccess.getUntypedBaseDataDescriptionRuleAccess().getConstraintsKeyword_5_1()), new TokenAlias(false, false, grammarAccess.getUntypedBaseDataDescriptionRuleAccess().getColonKeyword_5_2()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_BaseDataTypeTypeDefinitionRule___WithKeyword_4_0_ConstraintsKeyword_4_1_ColonKeyword_4_2__q.equals(syntax))
				emit_BaseDataTypeTypeDefinitionRule___WithKeyword_4_0_ConstraintsKeyword_4_1_ColonKeyword_4_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_DataDescriptionModelRule___ConstraintsKeyword_6_0_ColonKeyword_6_1__q.equals(syntax))
				emit_DataDescriptionModelRule___ConstraintsKeyword_6_0_ColonKeyword_6_1__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_DataDescriptionModelRule___DataKeyword_5_0_ColonKeyword_5_1__q.equals(syntax))
				emit_DataDescriptionModelRule___DataKeyword_5_0_ColonKeyword_5_1__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_DataDescriptionModelRule___TypesKeyword_4_0_ColonKeyword_4_1__q.equals(syntax))
				emit_DataDescriptionModelRule___TypesKeyword_4_0_ColonKeyword_4_1__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_EnumTypeDefinitionRule___WithKeyword_8_0_ConstraintsKeyword_8_1_ColonKeyword_8_2__q.equals(syntax))
				emit_EnumTypeDefinitionRule___WithKeyword_8_0_ConstraintsKeyword_8_1_ColonKeyword_8_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_SelfReferenceRule_SelfKeyword_0_1_or_ValueKeyword_1_1.equals(syntax))
				emit_SelfReferenceRule_SelfKeyword_0_1_or_ValueKeyword_1_1(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_TypedBaseDataDescriptionRule___WithKeyword_6_0_ConstraintsKeyword_6_1_ColonKeyword_6_2__q.equals(syntax))
				emit_TypedBaseDataDescriptionRule___WithKeyword_6_0_ConstraintsKeyword_6_1_ColonKeyword_6_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_UntypedBaseDataDescriptionRule___WithKeyword_5_0_ConstraintsKeyword_5_1_ColonKeyword_5_2__q.equals(syntax))
				emit_UntypedBaseDataDescriptionRule___WithKeyword_5_0_ConstraintsKeyword_5_1_ColonKeyword_5_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('with' 'constraints' ':')?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=StringOrId (ambiguity) ';' (rule end)
	 
	 * </pre>
	 */
	protected void emit_BaseDataTypeTypeDefinitionRule___WithKeyword_4_0_ConstraintsKeyword_4_1_ColonKeyword_4_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('constraints' ':')?
	 *
	 * This ambiguous syntax occurs at:
	 *     descriptions+=DataDescriptionRule (ambiguity) '}' (rule end)
	 *     name=QualifiedName '{' ('types' ':')? ('data' ':')? (ambiguity) '}' (rule end)
	 *     types+=DataTypeDefinitionRule ('data' ':')? (ambiguity) '}' (rule end)
	 
	 * </pre>
	 */
	protected void emit_DataDescriptionModelRule___ConstraintsKeyword_6_0_ColonKeyword_6_1__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('data' ':')?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=QualifiedName '{' ('types' ':')? (ambiguity) 'constraints' ':' constraints+=StatementRule
	 *     name=QualifiedName '{' ('types' ':')? (ambiguity) ('constraints' ':')? '}' (rule end)
	 *     types+=DataTypeDefinitionRule (ambiguity) 'constraints' ':' constraints+=StatementRule
	 *     types+=DataTypeDefinitionRule (ambiguity) ('constraints' ':')? '}' (rule end)
	 
	 * </pre>
	 */
	protected void emit_DataDescriptionModelRule___DataKeyword_5_0_ColonKeyword_5_1__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('types' ':')?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=QualifiedName '{' (ambiguity) 'data' ':' descriptions+=DataDescriptionRule
	 *     name=QualifiedName '{' (ambiguity) ('data' ':')? 'constraints' ':' constraints+=StatementRule
	 *     name=QualifiedName '{' (ambiguity) ('data' ':')? ('constraints' ':')? '}' (rule end)
	 
	 * </pre>
	 */
	protected void emit_DataDescriptionModelRule___TypesKeyword_4_0_ColonKeyword_4_1__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('with' 'constraints' ':')?
	 *
	 * This ambiguous syntax occurs at:
	 *     literals+=EnumLiteralRule ')' (ambiguity) ';' (rule end)
	 
	 * </pre>
	 */
	protected void emit_EnumTypeDefinitionRule___WithKeyword_8_0_ConstraintsKeyword_8_1_ColonKeyword_8_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     'self' | 'value'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 
	 * </pre>
	 */
	protected void emit_SelfReferenceRule_SelfKeyword_0_1_or_ValueKeyword_1_1(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('with' 'constraints' ':')?
	 *
	 * This ambiguous syntax occurs at:
	 *     type=[DataTypeTypeDefinition|QualifiedName] (ambiguity) ';' (rule end)
	 *     type=[EnumDefinition|QualifiedName] (ambiguity) ';' (rule end)
	 
	 * </pre>
	 */
	protected void emit_TypedBaseDataDescriptionRule___WithKeyword_6_0_ConstraintsKeyword_6_1_ColonKeyword_6_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('with' 'constraints' ':')?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=StringOrId (ambiguity) ';' (rule end)
	 
	 * </pre>
	 */
	protected void emit_UntypedBaseDataDescriptionRule___WithKeyword_5_0_ConstraintsKeyword_5_1_ColonKeyword_5_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
