/**
 * generated by Xtext 2.25.0
 */
package de.evoal.languages.model.generator.dsl.generatorDSL.impl;

import de.evoal.languages.model.generator.dsl.generatorDSL.GeneratorDSLPackage;
import de.evoal.languages.model.generator.dsl.generatorDSL.GeneratorDefinition;
import de.evoal.languages.model.generator.dsl.generatorDSL.GeneratorReferences;

import java.util.Collection;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Generator References</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.evoal.languages.model.generator.dsl.generatorDSL.impl.GeneratorReferencesImpl#getGenerators <em>Generators</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GeneratorReferencesImpl extends MinimalEObjectImpl.Container implements GeneratorReferences
{
  /**
   * The cached value of the '{@link #getGenerators() <em>Generators</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGenerators()
   * @generated
   * @ordered
   */
  protected EList<GeneratorDefinition> generators;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GeneratorReferencesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GeneratorDSLPackage.Literals.GENERATOR_REFERENCES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<GeneratorDefinition> getGenerators()
  {
    if (generators == null)
    {
      generators = new EObjectResolvingEList<GeneratorDefinition>(GeneratorDefinition.class, this, GeneratorDSLPackage.GENERATOR_REFERENCES__GENERATORS);
    }
    return generators;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GeneratorDSLPackage.GENERATOR_REFERENCES__GENERATORS:
        return getGenerators();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GeneratorDSLPackage.GENERATOR_REFERENCES__GENERATORS:
        getGenerators().clear();
        getGenerators().addAll((Collection<? extends GeneratorDefinition>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GeneratorDSLPackage.GENERATOR_REFERENCES__GENERATORS:
        getGenerators().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GeneratorDSLPackage.GENERATOR_REFERENCES__GENERATORS:
        return generators != null && !generators.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //GeneratorReferencesImpl
