/*
 * generated by Xtext 2.25.0
 * (c) EvolAl Project
 */
package de.evoal.languages.model.mll.dsl.validation;


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class MachineLearningLanguageValidator extends AbstractMachineLearningLanguageValidator {
	
//	public static final String INVALID_NAME = "invalidName";
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					MachineLearningLanguagePackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	
}
