package de.evoal.optimisation.ea.main.codec.program.operations;

import de.evoal.core.api.properties.PropertiesSpecification;
import de.evoal.core.api.properties.PropertySpecification;
import io.jenetics.prog.ProgramChromosome;
import io.jenetics.prog.op.Op;
import io.jenetics.util.ISeq;

import java.util.function.Predicate;

/**
 * Genotype information that stores information for the ProgramGenotypeCodec.
 *   It helps to not recalculate necessary information every time.
 *
 * @param searchSpaceProperty The search space property that is represented
 *                              by a {@link io.jenetics.prog.ProgramChromosome}.
 * @param chromosome A created chromosome that can be used as a template for
 *                     creating new (random) chromosomes.
 * @param initialDepth The initial depth of trees when they are generated
 *                       randomly.
 * @param operations List of all internal nodes.
 * @param terminals List of all terminal nodes
 * @param variablesSpecification The properties specification for the
 *                                 evaluation of the function.
 * @param optimisationSpaceProperty The property generated by the function.
 * @param chromosomeIndex Index of the chromosome in the genotype.
 */
public record GenotypeInformation(PropertySpecification searchSpaceProperty,
                                  ProgramChromosome<Double> chromosome,
                                  int initialDepth,
                                  ISeq<Op<Double>> operations,
                                  ISeq<? extends Op<Double>> terminals,
                                  PropertiesSpecification variablesSpecification,
                                  PropertySpecification optimisationSpaceProperty,
                                  int chromosomeIndex,
                                  Predicate<? super ProgramChromosome<Double>> validator) {
}
