<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>de.evoal.core</groupId>
		<artifactId>releng.parent</artifactId>
		<version>0.9.0-SNAPSHOT</version>

		<relativePath>../de.evoal.core.releng.parent</relativePath>
	</parent>

	<artifactId>core.api</artifactId>
	<name>EvoAl - Core - API</name>

	<dependencies>
		<!-- Include dependencies of EvoAl platform -->
		<!-- CDI APIs -->
		<dependency>
			<groupId>jakarta.enterprise</groupId>
			<artifactId>jakarta.enterprise.cdi-api</artifactId>
			<scope>provided</scope>
		</dependency>

		<!-- JSON API -->
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>${jackson.version}</version>
		</dependency>

		<!-- Logging API -->
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>org.apache.deltaspike.core</groupId>
			<artifactId>deltaspike-core-api</artifactId>
			<version>${deltaspike.version}</version>
		</dependency>

		<!-- TODO DO we want this dependency here? -->
		<dependency>
			<groupId>io.jenetics</groupId>
			<artifactId>jenetics</artifactId>
			<version>${jenetics.version}</version>
		</dependency>

		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.dl</artifactId>
			<version>${evoal.languages.version}</version>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.instance</artifactId>
			<version>${evoal.languages.version}</version>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.el</artifactId>
			<version>${evoal.languages.version}</version>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>org.eclipse.emf</groupId>
			<artifactId>org.eclipse.emf.common</artifactId>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>org.eclipse.emf</groupId>
			<artifactId>org.eclipse.emf.ecore</artifactId>
			<scope>provided</scope>
		</dependency>


		<!-- Math stuff -->
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-math3</artifactId>
			<version>3.6.1</version>
		</dependency>

		<dependency>
			<groupId>com.github.haifengl</groupId>
			<artifactId>smile-math</artifactId>
			<version>${smile.version}</version>
		</dependency>
	</dependencies>
</project>
