<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>de.evoal</groupId>
		<artifactId>releng.parent</artifactId>
		<version>0.9.0-SNAPSHOT</version>

		<relativePath>../de.evoal.releng.parent</relativePath>
	</parent>

	<artifactId>core.main</artifactId>
	<name>EvoAl - Core - Main</name>

	<properties>
		<javax.activation.version>1.2.0</javax.activation.version>

		<!-- DeltaSpike uses this version in its documentation. Newer version didn't work for some reasons. -->
		<weld.version>3.1.9.Final</weld.version>
	</properties>

	<dependencies>
		<!-- Prevent me from typing -->
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<scope>compile</scope>
		</dependency>

		<!-- Weld for CDI (@runtime) -->
		<dependency>
			<groupId>org.jboss.weld.se</groupId>
			<artifactId>weld-se-core</artifactId>
			<version>${weld.version}</version>
			<scope>compile</scope>
		</dependency>

		<!--  Jandex results in a NPE at the moment -->
		<dependency>
			<groupId>org.jboss</groupId>
			<artifactId>jandex</artifactId>
			<version>2.4.1.Final</version>
			<scope>runtime</scope>
		</dependency>

		<!-- logback for logging -->
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<version>1.4.5</version>
		</dependency>

		<!-- Deltaspike uses JUL. Use the JUL bridge to reroute it SLF4J -->
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>jul-to-slf4j</artifactId>
			<version>2.0.6</version>
		</dependency>

		<!-- deltaspike -->
		<dependency>
			<groupId>org.apache.deltaspike.core</groupId>
			<artifactId>deltaspike-core-api</artifactId>
			<version>${deltaspike.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>org.apache.deltaspike.cdictrl</groupId>
			<artifactId>deltaspike-cdictrl-api</artifactId>
			<version>${deltaspike.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>org.apache.deltaspike.cdictrl</groupId>
			<artifactId>deltaspike-cdictrl-weld</artifactId>
			<version>${deltaspike.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>org.apache.deltaspike.core</groupId>
			<artifactId>deltaspike-core-impl</artifactId>
			<version>${deltaspike.version}</version>
			<scope>runtime</scope>
		</dependency>

		<!-- Include dependencies of parent -->
		<!-- CDI APIs -->
		<dependency>
			<groupId>jakarta.inject</groupId>
			<artifactId>jakarta.inject-api</artifactId>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>jakarta.enterprise</groupId>
			<artifactId>jakarta.enterprise.cdi-api</artifactId>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>javax.annotation</groupId>
			<artifactId>javax.annotation-api</artifactId>
			<scope>compile</scope>
		</dependency>

		<!-- JSON API -->
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>${jackson.version}</version>
			<scope>compile</scope>
		</dependency>

		<!-- Logging API -->
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<scope>compile</scope>
		</dependency>

		<!-- CSV IO -->
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-csv</artifactId>
			<version>1.8</version>
			<scope>compile</scope>
		</dependency>


		<!-- dependencies to language models -->
		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.ddl</artifactId>
			<version>${evoal.languages.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.dl</artifactId>
			<version>${evoal.languages.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.ol</artifactId>
			<version>${evoal.languages.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.base</artifactId>
			<version>${evoal.languages.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.instance</artifactId>
			<version>${evoal.languages.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.mll</artifactId>
			<version>${evoal.languages.version}</version>
			<scope>compile</scope>
		</dependency>

		<!-- dependencies to DSLs -->
		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.ddl.dsl</artifactId>
			<version>${evoal.languages.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.dl.dsl</artifactId>
			<version>${evoal.languages.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.ol.dsl</artifactId>
			<version>${evoal.languages.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.base.dsl</artifactId>
			<version>${evoal.languages.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.instance.dsl</artifactId>
			<version>${evoal.languages.version}</version>
			<scope>runtime</scope>
		</dependency>

		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.mll.dsl</artifactId>
			<version>${evoal.languages.version}</version>
			<scope>runtime</scope>
		</dependency>

		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.utils</artifactId>
			<version>${evoal.languages.version}</version>
		</dependency>

		<!-- Xtext -->
		<dependency>
			<groupId>org.eclipse.emf</groupId>
			<artifactId>org.eclipse.emf.ecore</artifactId>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>org.eclipse.emf</groupId>
			<artifactId>org.eclipse.emf.common</artifactId>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>org.eclipse.xtext</groupId>
			<artifactId>org.eclipse.xtext</artifactId>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>org.eclipse.xtext</groupId>
			<artifactId>org.eclipse.xtext.util</artifactId>
			<version>2.29.0</version>
			<scope>compile</scope>
		</dependency>

		<!-- Math stuff -->
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-math3</artifactId>
			<version>3.6.1</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
		</dependency>

		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>core.junit</artifactId>
			<version>${project.version}</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<artifactId>maven-dependency-plugin</artifactId>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<configuration>
							<outputDirectory>${project.build.directory}/${project.artifactId}</outputDirectory>
							<includeScope>runtime</includeScope>
							<excludeScope>test</excludeScope>
							<excludeScope>system</excludeScope>
							<excludeArtifactIds>
								org.eclipse.xtext.util,jboss-annotations-api_1.3_spec,jboss-el-api_3.0_spec,jboss-interceptors-api_1.2_spec,javax.annotation-api,jsr305,javax.inject
							</excludeArtifactIds>
							<excludeTransitive>false</excludeTransitive>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>
