/*
 * generated by Xtext 2.29.0
 * (c) EvoAl Project
 */
package de.evoal.languages.model.instance.dsl.ui.contentassist;

import de.evoal.languages.model.base.dsl.ui.contentassist.BaseLanguageProposalProvider;

/**
 * Represents a generated, default implementation of superclass {@link BaseLanguageProposalProvider}.
 * Methods are dynamically dispatched on the first parameter, i.e., you can override them 
 * with a more concrete subtype. 
 */
public abstract class AbstractInstanceLanguageProposalProvider extends BaseLanguageProposalProvider {

}
