/*
 * generated by Xtext 2.29.0
 * (c) EvoAl Project
 */
package de.evoal.languages.model.mll.dsl.serializer;

import com.google.inject.Inject;
import de.evoal.languages.model.base.BasePackage;
import de.evoal.languages.model.base.Import;
import de.evoal.languages.model.base.definitions.AttributeDefinition;
import de.evoal.languages.model.base.definitions.ClassDefinition;
import de.evoal.languages.model.base.definitions.ConstantDefinition;
import de.evoal.languages.model.base.definitions.DefinitionsPackage;
import de.evoal.languages.model.base.definitions.FunctionDefinition;
import de.evoal.languages.model.base.expressions.AddOrSubtractExpression;
import de.evoal.languages.model.base.expressions.AndExpression;
import de.evoal.languages.model.base.expressions.Array;
import de.evoal.languages.model.base.expressions.Attribute;
import de.evoal.languages.model.base.expressions.BooleanLiteral;
import de.evoal.languages.model.base.expressions.Call;
import de.evoal.languages.model.base.expressions.ComparisonExpression;
import de.evoal.languages.model.base.expressions.ExpressionsPackage;
import de.evoal.languages.model.base.expressions.Instance;
import de.evoal.languages.model.base.expressions.IntegerLiteral;
import de.evoal.languages.model.base.expressions.LiteralDefinitionReference;
import de.evoal.languages.model.base.expressions.MultiplyDivideModuloExpression;
import de.evoal.languages.model.base.expressions.NotExpression;
import de.evoal.languages.model.base.expressions.OrExpression;
import de.evoal.languages.model.base.expressions.Parantheses;
import de.evoal.languages.model.base.expressions.PartialComparisonExpression;
import de.evoal.languages.model.base.expressions.PowerOfExpression;
import de.evoal.languages.model.base.expressions.RealLiteral;
import de.evoal.languages.model.base.expressions.StringLiteral;
import de.evoal.languages.model.base.expressions.TypeDefinitionReference;
import de.evoal.languages.model.base.expressions.UnaryAddOrSubtractExpression;
import de.evoal.languages.model.base.expressions.XorExpression;
import de.evoal.languages.model.base.types.ArrayType;
import de.evoal.languages.model.base.types.BooleanType;
import de.evoal.languages.model.base.types.DataType;
import de.evoal.languages.model.base.types.DefinitionReference;
import de.evoal.languages.model.base.types.ExpressionType;
import de.evoal.languages.model.base.types.IntType;
import de.evoal.languages.model.base.types.LiteralType;
import de.evoal.languages.model.base.types.RealType;
import de.evoal.languages.model.base.types.StringType;
import de.evoal.languages.model.base.types.TypesPackage;
import de.evoal.languages.model.base.types.VoidType;
import de.evoal.languages.model.execution.Block;
import de.evoal.languages.model.execution.CallBuiltinFunction;
import de.evoal.languages.model.execution.CounterRange;
import de.evoal.languages.model.execution.ExecutionPackage;
import de.evoal.languages.model.execution.ForStatement;
import de.evoal.languages.model.execution.NamedVariable;
import de.evoal.languages.model.execution.ValueRange;
import de.evoal.languages.model.execution.VariableReference;
import de.evoal.languages.model.generator.ApplyStatement;
import de.evoal.languages.model.generator.ConcreteStep;
import de.evoal.languages.model.generator.GeneratorModule;
import de.evoal.languages.model.generator.GeneratorPackage;
import de.evoal.languages.model.generator.PipelineDefinition;
import de.evoal.languages.model.generator.PipelineStep;
import de.evoal.languages.model.generator.dsl.serializer.GeneratorDSLSemanticSequencer;
import de.evoal.languages.model.mll.MachineLearningModule;
import de.evoal.languages.model.mll.MllPackage;
import de.evoal.languages.model.mll.TaskDescription;
import de.evoal.languages.model.mll.dsl.services.MachineLearningLanguageGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;

@SuppressWarnings("all")
public class MachineLearningLanguageSemanticSequencer extends GeneratorDSLSemanticSequencer {

	@Inject
	private MachineLearningLanguageGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == BasePackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case BasePackage.IMPORT:
				sequence_ImportRule(context, (Import) semanticObject); 
				return; 
			}
		else if (epackage == DefinitionsPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case DefinitionsPackage.ATTRIBUTE_DEFINITION:
				sequence_AttributeDefinitionRule(context, (AttributeDefinition) semanticObject); 
				return; 
			case DefinitionsPackage.CLASS_DEFINITION:
				sequence_ClassDefinitionRule(context, (ClassDefinition) semanticObject); 
				return; 
			case DefinitionsPackage.CONSTANT_DEFINITION:
				sequence_ConstantDefinitionRule(context, (ConstantDefinition) semanticObject); 
				return; 
			case DefinitionsPackage.FUNCTION_DEFINITION:
				sequence_FunctionDefinitionRule(context, (FunctionDefinition) semanticObject); 
				return; 
			case DefinitionsPackage.PARAMETER:
				sequence_ParameterRule(context, (de.evoal.languages.model.base.definitions.Parameter) semanticObject); 
				return; 
			}
		else if (epackage == ExecutionPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case ExecutionPackage.BLOCK:
				if (rule == grammarAccess.getBodyRuleRule()) {
					sequence_BodyRule(context, (Block) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getLearningUseCaseRuleRule()) {
					sequence_LearningUseCaseRule(context, (Block) semanticObject); 
					return; 
				}
				else break;
			case ExecutionPackage.CALL_BUILTIN_FUNCTION:
				sequence_CallBuiltInFunctionRule(context, (CallBuiltinFunction) semanticObject); 
				return; 
			case ExecutionPackage.COUNTER_RANGE:
				sequence_CounterRangeRule(context, (CounterRange) semanticObject); 
				return; 
			case ExecutionPackage.FOR_STATEMENT:
				sequence_ForStatementRule(context, (ForStatement) semanticObject); 
				return; 
			case ExecutionPackage.NAMED_VARIABLE:
				sequence_NamedVariableRule(context, (NamedVariable) semanticObject); 
				return; 
			case ExecutionPackage.VALUE_RANGE:
				sequence_LiteralRangeRule(context, (ValueRange) semanticObject); 
				return; 
			case ExecutionPackage.VARIABLE_REFERENCE:
				sequence_VariableReferenceRule(context, (VariableReference) semanticObject); 
				return; 
			}
		else if (epackage == ExpressionsPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case ExpressionsPackage.ADD_OR_SUBTRACT_EXPRESSION:
				sequence_AddOrSubtractExpressionRule(context, (AddOrSubtractExpression) semanticObject); 
				return; 
			case ExpressionsPackage.AND_EXPRESSION:
				sequence_AndExpressionRule(context, (AndExpression) semanticObject); 
				return; 
			case ExpressionsPackage.ARRAY:
				sequence_ArrayRule(context, (Array) semanticObject); 
				return; 
			case ExpressionsPackage.ATTRIBUTE:
				sequence_AttributeRule(context, (Attribute) semanticObject); 
				return; 
			case ExpressionsPackage.BOOLEAN_LITERAL:
				sequence_BooleanLiteralRule(context, (BooleanLiteral) semanticObject); 
				return; 
			case ExpressionsPackage.CALL:
				sequence_CallRule(context, (Call) semanticObject); 
				return; 
			case ExpressionsPackage.COMPARISON_EXPRESSION:
				sequence_ComparisonExpressionRule(context, (ComparisonExpression) semanticObject); 
				return; 
			case ExpressionsPackage.INSTANCE:
				sequence_InstanceLiteralRule(context, (Instance) semanticObject); 
				return; 
			case ExpressionsPackage.INTEGER_LITERAL:
				sequence_IntegerLiteralRule(context, (IntegerLiteral) semanticObject); 
				return; 
			case ExpressionsPackage.LITERAL_DEFINITION_REFERENCE:
				sequence_LiteralDefinitionReferenceRule(context, (LiteralDefinitionReference) semanticObject); 
				return; 
			case ExpressionsPackage.MULTIPLY_DIVIDE_MODULO_EXPRESSION:
				sequence_MultiplyDivideModuloExpressionRule(context, (MultiplyDivideModuloExpression) semanticObject); 
				return; 
			case ExpressionsPackage.NOT_EXPRESSION:
				sequence_NotExpressionRule(context, (NotExpression) semanticObject); 
				return; 
			case ExpressionsPackage.OR_EXPRESSION:
				sequence_OrExpressionRule(context, (OrExpression) semanticObject); 
				return; 
			case ExpressionsPackage.PARANTHESES:
				sequence_ParanthesesRule(context, (Parantheses) semanticObject); 
				return; 
			case ExpressionsPackage.PARTIAL_COMPARISON_EXPRESSION:
				sequence_PartialComparisonExpressionRule(context, (PartialComparisonExpression) semanticObject); 
				return; 
			case ExpressionsPackage.POWER_OF_EXPRESSION:
				sequence_PowerOfExpressionRule(context, (PowerOfExpression) semanticObject); 
				return; 
			case ExpressionsPackage.REAL_LITERAL:
				sequence_RealLiteralRule(context, (RealLiteral) semanticObject); 
				return; 
			case ExpressionsPackage.STRING_LITERAL:
				sequence_StringLiteralRule(context, (StringLiteral) semanticObject); 
				return; 
			case ExpressionsPackage.TYPE_DEFINITION_REFERENCE:
				if (rule == grammarAccess.getReferenceRuleRule()
						|| rule == grammarAccess.getReadExpressionRuleRule()
						|| rule == grammarAccess.getTypeDefinitionReferenceRuleRule()) {
					sequence_BaseDataReferenceRule_StructuredDataDescriptionReferenceRule(context, (TypeDefinitionReference) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getBaseDataReferenceRuleRule()) {
					sequence_BaseDataReferenceRule(context, (TypeDefinitionReference) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getStructuredDataDescriptionReferenceRuleRule()) {
					sequence_StructuredDataDescriptionReferenceRule(context, (TypeDefinitionReference) semanticObject); 
					return; 
				}
				else break;
			case ExpressionsPackage.UNARY_ADD_OR_SUBTRACT_EXPRESSION:
				sequence_UnaryAddOrSubtractExpressionRule(context, (UnaryAddOrSubtractExpression) semanticObject); 
				return; 
			case ExpressionsPackage.XOR_EXPRESSION:
				sequence_XorExpressionRule(context, (XorExpression) semanticObject); 
				return; 
			}
		else if (epackage == GeneratorPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case GeneratorPackage.APPLY_STATEMENT:
				sequence_ApplyStatementRule(context, (ApplyStatement) semanticObject); 
				return; 
			case GeneratorPackage.CONCRETE_STEP:
				sequence_ConcreteStepRule(context, (ConcreteStep) semanticObject); 
				return; 
			case GeneratorPackage.GENERATOR_MODULE:
				sequence_GeneratorModuleRule(context, (GeneratorModule) semanticObject); 
				return; 
			case GeneratorPackage.PIPELINE_DEFINITION:
				if (rule == grammarAccess.getPipelineDefinitionRuleRule()) {
					sequence_PipelineDefinitionRule(context, (PipelineDefinition) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getPredictionUseCaseRuleRule()) {
					sequence_PredictionUseCaseRule(context, (PipelineDefinition) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getPreparationPipelineDefinitionRuleRule()) {
					sequence_PreparationPipelineDefinitionRule(context, (PipelineDefinition) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getValidationPipelineDefinitionRuleRule()) {
					sequence_ValidationPipelineDefinitionRule(context, (PipelineDefinition) semanticObject); 
					return; 
				}
				else break;
			case GeneratorPackage.PIPELINE_STEP:
				sequence_PipelineStepRule(context, (PipelineStep) semanticObject); 
				return; 
			}
		else if (epackage == MllPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case MllPackage.MACHINE_LEARNING_MODULE:
				sequence_MachineLearningModuleRule(context, (MachineLearningModule) semanticObject); 
				return; 
			case MllPackage.TASK_DESCRIPTION:
				sequence_TaskDescriptionRule(context, (TaskDescription) semanticObject); 
				return; 
			}
		else if (epackage == TypesPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case TypesPackage.ARRAY_TYPE:
				sequence_ArrayTypeRule(context, (ArrayType) semanticObject); 
				return; 
			case TypesPackage.BOOLEAN_TYPE:
				sequence_BooleanTypeRule(context, (BooleanType) semanticObject); 
				return; 
			case TypesPackage.DATA_TYPE:
				sequence_DataTypeRule(context, (DataType) semanticObject); 
				return; 
			case TypesPackage.DEFINITION_REFERENCE:
				if (rule == grammarAccess.getEnumReferenceRuleRule()) {
					sequence_EnumReferenceRule(context, (DefinitionReference) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getTypeRuleRule()) {
					sequence_EnumReferenceRule_TypeReferenceRule(context, (DefinitionReference) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getTypeReferenceRuleRule()) {
					sequence_TypeReferenceRule(context, (DefinitionReference) semanticObject); 
					return; 
				}
				else break;
			case TypesPackage.EXPRESSION_TYPE:
				sequence_ExpressionTypeRule(context, (ExpressionType) semanticObject); 
				return; 
			case TypesPackage.INT_TYPE:
				sequence_IntTypeRule(context, (IntType) semanticObject); 
				return; 
			case TypesPackage.LITERAL_TYPE:
				sequence_LiteralTypeRule(context, (LiteralType) semanticObject); 
				return; 
			case TypesPackage.REAL_TYPE:
				sequence_RealTypeRule(context, (RealType) semanticObject); 
				return; 
			case TypesPackage.STRING_TYPE:
				sequence_StringTypeRule(context, (StringType) semanticObject); 
				return; 
			case TypesPackage.VOID_TYPE:
				sequence_VoidTypeRule(context, (VoidType) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     LearningUseCaseRule returns Block
	 *
	 * Constraint:
	 *     statements+=StatementRule*
	 * </pre>
	 */
	protected void sequence_LearningUseCaseRule(ISerializationContext context, Block semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     MachineLearningModuleRule returns MachineLearningModule
	 *
	 * Constraint:
	 *     (
	 *         imports+=ImportRule* 
	 *         name=QualifiedName 
	 *         task=TaskDescriptionRule 
	 *         validation=ValidationPipelineDefinitionRule 
	 *         preparation=PreparationPipelineDefinitionRule 
	 *         model=InstanceLiteralRule 
	 *         gof=BodyRule? 
	 *         learningUseCase=LearningUseCaseRule? 
	 *         predictionUseCase=PredictionUseCaseRule?
	 *     )
	 * </pre>
	 */
	protected void sequence_MachineLearningModuleRule(ISerializationContext context, MachineLearningModule semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     PredictionUseCaseRule returns PipelineDefinition
	 *
	 * Constraint:
	 *     (name='predicting' steps+=StepRule*)
	 * </pre>
	 */
	protected void sequence_PredictionUseCaseRule(ISerializationContext context, PipelineDefinition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     PreparationPipelineDefinitionRule returns PipelineDefinition
	 *
	 * Constraint:
	 *     (name='preparation' steps+=StepRule*)
	 * </pre>
	 */
	protected void sequence_PreparationPipelineDefinitionRule(ISerializationContext context, PipelineDefinition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TaskDescriptionRule returns TaskDescription
	 *
	 * Constraint:
	 *     (
	 *         name='learning-task' 
	 *         inputs+=[DataDescription|QualifiedName] 
	 *         inputs+=[DataDescription|QualifiedName]* 
	 *         outputs+=[DataDescription|QualifiedName] 
	 *         outputs+=[DataDescription|QualifiedName]* 
	 *         learningData+=STRING 
	 *         learningData+=STRING* 
	 *         (testingData+=STRING testingData+=STRING*)? 
	 *         modelFile=STRING 
	 *         gofFile=STRING?
	 *     )
	 * </pre>
	 */
	protected void sequence_TaskDescriptionRule(ISerializationContext context, TaskDescription semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ValidationPipelineDefinitionRule returns PipelineDefinition
	 *
	 * Constraint:
	 *     (name='validation' steps+=StepRule*)
	 * </pre>
	 */
	protected void sequence_ValidationPipelineDefinitionRule(ISerializationContext context, PipelineDefinition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
