/*
 * generated by Xtext 2.29.0
 */
package de.evoal.languages.model.generator.dsl.serializer;

import com.google.inject.Inject;
import de.evoal.languages.model.base.AddOrSubtractExpression;
import de.evoal.languages.model.base.AndExpression;
import de.evoal.languages.model.base.Array;
import de.evoal.languages.model.base.ArrayType;
import de.evoal.languages.model.base.Attribute;
import de.evoal.languages.model.base.AttributeDefinition;
import de.evoal.languages.model.base.BasePackage;
import de.evoal.languages.model.base.BooleanLiteral;
import de.evoal.languages.model.base.BooleanType;
import de.evoal.languages.model.base.Call;
import de.evoal.languages.model.base.ComparisonExpression;
import de.evoal.languages.model.base.ConstantDefinition;
import de.evoal.languages.model.base.ConstantReference;
import de.evoal.languages.model.base.DataType;
import de.evoal.languages.model.base.DefinedFunctionName;
import de.evoal.languages.model.base.ExpressionType;
import de.evoal.languages.model.base.FunctionDefinition;
import de.evoal.languages.model.base.Import;
import de.evoal.languages.model.base.Instance;
import de.evoal.languages.model.base.InstanceType;
import de.evoal.languages.model.base.IntType;
import de.evoal.languages.model.base.IntegerLiteral;
import de.evoal.languages.model.base.LiteralType;
import de.evoal.languages.model.base.MultiplyDivideModuloExpression;
import de.evoal.languages.model.base.NotExpression;
import de.evoal.languages.model.base.OrExpression;
import de.evoal.languages.model.base.Parantheses;
import de.evoal.languages.model.base.PartialComparisonExpression;
import de.evoal.languages.model.base.PowerOfExpression;
import de.evoal.languages.model.base.RealLiteral;
import de.evoal.languages.model.base.RealType;
import de.evoal.languages.model.base.StringLiteral;
import de.evoal.languages.model.base.StringType;
import de.evoal.languages.model.base.TypeDefinition;
import de.evoal.languages.model.base.UnaryAddOrSubtractExpression;
import de.evoal.languages.model.base.VoidType;
import de.evoal.languages.model.base.XorExpression;
import de.evoal.languages.model.ddl.DdlPackage;
import de.evoal.languages.model.ddl.EnumLiteralReference;
import de.evoal.languages.model.generator.ApplyStatement;
import de.evoal.languages.model.generator.CounterRange;
import de.evoal.languages.model.generator.ForStatement;
import de.evoal.languages.model.generator.GeneratorModule;
import de.evoal.languages.model.generator.GeneratorPackage;
import de.evoal.languages.model.generator.LiteralRange;
import de.evoal.languages.model.generator.PipelineDefinition;
import de.evoal.languages.model.generator.PipelineDefinitionReference;
import de.evoal.languages.model.generator.Step;
import de.evoal.languages.model.generator.VariableReference;
import de.evoal.languages.model.generator.dsl.services.GeneratorDSLGrammarAccess;
import de.evoal.languages.model.instance.DataReference;
import de.evoal.languages.model.instance.InstancePackage;
import de.evoal.languages.model.instance.dsl.serializer.InstanceLanguageSemanticSequencer;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class GeneratorDSLSemanticSequencer extends InstanceLanguageSemanticSequencer {

	@Inject
	private GeneratorDSLGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == BasePackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case BasePackage.ADD_OR_SUBTRACT_EXPRESSION:
				sequence_AddOrSubtractExpressionRule(context, (AddOrSubtractExpression) semanticObject); 
				return; 
			case BasePackage.AND_EXPRESSION:
				sequence_AndExpressionRule(context, (AndExpression) semanticObject); 
				return; 
			case BasePackage.ARRAY:
				sequence_ArrayRule(context, (Array) semanticObject); 
				return; 
			case BasePackage.ARRAY_TYPE:
				sequence_ArrayTypeRule(context, (ArrayType) semanticObject); 
				return; 
			case BasePackage.ATTRIBUTE:
				sequence_AttributeRule(context, (Attribute) semanticObject); 
				return; 
			case BasePackage.ATTRIBUTE_DEFINITION:
				sequence_AttributeDefinitionRule(context, (AttributeDefinition) semanticObject); 
				return; 
			case BasePackage.BOOLEAN_LITERAL:
				sequence_BooleanLiteralRule(context, (BooleanLiteral) semanticObject); 
				return; 
			case BasePackage.BOOLEAN_TYPE:
				sequence_BooleanTypeRule(context, (BooleanType) semanticObject); 
				return; 
			case BasePackage.CALL:
				sequence_CallRule(context, (Call) semanticObject); 
				return; 
			case BasePackage.COMPARISON_EXPRESSION:
				sequence_ComparisonExpressionRule(context, (ComparisonExpression) semanticObject); 
				return; 
			case BasePackage.CONSTANT_DEFINITION:
				sequence_ConstantDefinitionRule(context, (ConstantDefinition) semanticObject); 
				return; 
			case BasePackage.CONSTANT_REFERENCE:
				sequence_ConstantReferenceRule(context, (ConstantReference) semanticObject); 
				return; 
			case BasePackage.DATA_TYPE:
				sequence_DataTypeRule(context, (DataType) semanticObject); 
				return; 
			case BasePackage.DEFINED_FUNCTION_NAME:
				sequence_FunctionNameRule(context, (DefinedFunctionName) semanticObject); 
				return; 
			case BasePackage.EXPRESSION_TYPE:
				sequence_ExpressionTypeRule(context, (ExpressionType) semanticObject); 
				return; 
			case BasePackage.FUNCTION_DEFINITION:
				sequence_FunctionDefinitionRule(context, (FunctionDefinition) semanticObject); 
				return; 
			case BasePackage.IMPORT:
				sequence_ImportRule(context, (Import) semanticObject); 
				return; 
			case BasePackage.INSTANCE:
				sequence_InstanceLiteralRule(context, (Instance) semanticObject); 
				return; 
			case BasePackage.INSTANCE_TYPE:
				sequence_InstanceTypeRule(context, (InstanceType) semanticObject); 
				return; 
			case BasePackage.INT_TYPE:
				sequence_IntTypeRule(context, (IntType) semanticObject); 
				return; 
			case BasePackage.INTEGER_LITERAL:
				sequence_IntegerLiteralRule(context, (IntegerLiteral) semanticObject); 
				return; 
			case BasePackage.LITERAL_TYPE:
				sequence_LiteralTypeRule(context, (LiteralType) semanticObject); 
				return; 
			case BasePackage.MULTIPLY_DIVIDE_MODULO_EXPRESSION:
				sequence_MultiplyDivideModuloExpressionRule(context, (MultiplyDivideModuloExpression) semanticObject); 
				return; 
			case BasePackage.NOT_EXPRESSION:
				sequence_NotExpressionRule(context, (NotExpression) semanticObject); 
				return; 
			case BasePackage.OR_EXPRESSION:
				sequence_OrExpressionRule(context, (OrExpression) semanticObject); 
				return; 
			case BasePackage.PARAMETER:
				sequence_ParameterRule(context, (de.evoal.languages.model.base.Parameter) semanticObject); 
				return; 
			case BasePackage.PARANTHESES:
				sequence_ParanthesesRule(context, (Parantheses) semanticObject); 
				return; 
			case BasePackage.PARTIAL_COMPARISON_EXPRESSION:
				sequence_PartialComparisonExpressionRule(context, (PartialComparisonExpression) semanticObject); 
				return; 
			case BasePackage.POWER_OF_EXPRESSION:
				sequence_PowerOfExpressionRule(context, (PowerOfExpression) semanticObject); 
				return; 
			case BasePackage.REAL_LITERAL:
				sequence_RealLiteralRule(context, (RealLiteral) semanticObject); 
				return; 
			case BasePackage.REAL_TYPE:
				sequence_RealTypeRule(context, (RealType) semanticObject); 
				return; 
			case BasePackage.STRING_LITERAL:
				sequence_StringLiteralRule(context, (StringLiteral) semanticObject); 
				return; 
			case BasePackage.STRING_TYPE:
				sequence_StringTypeRule(context, (StringType) semanticObject); 
				return; 
			case BasePackage.TYPE_DEFINITION:
				sequence_TypeDefinitionRule(context, (TypeDefinition) semanticObject); 
				return; 
			case BasePackage.UNARY_ADD_OR_SUBTRACT_EXPRESSION:
				sequence_UnaryAddOrSubtractExpressionRule(context, (UnaryAddOrSubtractExpression) semanticObject); 
				return; 
			case BasePackage.VOID_TYPE:
				sequence_VoidTypeRule(context, (VoidType) semanticObject); 
				return; 
			case BasePackage.XOR_EXPRESSION:
				sequence_XorExpressionRule(context, (XorExpression) semanticObject); 
				return; 
			}
		else if (epackage == DdlPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case DdlPackage.ENUM_LITERAL_REFERENCE:
				sequence_EnumLiteralReferenceRule(context, (EnumLiteralReference) semanticObject); 
				return; 
			}
		else if (epackage == GeneratorPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case GeneratorPackage.APPLY_STATEMENT:
				sequence_ApplyStatementRule(context, (ApplyStatement) semanticObject); 
				return; 
			case GeneratorPackage.COUNTER_RANGE:
				sequence_CounterRangeRule(context, (CounterRange) semanticObject); 
				return; 
			case GeneratorPackage.FOR_STATEMENT:
				sequence_ForStatementRule(context, (ForStatement) semanticObject); 
				return; 
			case GeneratorPackage.GENERATOR_MODULE:
				sequence_GeneratorModuleRule(context, (GeneratorModule) semanticObject); 
				return; 
			case GeneratorPackage.LITERAL_RANGE:
				sequence_LiteralRangeRule(context, (LiteralRange) semanticObject); 
				return; 
			case GeneratorPackage.PIPELINE_DEFINITION:
				sequence_PipelineDefinitionRule(context, (PipelineDefinition) semanticObject); 
				return; 
			case GeneratorPackage.PIPELINE_DEFINITION_REFERENCE:
				sequence_PipelineDefinitionReferenceRule(context, (PipelineDefinitionReference) semanticObject); 
				return; 
			case GeneratorPackage.STEP:
				sequence_StepRule(context, (Step) semanticObject); 
				return; 
			case GeneratorPackage.VARIABLE_REFERENCE:
				sequence_VariableReferenceRule(context, (VariableReference) semanticObject); 
				return; 
			}
		else if (epackage == InstancePackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case InstancePackage.DATA_REFERENCE:
				sequence_DataReferenceRule(context, (DataReference) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     StatementRule returns ApplyStatement
	 *     ApplyStatementRule returns ApplyStatement
	 *
	 * Constraint:
	 *     (file=STRING count=LiteralRule pipelines+=LiteralRule pipelines+=LiteralRule*)
	 * </pre>
	 */
	protected void sequence_ApplyStatementRule(ISerializationContext context, ApplyStatement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     RangeRule returns CounterRange
	 *     CounterRangeRule returns CounterRange
	 *
	 * Constraint:
	 *     (start=IntegerLiteralRule end=IntegerLiteralRule)
	 * </pre>
	 */
	protected void sequence_CounterRangeRule(ISerializationContext context, CounterRange semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GeneratorPackage.Literals.COUNTER_RANGE__START) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GeneratorPackage.Literals.COUNTER_RANGE__START));
			if (transientValues.isValueTransient(semanticObject, GeneratorPackage.Literals.COUNTER_RANGE__END) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GeneratorPackage.Literals.COUNTER_RANGE__END));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getCounterRangeRuleAccess().getStartIntegerLiteralRuleParserRuleCall_1_0(), semanticObject.getStart());
		feeder.accept(grammarAccess.getCounterRangeRuleAccess().getEndIntegerLiteralRuleParserRuleCall_3_0(), semanticObject.getEnd());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     StatementRule returns ForStatement
	 *     ForStatementRule returns ForStatement
	 *
	 * Constraint:
	 *     (name=ID range=RangeRule statements+=StatementRule*)
	 * </pre>
	 */
	protected void sequence_ForStatementRule(ISerializationContext context, ForStatement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     GeneratorModuleRule returns GeneratorModule
	 *
	 * Constraint:
	 *     (imports+=ImportRule* name=QualifiedName pipelines+=PipelineDefinitionRule* statements+=StatementRule*)
	 * </pre>
	 */
	protected void sequence_GeneratorModuleRule(ISerializationContext context, GeneratorModule semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     RangeRule returns LiteralRange
	 *     LiteralRangeRule returns LiteralRange
	 *
	 * Constraint:
	 *     (elements+=LiteralRule elements+=LiteralRule*)
	 * </pre>
	 */
	protected void sequence_LiteralRangeRule(ISerializationContext context, LiteralRange semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     LiteralRule returns PipelineDefinitionReference
	 *     PipelineDefinitionReferenceRule returns PipelineDefinitionReference
	 *     ValueRule returns PipelineDefinitionReference
	 *
	 * Constraint:
	 *     pipeline=[PipelineDefinition|QualifiedName]
	 * </pre>
	 */
	protected void sequence_PipelineDefinitionReferenceRule(ISerializationContext context, PipelineDefinitionReference semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GeneratorPackage.Literals.PIPELINE_DEFINITION_REFERENCE__PIPELINE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GeneratorPackage.Literals.PIPELINE_DEFINITION_REFERENCE__PIPELINE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPipelineDefinitionReferenceRuleAccess().getPipelinePipelineDefinitionQualifiedNameParserRuleCall_1_0_1(), semanticObject.eGet(GeneratorPackage.Literals.PIPELINE_DEFINITION_REFERENCE__PIPELINE, false));
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     PipelineDefinitionRule returns PipelineDefinition
	 *
	 * Constraint:
	 *     (name=StringOrId steps+=StepRule*)
	 * </pre>
	 */
	protected void sequence_PipelineDefinitionRule(ISerializationContext context, PipelineDefinition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     StepRule returns Step
	 *
	 * Constraint:
	 *     (instance=InstanceLiteralRule (reads+=DataReferenceRule reads+=DataReferenceRule*)? (writes+=DataReferenceRule writes+=DataReferenceRule*)?)
	 * </pre>
	 */
	protected void sequence_StepRule(ISerializationContext context, Step semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     LiteralRule returns VariableReference
	 *     VariableReferenceRule returns VariableReference
	 *     ValueRule returns VariableReference
	 *
	 * Constraint:
	 *     loop=[ForStatement|ID]
	 * </pre>
	 */
	protected void sequence_VariableReferenceRule(ISerializationContext context, VariableReference semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GeneratorPackage.Literals.VARIABLE_REFERENCE__LOOP) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GeneratorPackage.Literals.VARIABLE_REFERENCE__LOOP));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getVariableReferenceRuleAccess().getLoopForStatementIDTerminalRuleCall_0_1(), semanticObject.eGet(GeneratorPackage.Literals.VARIABLE_REFERENCE__LOOP, false));
		feeder.finish();
	}
	
	
}
