/*
 * generated by Xtext 2.25.0
 * (c) EvoAl Project
 */
package de.evoal.languages.model.eal.dsl.scoping;

import de.evoal.languages.model.instance.dsl.scoping.InstanceLanguageScopeProvider;

public abstract class AbstractEvolutionaryAlgorithmLanguageScopeProvider extends InstanceLanguageScopeProvider {
}
