/*
 * generated by Xtext 2.25.0
 */
package de.evoal.languages.model.generator.dsl.ide;


/**
 * Use this class to register ide components.
 */
public class GeneratorDSLIdeModule extends AbstractGeneratorDSLIdeModule {
}
