/**
 * generated by Xtext 2.25.0
 */
package de.evoal.languages.model.dl.impl;

import de.evoal.languages.model.dl.DlPackage;
import de.evoal.languages.model.dl.VoidType;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Void Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class VoidTypeImpl extends TypeImpl implements VoidType {
	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VoidTypeImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return DlPackage.Literals.VOID_TYPE;
	}

} //VoidTypeImpl
