/*
 * generated by Xtext 2.29.0
 */
package de.evoal.languages.model.generator.dsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import de.evoal.languages.model.generator.GeneratorModule

@ExtendWith(InjectionExtension)
@InjectWith(GeneratorDSLInjectorProvider)
class GeneratorDSLParsingTest {
	@Inject
	ParseHelper<GeneratorModule> parseHelper
	
	@Test
	def void loadModel() {
		/*
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		*/
	}
}
