/*
 * generated by Xtext 2.25.0
 * (c) EvoAl Project
 */
grammar InternalMachineLearningLanguage;

options {
	superClass=AbstractInternalAntlrParser;
	backtrack=true;
}

@lexer::header {
package de.evoal.languages.model.mll.dsl.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package de.evoal.languages.model.mll.dsl.parser.antlr.internal;

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.common.util.Enumerator;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import de.evoal.languages.model.mll.dsl.services.MachineLearningLanguageGrammarAccess;

}

@parser::members {

/*
  This grammar contains a lot of empty actions to work around a bug in ANTLR.
  Otherwise the ANTLR tool will create synpreds that cannot be compiled in some rare cases.
*/

 	private MachineLearningLanguageGrammarAccess grammarAccess;

    public InternalMachineLearningLanguageParser(TokenStream input, MachineLearningLanguageGrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }

    @Override
    protected String getFirstRuleName() {
    	return "MachineLearningConfigurationRule";
   	}

   	@Override
   	protected MachineLearningLanguageGrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}

}

@rulecatch {
    catch (RecognitionException re) {
        recover(input,re);
        appendSkippedTokens();
    }
}

// Entry rule entryRuleMachineLearningConfigurationRule
entryRuleMachineLearningConfigurationRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getMachineLearningConfigurationRuleRule()); }
	iv_ruleMachineLearningConfigurationRule=ruleMachineLearningConfigurationRule
	{ $current=$iv_ruleMachineLearningConfigurationRule.current; }
	EOF;

// Rule MachineLearningConfigurationRule
ruleMachineLearningConfigurationRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					newCompositeNode(grammarAccess.getMachineLearningConfigurationRuleAccess().getUsesUseRuleParserRuleCall_0_0());
				}
				lv_uses_0_0=ruleUseRule
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getMachineLearningConfigurationRuleRule());
					}
					add(
						$current,
						"uses",
						lv_uses_0_0,
						"de.evoal.languages.model.mll.dsl.MachineLearningLanguage.UseRule");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		(
			(
				{
					newCompositeNode(grammarAccess.getMachineLearningConfigurationRuleAccess().getDefinitionsSurrogateDefinitionRuleParserRuleCall_1_0());
				}
				lv_definitions_1_0=ruleSurrogateDefinitionRule
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getMachineLearningConfigurationRuleRule());
					}
					add(
						$current,
						"definitions",
						lv_definitions_1_0,
						"de.evoal.languages.model.mll.dsl.MachineLearningLanguage.SurrogateDefinitionRule");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		(
			(
				{
					newCompositeNode(grammarAccess.getMachineLearningConfigurationRuleAccess().getPredictionsPredictionRuleParserRuleCall_2_0());
				}
				lv_predictions_2_0=rulePredictionRule
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getMachineLearningConfigurationRuleRule());
					}
					add(
						$current,
						"predictions",
						lv_predictions_2_0,
						"de.evoal.languages.model.mll.dsl.MachineLearningLanguage.PredictionRule");
					afterParserOrEnumRuleCall();
				}
			)
		)*
	)
;

// Entry rule entryRuleUseRule
entryRuleUseRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getUseRuleRule()); }
	iv_ruleUseRule=ruleUseRule
	{ $current=$iv_ruleUseRule.current; }
	EOF;

// Rule UseRule
ruleUseRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='use'
		{
			newLeafNode(otherlv_0, grammarAccess.getUseRuleAccess().getUseKeyword_0());
		}
		(
			(
				lv_importURI_1_0=RULE_STRING
				{
					newLeafNode(lv_importURI_1_0, grammarAccess.getUseRuleAccess().getImportURISTRINGTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getUseRuleRule());
					}
					setWithLastConsumed(
						$current,
						"importURI",
						lv_importURI_1_0,
						"de.evoal.languages.model.el.dsl.ExpressionLanguage.STRING");
				}
			)
		)
		otherlv_2=';'
		{
			newLeafNode(otherlv_2, grammarAccess.getUseRuleAccess().getSemicolonKeyword_2());
		}
	)
;

// Entry rule entryRuleSurrogateDefinitionRule
entryRuleSurrogateDefinitionRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getSurrogateDefinitionRuleRule()); }
	iv_ruleSurrogateDefinitionRule=ruleSurrogateDefinitionRule
	{ $current=$iv_ruleSurrogateDefinitionRule.current; }
	EOF;

// Rule SurrogateDefinitionRule
ruleSurrogateDefinitionRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='prediction'
		{
			newLeafNode(otherlv_0, grammarAccess.getSurrogateDefinitionRuleAccess().getPredictionKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_STRING
				{
					newLeafNode(lv_name_1_0, grammarAccess.getSurrogateDefinitionRuleAccess().getNameSTRINGTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getSurrogateDefinitionRuleRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"de.evoal.languages.model.el.dsl.ExpressionLanguage.STRING");
				}
			)
		)
		otherlv_2='maps'
		{
			newLeafNode(otherlv_2, grammarAccess.getSurrogateDefinitionRuleAccess().getMapsKeyword_2());
		}
		(
			(
				{
					/* */
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getSurrogateDefinitionRuleRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getSurrogateDefinitionRuleAccess().getInputsDataDescriptionCrossReference_3_0());
				}
				ruleStringOrId
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_4=','
			{
				newLeafNode(otherlv_4, grammarAccess.getSurrogateDefinitionRuleAccess().getCommaKeyword_4_0());
			}
			(
				(
					{
						/* */
					}
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getSurrogateDefinitionRuleRule());
						}
					}
					{
						newCompositeNode(grammarAccess.getSurrogateDefinitionRuleAccess().getInputsDataDescriptionCrossReference_4_1_0());
					}
					ruleStringOrId
					{
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
		otherlv_6='to'
		{
			newLeafNode(otherlv_6, grammarAccess.getSurrogateDefinitionRuleAccess().getToKeyword_5());
		}
		(
			(
				{
					/* */
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getSurrogateDefinitionRuleRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getSurrogateDefinitionRuleAccess().getOutputsDataDescriptionCrossReference_6_0());
				}
				ruleStringOrId
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_8=','
			{
				newLeafNode(otherlv_8, grammarAccess.getSurrogateDefinitionRuleAccess().getCommaKeyword_7_0());
			}
			(
				(
					{
						/* */
					}
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getSurrogateDefinitionRuleRule());
						}
					}
					{
						newCompositeNode(grammarAccess.getSurrogateDefinitionRuleAccess().getOutputsDataDescriptionCrossReference_7_1_0());
					}
					ruleStringOrId
					{
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
		otherlv_10='using'
		{
			newLeafNode(otherlv_10, grammarAccess.getSurrogateDefinitionRuleAccess().getUsingKeyword_8());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getSurrogateDefinitionRuleAccess().getLayersSurrogateLayerRuleParserRuleCall_9_0());
				}
				lv_layers_11_0=ruleSurrogateLayerRule
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSurrogateDefinitionRuleRule());
					}
					add(
						$current,
						"layers",
						lv_layers_11_0,
						"de.evoal.languages.model.mll.dsl.MachineLearningLanguage.SurrogateLayerRule");
					afterParserOrEnumRuleCall();
				}
			)
		)+
	)
;

// Entry rule entryRuleSurrogateLayerRule
entryRuleSurrogateLayerRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getSurrogateLayerRuleRule()); }
	iv_ruleSurrogateLayerRule=ruleSurrogateLayerRule
	{ $current=$iv_ruleSurrogateLayerRule.current; }
	EOF;

// Rule SurrogateLayerRule
ruleSurrogateLayerRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='layer'
		{
			newLeafNode(otherlv_0, grammarAccess.getSurrogateLayerRuleAccess().getLayerKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_STRING
				{
					newLeafNode(lv_name_1_0, grammarAccess.getSurrogateLayerRuleAccess().getNameSTRINGTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getSurrogateLayerRuleRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"de.evoal.languages.model.el.dsl.ExpressionLanguage.STRING");
				}
			)
		)
		otherlv_2='with'
		{
			newLeafNode(otherlv_2, grammarAccess.getSurrogateLayerRuleAccess().getWithKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getSurrogateLayerRuleAccess().getFunctionsPartialSurrogateFunctionRuleParserRuleCall_3_0());
				}
				lv_functions_3_0=rulePartialSurrogateFunctionRule
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getSurrogateLayerRuleRule());
					}
					add(
						$current,
						"functions",
						lv_functions_3_0,
						"de.evoal.languages.model.mll.dsl.MachineLearningLanguage.PartialSurrogateFunctionRule");
					afterParserOrEnumRuleCall();
				}
			)
		)+
	)
;

// Entry rule entryRulePartialSurrogateFunctionRule
entryRulePartialSurrogateFunctionRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getPartialSurrogateFunctionRuleRule()); }
	iv_rulePartialSurrogateFunctionRule=rulePartialSurrogateFunctionRule
	{ $current=$iv_rulePartialSurrogateFunctionRule.current; }
	EOF;

// Rule PartialSurrogateFunctionRule
rulePartialSurrogateFunctionRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='function'
		{
			newLeafNode(otherlv_0, grammarAccess.getPartialSurrogateFunctionRuleAccess().getFunctionKeyword_0());
		}
		(
			(
				{
					/* */
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPartialSurrogateFunctionRuleRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getPartialSurrogateFunctionRuleAccess().getNameTypeDefinitionCrossReference_1_0());
				}
				ruleStringOrId
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_2='mapping'
		{
			newLeafNode(otherlv_2, grammarAccess.getPartialSurrogateFunctionRuleAccess().getMappingKeyword_2());
		}
		(
			(
				{
					/* */
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPartialSurrogateFunctionRuleRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getPartialSurrogateFunctionRuleAccess().getInputsDataDescriptionCrossReference_3_0());
				}
				ruleStringOrId
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_4=','
			{
				newLeafNode(otherlv_4, grammarAccess.getPartialSurrogateFunctionRuleAccess().getCommaKeyword_4_0());
			}
			(
				(
					{
						/* */
					}
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getPartialSurrogateFunctionRuleRule());
						}
					}
					{
						newCompositeNode(grammarAccess.getPartialSurrogateFunctionRuleAccess().getInputsDataDescriptionCrossReference_4_1_0());
					}
					ruleStringOrId
					{
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
		otherlv_6='to'
		{
			newLeafNode(otherlv_6, grammarAccess.getPartialSurrogateFunctionRuleAccess().getToKeyword_5());
		}
		(
			(
				{
					/* */
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPartialSurrogateFunctionRuleRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getPartialSurrogateFunctionRuleAccess().getOutputsDataDescriptionCrossReference_6_0());
				}
				ruleStringOrId
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_8=','
			{
				newLeafNode(otherlv_8, grammarAccess.getPartialSurrogateFunctionRuleAccess().getCommaKeyword_7_0());
			}
			(
				(
					{
						/* */
					}
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getPartialSurrogateFunctionRuleRule());
						}
					}
					{
						newCompositeNode(grammarAccess.getPartialSurrogateFunctionRuleAccess().getOutputsDataDescriptionCrossReference_7_1_0());
					}
					ruleStringOrId
					{
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
		(
			otherlv_10='with'
			{
				newLeafNode(otherlv_10, grammarAccess.getPartialSurrogateFunctionRuleAccess().getWithKeyword_8_0());
			}
			otherlv_11='parameters'
			{
				newLeafNode(otherlv_11, grammarAccess.getPartialSurrogateFunctionRuleAccess().getParametersKeyword_8_1());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getPartialSurrogateFunctionRuleAccess().getParametersAttributeRuleParserRuleCall_8_2_0());
					}
					lv_parameters_12_0=ruleAttributeRule
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getPartialSurrogateFunctionRuleRule());
						}
						add(
							$current,
							"parameters",
							lv_parameters_12_0,
							"de.evoal.languages.model.instance.dsl.InstanceLanguage.AttributeRule");
						afterParserOrEnumRuleCall();
					}
				)
			)+
		)?
	)
;

// Entry rule entryRulePredictionRule
entryRulePredictionRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getPredictionRuleRule()); }
	iv_rulePredictionRule=rulePredictionRule
	{ $current=$iv_rulePredictionRule.current; }
	EOF;

// Rule PredictionRule
rulePredictionRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='predict'
		{
			newLeafNode(otherlv_0, grammarAccess.getPredictionRuleAccess().getPredictKeyword_0());
		}
		(
			(
				{
					/* */
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPredictionRuleRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getPredictionRuleAccess().getOutputsDataDescriptionCrossReference_1_0());
				}
				ruleStringOrId
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_2=','
			{
				newLeafNode(otherlv_2, grammarAccess.getPredictionRuleAccess().getCommaKeyword_2_0());
			}
			(
				(
					{
						/* */
					}
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getPredictionRuleRule());
						}
					}
					{
						newCompositeNode(grammarAccess.getPredictionRuleAccess().getOutputsDataDescriptionCrossReference_2_1_0());
					}
					ruleStringOrId
					{
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
		otherlv_4='from'
		{
			newLeafNode(otherlv_4, grammarAccess.getPredictionRuleAccess().getFromKeyword_3());
		}
		(
			(
				{
					/* */
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPredictionRuleRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getPredictionRuleAccess().getInputsDataDescriptionCrossReference_4_0());
				}
				ruleStringOrId
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_6=','
			{
				newLeafNode(otherlv_6, grammarAccess.getPredictionRuleAccess().getCommaKeyword_5_0());
			}
			(
				(
					{
						/* */
					}
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getPredictionRuleRule());
						}
					}
					{
						newCompositeNode(grammarAccess.getPredictionRuleAccess().getInputsDataDescriptionCrossReference_5_1_0());
					}
					ruleStringOrId
					{
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
		otherlv_8='using'
		{
			newLeafNode(otherlv_8, grammarAccess.getPredictionRuleAccess().getUsingKeyword_6());
		}
		(
			(
				{
					/* */
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getPredictionRuleRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getPredictionRuleAccess().getDefinitionSurrogateDefinitionCrossReference_7_0());
				}
				ruleStringOrId
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_10='measure'
		{
			newLeafNode(otherlv_10, grammarAccess.getPredictionRuleAccess().getMeasureKeyword_8());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getPredictionRuleAccess().getQualityBlockStatementRuleParserRuleCall_9_0());
				}
				lv_quality_11_0=ruleBlockStatementRule
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPredictionRuleRule());
					}
					set(
						$current,
						"quality",
						lv_quality_11_0,
						"de.evoal.languages.model.mll.dsl.MachineLearningLanguage.BlockStatementRule");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleStatementRule
entryRuleStatementRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getStatementRuleRule()); }
	iv_ruleStatementRule=ruleStatementRule
	{ $current=$iv_ruleStatementRule.current; }
	EOF;

// Rule StatementRule
ruleStatementRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			/* */
		}
		{
			newCompositeNode(grammarAccess.getStatementRuleAccess().getCallStatementRuleParserRuleCall_0());
		}
		this_CallStatementRule_0=ruleCallStatementRule
		{
			$current = $this_CallStatementRule_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			/* */
		}
		{
			newCompositeNode(grammarAccess.getStatementRuleAccess().getBlockStatementRuleParserRuleCall_1());
		}
		this_BlockStatementRule_1=ruleBlockStatementRule
		{
			$current = $this_BlockStatementRule_1.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleBlockStatementRule
entryRuleBlockStatementRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getBlockStatementRuleRule()); }
	iv_ruleBlockStatementRule=ruleBlockStatementRule
	{ $current=$iv_ruleBlockStatementRule.current; }
	EOF;

// Rule BlockStatementRule
ruleBlockStatementRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				/* */
			}
			{
				$current = forceCreateModelElement(
					grammarAccess.getBlockStatementRuleAccess().getBlockStatementAction_0(),
					$current);
			}
		)
		otherlv_1='{'
		{
			newLeafNode(otherlv_1, grammarAccess.getBlockStatementRuleAccess().getLeftCurlyBracketKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getBlockStatementRuleAccess().getStatementsStatementRuleParserRuleCall_2_0());
				}
				lv_statements_2_0=ruleStatementRule
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getBlockStatementRuleRule());
					}
					add(
						$current,
						"statements",
						lv_statements_2_0,
						"de.evoal.languages.model.mll.dsl.MachineLearningLanguage.StatementRule");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		otherlv_3='}'
		{
			newLeafNode(otherlv_3, grammarAccess.getBlockStatementRuleAccess().getRightCurlyBracketKeyword_3());
		}
	)
;

// Entry rule entryRuleCallStatementRule
entryRuleCallStatementRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getCallStatementRuleRule()); }
	iv_ruleCallStatementRule=ruleCallStatementRule
	{ $current=$iv_ruleCallStatementRule.current; }
	EOF;

// Rule CallStatementRule
ruleCallStatementRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					newCompositeNode(grammarAccess.getCallStatementRuleAccess().getCallCallRuleParserRuleCall_0_0());
				}
				lv_call_0_0=ruleCallRule
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getCallStatementRuleRule());
					}
					set(
						$current,
						"call",
						lv_call_0_0,
						"de.evoal.languages.model.el.dsl.ExpressionLanguage.CallRule");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_1=';'
		{
			newLeafNode(otherlv_1, grammarAccess.getCallStatementRuleAccess().getSemicolonKeyword_1());
		}
	)
;

// Entry rule entryRuleFunctionNameRule
entryRuleFunctionNameRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getFunctionNameRuleRule()); }
	iv_ruleFunctionNameRule=ruleFunctionNameRule
	{ $current=$iv_ruleFunctionNameRule.current; }
	EOF;

// Rule FunctionNameRule
ruleFunctionNameRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				/* */
			}
			{
				if ($current==null) {
					$current = createModelElement(grammarAccess.getFunctionNameRuleRule());
				}
			}
			{
				newCompositeNode(grammarAccess.getFunctionNameRuleAccess().getDefinitionFunctionDefinitionCrossReference_0());
			}
			ruleStringOrId
			{
				afterParserOrEnumRuleCall();
			}
		)
	)
;

// Entry rule entryRuleInstanceRule
entryRuleInstanceRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getInstanceRuleRule()); }
	iv_ruleInstanceRule=ruleInstanceRule
	{ $current=$iv_ruleInstanceRule.current; }
	EOF;

// Rule InstanceRule
ruleInstanceRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					/* */
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getInstanceRuleRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getInstanceRuleAccess().getNameTypeDefinitionCrossReference_0_0());
				}
				ruleStringOrId
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_1='{'
			{
				newLeafNode(otherlv_1, grammarAccess.getInstanceRuleAccess().getLeftCurlyBracketKeyword_1_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getInstanceRuleAccess().getAttributesAttributeRuleParserRuleCall_1_1_0());
					}
					lv_attributes_2_0=ruleAttributeRule
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getInstanceRuleRule());
						}
						add(
							$current,
							"attributes",
							lv_attributes_2_0,
							"de.evoal.languages.model.instance.dsl.InstanceLanguage.AttributeRule");
						afterParserOrEnumRuleCall();
					}
				)
			)*
			otherlv_3='}'
			{
				newLeafNode(otherlv_3, grammarAccess.getInstanceRuleAccess().getRightCurlyBracketKeyword_1_2());
			}
		)?
	)
;

// Entry rule entryRuleAttributeRule
entryRuleAttributeRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getAttributeRuleRule()); }
	iv_ruleAttributeRule=ruleAttributeRule
	{ $current=$iv_ruleAttributeRule.current; }
	EOF;

// Rule AttributeRule
ruleAttributeRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					newCompositeNode(grammarAccess.getAttributeRuleAccess().getNameNameOrMiscRuleParserRuleCall_0_0());
				}
				lv_name_0_0=ruleNameOrMiscRule
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAttributeRuleRule());
					}
					set(
						$current,
						"name",
						lv_name_0_0,
						"de.evoal.languages.model.instance.dsl.InstanceLanguage.NameOrMiscRule");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_1=':='
		{
			newLeafNode(otherlv_1, grammarAccess.getAttributeRuleAccess().getColonEqualsSignKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getAttributeRuleAccess().getValueValueRuleParserRuleCall_2_0());
				}
				lv_value_2_0=ruleValueRule
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAttributeRuleRule());
					}
					set(
						$current,
						"value",
						lv_value_2_0,
						"de.evoal.languages.model.instance.dsl.InstanceLanguage.ValueRule");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_3=';'
		{
			newLeafNode(otherlv_3, grammarAccess.getAttributeRuleAccess().getSemicolonKeyword_3());
		}
	)
;

// Entry rule entryRuleNameOrMiscRule
entryRuleNameOrMiscRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getNameOrMiscRuleRule()); }
	iv_ruleNameOrMiscRule=ruleNameOrMiscRule
	{ $current=$iv_ruleNameOrMiscRule.current; }
	EOF;

// Rule NameOrMiscRule
ruleNameOrMiscRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			/* */
		}
		{
			newCompositeNode(grammarAccess.getNameOrMiscRuleAccess().getNameRuleParserRuleCall_0());
		}
		this_NameRule_0=ruleNameRule
		{
			$current = $this_NameRule_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			/* */
		}
		{
			newCompositeNode(grammarAccess.getNameOrMiscRuleAccess().getMiscRuleParserRuleCall_1());
		}
		this_MiscRule_1=ruleMiscRule
		{
			$current = $this_MiscRule_1.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleNameRule
entryRuleNameRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getNameRuleRule()); }
	iv_ruleNameRule=ruleNameRule
	{ $current=$iv_ruleNameRule.current; }
	EOF;

// Rule NameRule
ruleNameRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				/* */
			}
			{
				if ($current==null) {
					$current = createModelElement(grammarAccess.getNameRuleRule());
				}
			}
			{
				newCompositeNode(grammarAccess.getNameRuleAccess().getNameNamedAttributeDefinitionCrossReference_0());
			}
			ruleStringOrId
			{
				afterParserOrEnumRuleCall();
			}
		)
	)
;

// Entry rule entryRuleMiscRule
entryRuleMiscRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getMiscRuleRule()); }
	iv_ruleMiscRule=ruleMiscRule
	{ $current=$iv_ruleMiscRule.current; }
	EOF;

// Rule MiscRule
ruleMiscRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			lv_name_0_0=RULE_STRING
			{
				newLeafNode(lv_name_0_0, grammarAccess.getMiscRuleAccess().getNameSTRINGTerminalRuleCall_0());
			}
			{
				if ($current==null) {
					$current = createModelElement(grammarAccess.getMiscRuleRule());
				}
				setWithLastConsumed(
					$current,
					"name",
					lv_name_0_0,
					"de.evoal.languages.model.el.dsl.ExpressionLanguage.STRING");
			}
		)
	)
;

// Entry rule entryRuleValueRule
entryRuleValueRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getValueRuleRule()); }
	iv_ruleValueRule=ruleValueRule
	{ $current=$iv_ruleValueRule.current; }
	EOF;

// Rule ValueRule
ruleValueRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			/* */
		}
		{
			newCompositeNode(grammarAccess.getValueRuleAccess().getArrayRuleParserRuleCall_0());
		}
		this_ArrayRule_0=ruleArrayRule
		{
			$current = $this_ArrayRule_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			/* */
		}
		{
			newCompositeNode(grammarAccess.getValueRuleAccess().getDataReferenceRuleParserRuleCall_1());
		}
		this_DataReferenceRule_1=ruleDataReferenceRule
		{
			$current = $this_DataReferenceRule_1.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			/* */
		}
		{
			newCompositeNode(grammarAccess.getValueRuleAccess().getInstanceRuleParserRuleCall_2());
		}
		this_InstanceRule_2=ruleInstanceRule
		{
			$current = $this_InstanceRule_2.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			/* */
		}
		{
			newCompositeNode(grammarAccess.getValueRuleAccess().getLiteralValueRuleParserRuleCall_3());
		}
		this_LiteralValueRule_3=ruleLiteralValueRule
		{
			$current = $this_LiteralValueRule_3.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleArrayRule
entryRuleArrayRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getArrayRuleRule()); }
	iv_ruleArrayRule=ruleArrayRule
	{ $current=$iv_ruleArrayRule.current; }
	EOF;

// Rule ArrayRule
ruleArrayRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				/* */
			}
			{
				$current = forceCreateModelElement(
					grammarAccess.getArrayRuleAccess().getArrayAction_0(),
					$current);
			}
		)
		otherlv_1='['
		{
			newLeafNode(otherlv_1, grammarAccess.getArrayRuleAccess().getLeftSquareBracketKeyword_1());
		}
		(
			(
				(
					{
						newCompositeNode(grammarAccess.getArrayRuleAccess().getValuesValueRuleParserRuleCall_2_0_0());
					}
					lv_values_2_0=ruleValueRule
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getArrayRuleRule());
						}
						add(
							$current,
							"values",
							lv_values_2_0,
							"de.evoal.languages.model.instance.dsl.InstanceLanguage.ValueRule");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_3=','
				{
					newLeafNode(otherlv_3, grammarAccess.getArrayRuleAccess().getCommaKeyword_2_1_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getArrayRuleAccess().getValuesValueRuleParserRuleCall_2_1_1_0());
						}
						lv_values_4_0=ruleValueRule
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getArrayRuleRule());
							}
							add(
								$current,
								"values",
								lv_values_4_0,
								"de.evoal.languages.model.instance.dsl.InstanceLanguage.ValueRule");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
		)?
		otherlv_5=']'
		{
			newLeafNode(otherlv_5, grammarAccess.getArrayRuleAccess().getRightSquareBracketKeyword_3());
		}
	)
;

// Entry rule entryRuleLiteralValueRule
entryRuleLiteralValueRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getLiteralValueRuleRule()); }
	iv_ruleLiteralValueRule=ruleLiteralValueRule
	{ $current=$iv_ruleLiteralValueRule.current; }
	EOF;

// Rule LiteralValueRule
ruleLiteralValueRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				newCompositeNode(grammarAccess.getLiteralValueRuleAccess().getLiteralLiteralRuleParserRuleCall_0());
			}
			lv_literal_0_0=ruleLiteralRule
			{
				if ($current==null) {
					$current = createModelElementForParent(grammarAccess.getLiteralValueRuleRule());
				}
				set(
					$current,
					"literal",
					lv_literal_0_0,
					"de.evoal.languages.model.el.dsl.ExpressionLanguage.LiteralRule");
				afterParserOrEnumRuleCall();
			}
		)
	)
;

// Entry rule entryRuleDataReferenceRule
entryRuleDataReferenceRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getDataReferenceRuleRule()); }
	iv_ruleDataReferenceRule=ruleDataReferenceRule
	{ $current=$iv_ruleDataReferenceRule.current; }
	EOF;

// Rule DataReferenceRule
ruleDataReferenceRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				/* */
			}
			{
				$current = forceCreateModelElement(
					grammarAccess.getDataReferenceRuleAccess().getDataReferenceAction_0(),
					$current);
			}
		)
		otherlv_1='data'
		{
			newLeafNode(otherlv_1, grammarAccess.getDataReferenceRuleAccess().getDataKeyword_1());
		}
		(
			(
				{
					/* */
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getDataReferenceRuleRule());
					}
				}
				{
					newCompositeNode(grammarAccess.getDataReferenceRuleAccess().getDefinitionDataDescriptionCrossReference_2_0());
				}
				ruleStringOrId
				{
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleExpressionRule
entryRuleExpressionRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getExpressionRuleRule()); }
	iv_ruleExpressionRule=ruleExpressionRule
	{ $current=$iv_ruleExpressionRule.current; }
	EOF;

// Rule ExpressionRule
ruleExpressionRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	{
		/* */
	}
	{
		newCompositeNode(grammarAccess.getExpressionRuleAccess().getOrExpressionRuleParserRuleCall());
	}
	this_OrExpressionRule_0=ruleOrExpressionRule
	{
		$current = $this_OrExpressionRule_0.current;
		afterParserOrEnumRuleCall();
	}
;

// Entry rule entryRuleOrExpressionRule
entryRuleOrExpressionRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getOrExpressionRuleRule()); }
	iv_ruleOrExpressionRule=ruleOrExpressionRule
	{ $current=$iv_ruleOrExpressionRule.current; }
	EOF;

// Rule OrExpressionRule
ruleOrExpressionRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					newCompositeNode(grammarAccess.getOrExpressionRuleAccess().getSubExpressionsXorExpressionRuleParserRuleCall_0_0());
				}
				lv_subExpressions_0_0=ruleXorExpressionRule
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getOrExpressionRuleRule());
					}
					add(
						$current,
						"subExpressions",
						lv_subExpressions_0_0,
						"de.evoal.languages.model.el.dsl.ExpressionLanguage.XorExpressionRule");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_1='OR'
			{
				newLeafNode(otherlv_1, grammarAccess.getOrExpressionRuleAccess().getORKeyword_1_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getOrExpressionRuleAccess().getSubExpressionsXorExpressionRuleParserRuleCall_1_1_0());
					}
					lv_subExpressions_2_0=ruleXorExpressionRule
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getOrExpressionRuleRule());
						}
						add(
							$current,
							"subExpressions",
							lv_subExpressions_2_0,
							"de.evoal.languages.model.el.dsl.ExpressionLanguage.XorExpressionRule");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
	)
;

// Entry rule entryRuleXorExpressionRule
entryRuleXorExpressionRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getXorExpressionRuleRule()); }
	iv_ruleXorExpressionRule=ruleXorExpressionRule
	{ $current=$iv_ruleXorExpressionRule.current; }
	EOF;

// Rule XorExpressionRule
ruleXorExpressionRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					newCompositeNode(grammarAccess.getXorExpressionRuleAccess().getSubExpressionsAndExpressionRuleParserRuleCall_0_0());
				}
				lv_subExpressions_0_0=ruleAndExpressionRule
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getXorExpressionRuleRule());
					}
					add(
						$current,
						"subExpressions",
						lv_subExpressions_0_0,
						"de.evoal.languages.model.el.dsl.ExpressionLanguage.AndExpressionRule");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_1='XOR'
			{
				newLeafNode(otherlv_1, grammarAccess.getXorExpressionRuleAccess().getXORKeyword_1_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getXorExpressionRuleAccess().getSubExpressionsAndExpressionRuleParserRuleCall_1_1_0());
					}
					lv_subExpressions_2_0=ruleAndExpressionRule
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getXorExpressionRuleRule());
						}
						add(
							$current,
							"subExpressions",
							lv_subExpressions_2_0,
							"de.evoal.languages.model.el.dsl.ExpressionLanguage.AndExpressionRule");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
	)
;

// Entry rule entryRuleAndExpressionRule
entryRuleAndExpressionRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getAndExpressionRuleRule()); }
	iv_ruleAndExpressionRule=ruleAndExpressionRule
	{ $current=$iv_ruleAndExpressionRule.current; }
	EOF;

// Rule AndExpressionRule
ruleAndExpressionRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					newCompositeNode(grammarAccess.getAndExpressionRuleAccess().getSubExpressionsNotExpressionRuleParserRuleCall_0_0());
				}
				lv_subExpressions_0_0=ruleNotExpressionRule
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAndExpressionRuleRule());
					}
					add(
						$current,
						"subExpressions",
						lv_subExpressions_0_0,
						"de.evoal.languages.model.el.dsl.ExpressionLanguage.NotExpressionRule");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_1='AND'
			{
				newLeafNode(otherlv_1, grammarAccess.getAndExpressionRuleAccess().getANDKeyword_1_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getAndExpressionRuleAccess().getSubExpressionsNotExpressionRuleParserRuleCall_1_1_0());
					}
					lv_subExpressions_2_0=ruleNotExpressionRule
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getAndExpressionRuleRule());
						}
						add(
							$current,
							"subExpressions",
							lv_subExpressions_2_0,
							"de.evoal.languages.model.el.dsl.ExpressionLanguage.NotExpressionRule");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
	)
;

// Entry rule entryRuleNotExpressionRule
entryRuleNotExpressionRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getNotExpressionRuleRule()); }
	iv_ruleNotExpressionRule=ruleNotExpressionRule
	{ $current=$iv_ruleNotExpressionRule.current; }
	EOF;

// Rule NotExpressionRule
ruleNotExpressionRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				lv_negated_0_0='!'
				{
					newLeafNode(lv_negated_0_0, grammarAccess.getNotExpressionRuleAccess().getNegatedExclamationMarkKeyword_0_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getNotExpressionRuleRule());
					}
					setWithLastConsumed($current, "negated", lv_negated_0_0 != null, "!");
				}
			)
		)?
		(
			(
				{
					newCompositeNode(grammarAccess.getNotExpressionRuleAccess().getOperandComparisonExpressionRuleParserRuleCall_1_0());
				}
				lv_operand_1_0=ruleComparisonExpressionRule
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getNotExpressionRuleRule());
					}
					set(
						$current,
						"operand",
						lv_operand_1_0,
						"de.evoal.languages.model.el.dsl.ExpressionLanguage.ComparisonExpressionRule");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleComparisonExpressionRule
entryRuleComparisonExpressionRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getComparisonExpressionRuleRule()); }
	iv_ruleComparisonExpressionRule=ruleComparisonExpressionRule
	{ $current=$iv_ruleComparisonExpressionRule.current; }
	EOF;

// Rule ComparisonExpressionRule
ruleComparisonExpressionRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					newCompositeNode(grammarAccess.getComparisonExpressionRuleAccess().getLeftOperandAddOrSubtractExpressionRuleParserRuleCall_0_0());
				}
				lv_leftOperand_0_0=ruleAddOrSubtractExpressionRule
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getComparisonExpressionRuleRule());
					}
					set(
						$current,
						"leftOperand",
						lv_leftOperand_0_0,
						"de.evoal.languages.model.el.dsl.ExpressionLanguage.AddOrSubtractExpressionRule");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				{
					newCompositeNode(grammarAccess.getComparisonExpressionRuleAccess().getComparisonPartialComparisonExpressionRuleParserRuleCall_1_0());
				}
				lv_comparison_1_0=rulePartialComparisonExpressionRule
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getComparisonExpressionRuleRule());
					}
					add(
						$current,
						"comparison",
						lv_comparison_1_0,
						"de.evoal.languages.model.el.dsl.ExpressionLanguage.PartialComparisonExpressionRule");
					afterParserOrEnumRuleCall();
				}
			)
		)*
	)
;

// Entry rule entryRulePartialComparisonExpressionRule
entryRulePartialComparisonExpressionRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getPartialComparisonExpressionRuleRule()); }
	iv_rulePartialComparisonExpressionRule=rulePartialComparisonExpressionRule
	{ $current=$iv_rulePartialComparisonExpressionRule.current; }
	EOF;

// Rule PartialComparisonExpressionRule
rulePartialComparisonExpressionRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					newCompositeNode(grammarAccess.getPartialComparisonExpressionRuleAccess().getOperatorComparisonOperatorRuleEnumRuleCall_0_0());
				}
				lv_operator_0_0=ruleComparisonOperatorRule
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPartialComparisonExpressionRuleRule());
					}
					set(
						$current,
						"operator",
						lv_operator_0_0,
						"de.evoal.languages.model.el.dsl.ExpressionLanguage.ComparisonOperatorRule");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				{
					newCompositeNode(grammarAccess.getPartialComparisonExpressionRuleAccess().getSubExpressionAddOrSubtractExpressionRuleParserRuleCall_1_0());
				}
				lv_subExpression_1_0=ruleAddOrSubtractExpressionRule
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPartialComparisonExpressionRuleRule());
					}
					set(
						$current,
						"subExpression",
						lv_subExpression_1_0,
						"de.evoal.languages.model.el.dsl.ExpressionLanguage.AddOrSubtractExpressionRule");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleAddOrSubtractExpressionRule
entryRuleAddOrSubtractExpressionRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getAddOrSubtractExpressionRuleRule()); }
	iv_ruleAddOrSubtractExpressionRule=ruleAddOrSubtractExpressionRule
	{ $current=$iv_ruleAddOrSubtractExpressionRule.current; }
	EOF;

// Rule AddOrSubtractExpressionRule
ruleAddOrSubtractExpressionRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					newCompositeNode(grammarAccess.getAddOrSubtractExpressionRuleAccess().getLeftOperandMultiplyDivideModuloExpressionRuleParserRuleCall_0_0());
				}
				lv_leftOperand_0_0=ruleMultiplyDivideModuloExpressionRule
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAddOrSubtractExpressionRuleRule());
					}
					set(
						$current,
						"leftOperand",
						lv_leftOperand_0_0,
						"de.evoal.languages.model.el.dsl.ExpressionLanguage.MultiplyDivideModuloExpressionRule");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				(
					{
						newCompositeNode(grammarAccess.getAddOrSubtractExpressionRuleAccess().getOperatorsAddOrSubtractOperatorRuleEnumRuleCall_1_0_0());
					}
					lv_operators_1_0=ruleAddOrSubtractOperatorRule
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getAddOrSubtractExpressionRuleRule());
						}
						add(
							$current,
							"operators",
							lv_operators_1_0,
							"de.evoal.languages.model.el.dsl.ExpressionLanguage.AddOrSubtractOperatorRule");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				(
					{
						newCompositeNode(grammarAccess.getAddOrSubtractExpressionRuleAccess().getOperandsMultiplyDivideModuloExpressionRuleParserRuleCall_1_1_0());
					}
					lv_operands_2_0=ruleMultiplyDivideModuloExpressionRule
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getAddOrSubtractExpressionRuleRule());
						}
						add(
							$current,
							"operands",
							lv_operands_2_0,
							"de.evoal.languages.model.el.dsl.ExpressionLanguage.MultiplyDivideModuloExpressionRule");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
	)
;

// Entry rule entryRuleMultiplyDivideModuloExpressionRule
entryRuleMultiplyDivideModuloExpressionRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getMultiplyDivideModuloExpressionRuleRule()); }
	iv_ruleMultiplyDivideModuloExpressionRule=ruleMultiplyDivideModuloExpressionRule
	{ $current=$iv_ruleMultiplyDivideModuloExpressionRule.current; }
	EOF;

// Rule MultiplyDivideModuloExpressionRule
ruleMultiplyDivideModuloExpressionRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					newCompositeNode(grammarAccess.getMultiplyDivideModuloExpressionRuleAccess().getLeftOperandPowerOfExpressionRuleParserRuleCall_0_0());
				}
				lv_leftOperand_0_0=rulePowerOfExpressionRule
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getMultiplyDivideModuloExpressionRuleRule());
					}
					set(
						$current,
						"leftOperand",
						lv_leftOperand_0_0,
						"de.evoal.languages.model.el.dsl.ExpressionLanguage.PowerOfExpressionRule");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				(
					{
						newCompositeNode(grammarAccess.getMultiplyDivideModuloExpressionRuleAccess().getOperatorsMultiplyDivideModuloOperatorRuleEnumRuleCall_1_0_0());
					}
					lv_operators_1_0=ruleMultiplyDivideModuloOperatorRule
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getMultiplyDivideModuloExpressionRuleRule());
						}
						add(
							$current,
							"operators",
							lv_operators_1_0,
							"de.evoal.languages.model.el.dsl.ExpressionLanguage.MultiplyDivideModuloOperatorRule");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				(
					{
						newCompositeNode(grammarAccess.getMultiplyDivideModuloExpressionRuleAccess().getOperandsPowerOfExpressionRuleParserRuleCall_1_1_0());
					}
					lv_operands_2_0=rulePowerOfExpressionRule
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getMultiplyDivideModuloExpressionRuleRule());
						}
						add(
							$current,
							"operands",
							lv_operands_2_0,
							"de.evoal.languages.model.el.dsl.ExpressionLanguage.PowerOfExpressionRule");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
	)
;

// Entry rule entryRulePowerOfExpressionRule
entryRulePowerOfExpressionRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getPowerOfExpressionRuleRule()); }
	iv_rulePowerOfExpressionRule=rulePowerOfExpressionRule
	{ $current=$iv_rulePowerOfExpressionRule.current; }
	EOF;

// Rule PowerOfExpressionRule
rulePowerOfExpressionRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					newCompositeNode(grammarAccess.getPowerOfExpressionRuleAccess().getLeftOperandUnaryAddOrSubtractExpressionRuleParserRuleCall_0_0());
				}
				lv_leftOperand_0_0=ruleUnaryAddOrSubtractExpressionRule
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPowerOfExpressionRuleRule());
					}
					set(
						$current,
						"leftOperand",
						lv_leftOperand_0_0,
						"de.evoal.languages.model.el.dsl.ExpressionLanguage.UnaryAddOrSubtractExpressionRule");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_1='^'
			{
				newLeafNode(otherlv_1, grammarAccess.getPowerOfExpressionRuleAccess().getCircumflexAccentKeyword_1_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getPowerOfExpressionRuleAccess().getRightOperandPowerOfExpressionRuleParserRuleCall_1_1_0());
					}
					lv_rightOperand_2_0=rulePowerOfExpressionRule
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getPowerOfExpressionRuleRule());
						}
						set(
							$current,
							"rightOperand",
							lv_rightOperand_2_0,
							"de.evoal.languages.model.el.dsl.ExpressionLanguage.PowerOfExpressionRule");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
	)
;

// Entry rule entryRuleUnaryAddOrSubtractExpressionRule
entryRuleUnaryAddOrSubtractExpressionRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getUnaryAddOrSubtractExpressionRuleRule()); }
	iv_ruleUnaryAddOrSubtractExpressionRule=ruleUnaryAddOrSubtractExpressionRule
	{ $current=$iv_ruleUnaryAddOrSubtractExpressionRule.current; }
	EOF;

// Rule UnaryAddOrSubtractExpressionRule
ruleUnaryAddOrSubtractExpressionRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					newCompositeNode(grammarAccess.getUnaryAddOrSubtractExpressionRuleAccess().getOperatorsAddOrSubtractOperatorRuleEnumRuleCall_0_0());
				}
				lv_operators_0_0=ruleAddOrSubtractOperatorRule
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getUnaryAddOrSubtractExpressionRuleRule());
					}
					add(
						$current,
						"operators",
						lv_operators_0_0,
						"de.evoal.languages.model.el.dsl.ExpressionLanguage.AddOrSubtractOperatorRule");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		(
			(
				{
					newCompositeNode(grammarAccess.getUnaryAddOrSubtractExpressionRuleAccess().getSubExpressionLiteralOrReferenceRuleParserRuleCall_1_0());
				}
				lv_subExpression_1_0=ruleLiteralOrReferenceRule
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getUnaryAddOrSubtractExpressionRuleRule());
					}
					set(
						$current,
						"subExpression",
						lv_subExpression_1_0,
						"de.evoal.languages.model.el.dsl.ExpressionLanguage.LiteralOrReferenceRule");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleLiteralOrReferenceRule
entryRuleLiteralOrReferenceRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getLiteralOrReferenceRuleRule()); }
	iv_ruleLiteralOrReferenceRule=ruleLiteralOrReferenceRule
	{ $current=$iv_ruleLiteralOrReferenceRule.current; }
	EOF;

// Rule LiteralOrReferenceRule
ruleLiteralOrReferenceRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			/* */
		}
		{
			newCompositeNode(grammarAccess.getLiteralOrReferenceRuleAccess().getCallRuleParserRuleCall_0());
		}
		this_CallRule_0=ruleCallRule
		{
			$current = $this_CallRule_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			/* */
		}
		{
			newCompositeNode(grammarAccess.getLiteralOrReferenceRuleAccess().getLiteralRuleParserRuleCall_1());
		}
		this_LiteralRule_1=ruleLiteralRule
		{
			$current = $this_LiteralRule_1.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			/* */
		}
		{
			newCompositeNode(grammarAccess.getLiteralOrReferenceRuleAccess().getParanthesesRuleParserRuleCall_2());
		}
		this_ParanthesesRule_2=ruleParanthesesRule
		{
			$current = $this_ParanthesesRule_2.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			/* */
		}
		{
			newCompositeNode(grammarAccess.getLiteralOrReferenceRuleAccess().getValueReferenceRuleParserRuleCall_3());
		}
		this_ValueReferenceRule_3=ruleValueReferenceRule
		{
			$current = $this_ValueReferenceRule_3.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleParanthesesRule
entryRuleParanthesesRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getParanthesesRuleRule()); }
	iv_ruleParanthesesRule=ruleParanthesesRule
	{ $current=$iv_ruleParanthesesRule.current; }
	EOF;

// Rule ParanthesesRule
ruleParanthesesRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='('
		{
			newLeafNode(otherlv_0, grammarAccess.getParanthesesRuleAccess().getLeftParenthesisKeyword_0());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getParanthesesRuleAccess().getSubExpressionExpressionRuleParserRuleCall_1_0());
				}
				lv_subExpression_1_0=ruleExpressionRule
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getParanthesesRuleRule());
					}
					set(
						$current,
						"subExpression",
						lv_subExpression_1_0,
						"de.evoal.languages.model.el.dsl.ExpressionLanguage.ExpressionRule");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_2=')'
		{
			newLeafNode(otherlv_2, grammarAccess.getParanthesesRuleAccess().getRightParenthesisKeyword_2());
		}
	)
;

// Entry rule entryRuleCallRule
entryRuleCallRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getCallRuleRule()); }
	iv_ruleCallRule=ruleCallRule
	{ $current=$iv_ruleCallRule.current; }
	EOF;

// Rule CallRule
ruleCallRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					newCompositeNode(grammarAccess.getCallRuleAccess().getFunctionFunctionNameRuleParserRuleCall_0_0());
				}
				lv_function_0_0=ruleFunctionNameRule
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getCallRuleRule());
					}
					set(
						$current,
						"function",
						lv_function_0_0,
						"de.evoal.languages.model.mll.dsl.MachineLearningLanguage.FunctionNameRule");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_1='('
		{
			newLeafNode(otherlv_1, grammarAccess.getCallRuleAccess().getLeftParenthesisKeyword_1());
		}
		(
			(
				(
					{
						newCompositeNode(grammarAccess.getCallRuleAccess().getParametersExpressionRuleParserRuleCall_2_0_0());
					}
					lv_parameters_2_0=ruleExpressionRule
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getCallRuleRule());
						}
						add(
							$current,
							"parameters",
							lv_parameters_2_0,
							"de.evoal.languages.model.el.dsl.ExpressionLanguage.ExpressionRule");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_3=','
				{
					newLeafNode(otherlv_3, grammarAccess.getCallRuleAccess().getCommaKeyword_2_1_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getCallRuleAccess().getParametersExpressionRuleParserRuleCall_2_1_1_0());
						}
						lv_parameters_4_0=ruleExpressionRule
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getCallRuleRule());
							}
							add(
								$current,
								"parameters",
								lv_parameters_4_0,
								"de.evoal.languages.model.el.dsl.ExpressionLanguage.ExpressionRule");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
		)?
		otherlv_5=')'
		{
			newLeafNode(otherlv_5, grammarAccess.getCallRuleAccess().getRightParenthesisKeyword_3());
		}
	)
;

// Entry rule entryRuleValueReferenceRule
entryRuleValueReferenceRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getValueReferenceRuleRule()); }
	iv_ruleValueReferenceRule=ruleValueReferenceRule
	{ $current=$iv_ruleValueReferenceRule.current; }
	EOF;

// Rule ValueReferenceRule
ruleValueReferenceRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				/* */
			}
			{
				$current = forceCreateModelElement(
					grammarAccess.getValueReferenceRuleAccess().getValueReferenceAction_0(),
					$current);
			}
		)
		otherlv_1='value'
		{
			newLeafNode(otherlv_1, grammarAccess.getValueReferenceRuleAccess().getValueKeyword_1());
		}
	)
;

// Entry rule entryRuleLiteralRule
entryRuleLiteralRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getLiteralRuleRule()); }
	iv_ruleLiteralRule=ruleLiteralRule
	{ $current=$iv_ruleLiteralRule.current; }
	EOF;

// Rule LiteralRule
ruleLiteralRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			/* */
		}
		{
			newCompositeNode(grammarAccess.getLiteralRuleAccess().getNumberLiteralRuleParserRuleCall_0());
		}
		this_NumberLiteralRule_0=ruleNumberLiteralRule
		{
			$current = $this_NumberLiteralRule_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			/* */
		}
		{
			newCompositeNode(grammarAccess.getLiteralRuleAccess().getStringLiteralRuleParserRuleCall_1());
		}
		this_StringLiteralRule_1=ruleStringLiteralRule
		{
			$current = $this_StringLiteralRule_1.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			/* */
		}
		{
			newCompositeNode(grammarAccess.getLiteralRuleAccess().getBooleanLiteralRuleParserRuleCall_2());
		}
		this_BooleanLiteralRule_2=ruleBooleanLiteralRule
		{
			$current = $this_BooleanLiteralRule_2.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleNumberLiteralRule
entryRuleNumberLiteralRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getNumberLiteralRuleRule()); }
	iv_ruleNumberLiteralRule=ruleNumberLiteralRule
	{ $current=$iv_ruleNumberLiteralRule.current; }
	EOF;

// Rule NumberLiteralRule
ruleNumberLiteralRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			/* */
		}
		{
			newCompositeNode(grammarAccess.getNumberLiteralRuleAccess().getDoubleLiteralRuleParserRuleCall_0());
		}
		this_DoubleLiteralRule_0=ruleDoubleLiteralRule
		{
			$current = $this_DoubleLiteralRule_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			/* */
		}
		{
			newCompositeNode(grammarAccess.getNumberLiteralRuleAccess().getIntegerLiteralRuleParserRuleCall_1());
		}
		this_IntegerLiteralRule_1=ruleIntegerLiteralRule
		{
			$current = $this_IntegerLiteralRule_1.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleDoubleLiteralRule
entryRuleDoubleLiteralRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getDoubleLiteralRuleRule()); }
	iv_ruleDoubleLiteralRule=ruleDoubleLiteralRule
	{ $current=$iv_ruleDoubleLiteralRule.current; }
	EOF;

// Rule DoubleLiteralRule
ruleDoubleLiteralRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				newCompositeNode(grammarAccess.getDoubleLiteralRuleAccess().getValueDOUBLEParserRuleCall_0());
			}
			lv_value_0_0=ruleDOUBLE
			{
				if ($current==null) {
					$current = createModelElementForParent(grammarAccess.getDoubleLiteralRuleRule());
				}
				set(
					$current,
					"value",
					lv_value_0_0,
					"de.evoal.languages.model.el.dsl.ExpressionLanguage.DOUBLE");
				afterParserOrEnumRuleCall();
			}
		)
	)
;

// Entry rule entryRuleIntegerLiteralRule
entryRuleIntegerLiteralRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getIntegerLiteralRuleRule()); }
	iv_ruleIntegerLiteralRule=ruleIntegerLiteralRule
	{ $current=$iv_ruleIntegerLiteralRule.current; }
	EOF;

// Rule IntegerLiteralRule
ruleIntegerLiteralRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			lv_value_0_0=RULE_INT
			{
				newLeafNode(lv_value_0_0, grammarAccess.getIntegerLiteralRuleAccess().getValueINTTerminalRuleCall_0());
			}
			{
				if ($current==null) {
					$current = createModelElement(grammarAccess.getIntegerLiteralRuleRule());
				}
				setWithLastConsumed(
					$current,
					"value",
					lv_value_0_0,
					"org.eclipse.xtext.common.Terminals.INT");
			}
		)
	)
;

// Entry rule entryRuleStringLiteralRule
entryRuleStringLiteralRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getStringLiteralRuleRule()); }
	iv_ruleStringLiteralRule=ruleStringLiteralRule
	{ $current=$iv_ruleStringLiteralRule.current; }
	EOF;

// Rule StringLiteralRule
ruleStringLiteralRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			lv_value_0_0=RULE_STRING
			{
				newLeafNode(lv_value_0_0, grammarAccess.getStringLiteralRuleAccess().getValueSTRINGTerminalRuleCall_0());
			}
			{
				if ($current==null) {
					$current = createModelElement(grammarAccess.getStringLiteralRuleRule());
				}
				setWithLastConsumed(
					$current,
					"value",
					lv_value_0_0,
					"de.evoal.languages.model.el.dsl.ExpressionLanguage.STRING");
			}
		)
	)
;

// Entry rule entryRuleBooleanLiteralRule
entryRuleBooleanLiteralRule returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getBooleanLiteralRuleRule()); }
	iv_ruleBooleanLiteralRule=ruleBooleanLiteralRule
	{ $current=$iv_ruleBooleanLiteralRule.current; }
	EOF;

// Rule BooleanLiteralRule
ruleBooleanLiteralRule returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				/* */
			}
			{
				$current = forceCreateModelElement(
					grammarAccess.getBooleanLiteralRuleAccess().getBooleanLiteralAction_0(),
					$current);
			}
		)
		(
			(
				(
					lv_value_1_0='true'
					{
						newLeafNode(lv_value_1_0, grammarAccess.getBooleanLiteralRuleAccess().getValueTrueKeyword_1_0_0());
					}
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getBooleanLiteralRuleRule());
						}
						setWithLastConsumed($current, "value", lv_value_1_0 != null, "true");
					}
				)
			)
			    |
			otherlv_2='false'
			{
				newLeafNode(otherlv_2, grammarAccess.getBooleanLiteralRuleAccess().getFalseKeyword_1_1());
			}
		)
	)
;

// Entry rule entryRuleStringOrId
entryRuleStringOrId returns [String current=null]:
	{ newCompositeNode(grammarAccess.getStringOrIdRule()); }
	iv_ruleStringOrId=ruleStringOrId
	{ $current=$iv_ruleStringOrId.current.getText(); }
	EOF;

// Rule StringOrId
ruleStringOrId returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		this_QUOTED_ID_0=RULE_QUOTED_ID
		{
			$current.merge(this_QUOTED_ID_0);
		}
		{
			newLeafNode(this_QUOTED_ID_0, grammarAccess.getStringOrIdAccess().getQUOTED_IDTerminalRuleCall_0());
		}
		    |
		this_ID_1=RULE_ID
		{
			$current.merge(this_ID_1);
		}
		{
			newLeafNode(this_ID_1, grammarAccess.getStringOrIdAccess().getIDTerminalRuleCall_1());
		}
	)
;

// Entry rule entryRuleDOUBLE
entryRuleDOUBLE returns [String current=null]:
	{ newCompositeNode(grammarAccess.getDOUBLERule()); }
	iv_ruleDOUBLE=ruleDOUBLE
	{ $current=$iv_ruleDOUBLE.current.getText(); }
	EOF;

// Rule DOUBLE
ruleDOUBLE returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		this_INT_0=RULE_INT
		{
			$current.merge(this_INT_0);
		}
		{
			newLeafNode(this_INT_0, grammarAccess.getDOUBLEAccess().getINTTerminalRuleCall_0());
		}
		kw='.'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getDOUBLEAccess().getFullStopKeyword_1());
		}
		this_INT_2=RULE_INT
		{
			$current.merge(this_INT_2);
		}
		{
			newLeafNode(this_INT_2, grammarAccess.getDOUBLEAccess().getINTTerminalRuleCall_2());
		}
	)
;

// Rule ComparisonOperatorRule
ruleComparisonOperatorRule returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='>='
			{
				$current = grammarAccess.getComparisonOperatorRuleAccess().getGreaterThanEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getComparisonOperatorRuleAccess().getGreaterThanEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='>'
			{
				$current = grammarAccess.getComparisonOperatorRuleAccess().getGreaterEqualEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getComparisonOperatorRuleAccess().getGreaterEqualEnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='='
			{
				$current = grammarAccess.getComparisonOperatorRuleAccess().getEqualEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getComparisonOperatorRuleAccess().getEqualEnumLiteralDeclaration_2());
			}
		)
		    |
		(
			enumLiteral_3='!='
			{
				$current = grammarAccess.getComparisonOperatorRuleAccess().getUnequalEnumLiteralDeclaration_3().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_3, grammarAccess.getComparisonOperatorRuleAccess().getUnequalEnumLiteralDeclaration_3());
			}
		)
		    |
		(
			enumLiteral_4='<'
			{
				$current = grammarAccess.getComparisonOperatorRuleAccess().getLessEqualEnumLiteralDeclaration_4().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_4, grammarAccess.getComparisonOperatorRuleAccess().getLessEqualEnumLiteralDeclaration_4());
			}
		)
		    |
		(
			enumLiteral_5='<='
			{
				$current = grammarAccess.getComparisonOperatorRuleAccess().getLessThanEnumLiteralDeclaration_5().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_5, grammarAccess.getComparisonOperatorRuleAccess().getLessThanEnumLiteralDeclaration_5());
			}
		)
	)
;

// Rule AddOrSubtractOperatorRule
ruleAddOrSubtractOperatorRule returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='+'
			{
				$current = grammarAccess.getAddOrSubtractOperatorRuleAccess().getAddEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getAddOrSubtractOperatorRuleAccess().getAddEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='-'
			{
				$current = grammarAccess.getAddOrSubtractOperatorRuleAccess().getSubtractEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getAddOrSubtractOperatorRuleAccess().getSubtractEnumLiteralDeclaration_1());
			}
		)
	)
;

// Rule MultiplyDivideModuloOperatorRule
ruleMultiplyDivideModuloOperatorRule returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='*'
			{
				$current = grammarAccess.getMultiplyDivideModuloOperatorRuleAccess().getMultiplyEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getMultiplyDivideModuloOperatorRuleAccess().getMultiplyEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='/'
			{
				$current = grammarAccess.getMultiplyDivideModuloOperatorRuleAccess().getDivideEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getMultiplyDivideModuloOperatorRuleAccess().getDivideEnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='%'
			{
				$current = grammarAccess.getMultiplyDivideModuloOperatorRuleAccess().getModuloEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getMultiplyDivideModuloOperatorRuleAccess().getModuloEnumLiteralDeclaration_2());
			}
		)
	)
;

RULE_STRING : '"' ('\\' .|~(('\\'|'"')))* '"';

RULE_QUOTED_ID : '\'' ('\\' .|~(('\\'|'\'')))* '\'';

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
