<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="generator" nsURI="https://www.evoal.de/languages/generator/1.0.0"
    nsPrefix="generator">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="dl" value="platform:/resource/de.evoal.languages.model.dl/model/model.ecore#/"/>
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
    <details key="ins" value="platform:/resource/de.evoal.languages.model.instance/model/model.ecore#/"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Configuration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="uses" upperBound="-1" eType="#//Use"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generators" upperBound="-1"
        eType="#//GeneratorDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functions" upperBound="-1"
        eType="#//ParametrizedFunctionDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Use">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParametrizedFunctionDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" eType="ecore:EClass ../../de.evoal.languages.model.instance/model/model.ecore#//Instance"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratorDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" eType="ecore:EClass ../../de.evoal.languages.model.instance/model/model.ecore#//Instance"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ForStatement" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="range" eType="#//Range"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Range"/>
  <eClassifiers xsi:type="ecore:EClass" name="CounterRange" eSuperTypes="#//Range">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Functions" eSuperTypes="#//Range">
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionReferences" eType="#//FunctionReferences"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionReferences">
    <eStructuralFeatures xsi:type="ecore:EReference" name="functions" upperBound="-1"
        eType="#//FunctionDefReference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Generators" eSuperTypes="#//Range">
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatorReferences" eType="#//GeneratorReferences"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratorReferences">
    <eStructuralFeatures xsi:type="ecore:EReference" name="generators" unique="false"
        upperBound="-1" eType="#//GeneratorDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplyStatement" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="file" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" eType="#//FunctionReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generator" eType="#//GeneratorReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratorReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratorDefinitionReference" eSuperTypes="#//GeneratorReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" eType="#//GeneratorDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionDefReference" eSuperTypes="#//FunctionReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="LoopVariable" eSuperTypes="#//GeneratorReference #//FunctionReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" eType="#//ForStatement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionDefinitionReference" eSuperTypes="#//FunctionDefReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" eType="ecore:EClass ../../de.evoal.languages.model.dl/model/model.ecore#//TypeDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParametrizedFunctionDefinitionReference"
      eSuperTypes="#//FunctionDefReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" eType="#//ParametrizedFunctionDefinition"/>
  </eClassifiers>
</ecore:EPackage>
