import "definitions" from de.evoal.optimisation.core;

module de.evoal.optimisation.hc.optimisation {

    /**
    * the hill climbing algorithm starts at an initial point
    * and searches for neighbours (according to neighbour-choosing-strategy)
    * with better objective values. It terminates when no improvement is found
    * or when the number-of-iterations is reached.
    */
	type 'hill-climbing-algorithm' extends 'algorithm' {
    	'number-of-iterations' : int;
    	'neighbour-choosing-strategy' : instance 'choosing-strategy';
	}

    /**
    * Neighbour choosing strategy for hill-climbing algorithm
    */
	abstract type 'choosing-strategy' {
	}

    /**
    * This strategy tries moving the given step size
    * in all possible directions until improvement is found
    */
	type 'manual-strategy' extends 'choosing-strategy' {
	    /**
	    * specify a step size for each variable of the
	    * search space.
	    */
    	'step-size' : array instance variable;
	}
}
