grammar de.evoal.languages.model.eal.dsl.EvolutionaryAlgorithmLanguage with de.evoal.languages.model.instance.dsl.InstanceLanguage

import "https://www.evoal.de/languages/eal/1.0.0" 

import "https://www.evoal.de/languages/dl/1.0.0" as dl
import "https://www.evoal.de/languages/ddl/1.0.0" as ddl
import "https://www.evoal.de/languages/instance/1.0.0" as instance
import "https://www.evoal.de/languages/el/1.0.0" as el

EAModelRule returns EAModel:
	(uses += UseRule)*
	
	instance = InstanceRule
	
	(constraints = ConstraintRule)?
;

UseRule returns Use:
	'use' importURI = STRING ';'
;

ConstraintRule returns Constraint:
	{Constraint}
	"constraints" "{"
		(statements += ConstraintStatementRule)*
	"}";


ConstraintStatementRule returns ConstraintStatement:
	constraintExpression = CallRule ';'
;

@Override
FunctionNameRule returns FunctionName:
	definition = [dl::FunctionDefinition]
;
