<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>de.evoal</groupId>
		<artifactId>core.plugin</artifactId>
		<version>${revision}</version>
	</parent>

	<artifactId>optimisation.ea</artifactId>
	<name>EvoAl - Plugins - Optimisation - EA</name>

	<dependencies>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>optimisation.api</artifactId>
			<version>${project.version}</version>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>org.decimal4j</groupId>
			<artifactId>decimal4j</artifactId>
			<version>1.0.3</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>io.jenetics</groupId>
			<artifactId>jenetics</artifactId>
			<version>${jenetics.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>io.jenetics</groupId>
			<artifactId>jenetics.ext</artifactId>
			<version>${jenetics.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>io.jenetics</groupId>
			<artifactId>jenetics.prog</artifactId>
			<version>${jenetics.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
		</dependency>

		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>core.junit</artifactId>
			<version>${project.version}</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.10.1</version>
				<configuration>
					<annotationProcessorPaths>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>${lombok.version}</version>
						</path>
					</annotationProcessorPaths>
					<compilerArgs>
						<arg>--add-exports</arg>
						<arg>io.jenetics.base/io.jenetics.internal.math=de.evoal.optimisation.ea</arg>
						<arg>--add-exports</arg>
						<arg>io.jenetics.base/io.jenetics.internal.util=de.evoal.optimisation.ea</arg>
						<arg>--add-exports</arg>
						<arg>io.jenetics.base/io.jenetics.internal.collection=de.evoal.optimisation.ea</arg>
					</compilerArgs>
					<forceJavacCompilerUse>true</forceJavacCompilerUse>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
