/*
 * generated by Xtext 2.25.0
 */
package de.evoal.languages.model.dl.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;

import de.evoal.languages.model.dl.dsl.ui.hover.DefinitionLanguageEObjectHoverProvider;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class DefinitionLanguageUiModule extends AbstractDefinitionLanguageUiModule {

	public DefinitionLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	
    public Class<? extends IEObjectHoverProvider> bindIEObjectHoverProvider() {
        return DefinitionLanguageEObjectHoverProvider.class;
    }
}
