import "definitions" from de.evoal.surrogate.ml;

/**
 * Simple surrogate functions.
 */
module de.evoal.surrogate.simple.ml {

	/**
	 * An exemplary identity function.
	 */
	type identity extends surrogate {
	}

	/**
	 * A surrogate model that is based on a linear regression.
	 */
	type 'linear-regression' extends surrogate {
	}
	
	/**
	 * A surrogate model that is based on a simple quadratic regression.
	 */
	type 'simple-quadratic-regression' extends surrogate {
	}
}