/*
 * generated by Xtext 2.29.0
 * (c) EvoAl Project
 */
package de.evoal.languages.model.mll.dsl.validation;

import de.evoal.languages.model.instance.dsl.validation.InstanceLanguageValidator;
import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public abstract class AbstractMachineLearningLanguageValidator extends InstanceLanguageValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>(super.getEPackages());
		result.add(EPackage.Registry.INSTANCE.getEPackage("https://www.evoal.de/languages/mll/1.0.0"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("https://www.evoal.de/languages/base/1.0.0"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("https://www.evoal.de/languages/instance/1.0.0"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("https://www.evoal.de/languages/ddl/1.0.0"));
		return result;
	}
}
