# Copyright Text	(c) EvoAl project

pluginName = EvoAl's Data Description Language Edit Support
providerName = EvoAl Project

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_State_type = State
_UI_Iteration_type = Iteration
_UI_Excecution_type = Excecution
_UI_Individual_type = Individual
_UI_Relationship_type = Relationship
_UI_Identity_type = Identity
_UI_Mutation_type = Mutation
_UI_Recombination_type = Recombination
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_Iteration_number_feature = Number
_UI_Iteration_individuals_feature = Individuals
_UI_Excecution_states_feature = States
_UI_Excecution_outputSpace_feature = Output Space
_UI_Excecution_inputSpace_feature = Input Space
_UI_Individual_id_feature = Id
_UI_Individual_input_feature = Input
_UI_Individual_output_feature = Output
_UI_Individual_relationships_feature = Relationships
_UI_Relationship_target_feature = Target
_UI_Recombination_other_feature = Other
_UI_Unknown_feature = Unspecified

