<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ol" nsURI="https://www.evoal.de/languages/ol/1.0.0" nsPrefix="ol">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ddl" value="platform:/resource/de.evoal.languages.model.ddl/model/model.ecore#/"/>
    <details key="el" value="platform:/resource/de.evoal.languages.model.base/model/model.ecore#/"/>
    <details key="instance" value="platform:/resource/de.evoal.languages.model.instance/model/model.ecore#/"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="OptimisationModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="ecore:EClass ../../de.evoal.languages.model.base/model/model.ecore#//Import"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="problem" eType="#//Problem"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="algorithm" eType="#//AlgorithmInstance"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Problem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="problem" lowerBound="1"
        eType="ecore:EClass ../../de.evoal.languages.model.base/model/model.ecore#//Instance"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="documentation" eType="ecore:EClass ../../de.evoal.languages.model.base/model/model.ecore#//Array"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlgorithmInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="problem" lowerBound="1"
        eType="#//Problem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="algorithm" lowerBound="1"
        eType="ecore:EClass ../../de.evoal.languages.model.base/model/model.ecore#//Instance"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="documentation" eType="ecore:EClass ../../de.evoal.languages.model.base/model/model.ecore#//Array"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
