import "definitions" from 'de.evoal.pipeline.base';
import "definitions" from 'de.evoal.surrogate.ml';

/**
 * Generator extensions based on surrogate models.
 */
module de.evoal.surrogate.pipeline {

    /**
     * Uses a pre-trained surrogate model as function.
     */
	type 'trained-model' extends Processor {
	    /**
	     * Name of the pson file storing surrogate model.
	     **/
	    'model-file' : string;
	}

	/**
	 * Component for loading training data and using it for the pipeline. 
	 */	
	type 'training-data-loader' {
		/**
		 * List of files or directories to use
		 */
		'training-files' : optional array string;
		
		/**
		 * The input features of the model.
		 */
         'input-features' : optional array data;
         
         /**
          * The output features of the model.
          */
         'output-features' : optional array data;
	}

    /**
     * Pipeline step for learning a model.
     */
	type 'model-learner' extends Processor {
        /**
         * The model (and the hyper parameters) to learn.
         */
         'model' : optional instance surrogate;
         
	    /**
	     * Location for storing the model.
	     */
	    'model-file' : optional string;

		/**
		 * The input features of the model.
		 */
         'input-features' : optional array data;
         
         /**
          * The output features of the model.
          */
         'output-features' : optional array data;
	}

	type 'model-prediction' extends Processor {}
	
	def void 'gof-calculator'();
		
	def void 'store-model'();

}