/*
 * generated by Xtext 2.29.0
 * (c) Evoal Project
 */
package de.evoal.languages.model.base.dsl.serializer;

import com.google.inject.Inject;
import de.evoal.languages.model.base.AddOrSubtractExpression;
import de.evoal.languages.model.base.AndExpression;
import de.evoal.languages.model.base.Array;
import de.evoal.languages.model.base.ArrayType;
import de.evoal.languages.model.base.Attribute;
import de.evoal.languages.model.base.AttributeDefinition;
import de.evoal.languages.model.base.BasePackage;
import de.evoal.languages.model.base.BooleanLiteral;
import de.evoal.languages.model.base.BooleanType;
import de.evoal.languages.model.base.Call;
import de.evoal.languages.model.base.ComparisonExpression;
import de.evoal.languages.model.base.ConstantDefinition;
import de.evoal.languages.model.base.ConstantReference;
import de.evoal.languages.model.base.DataOrInstanceType;
import de.evoal.languages.model.base.DataType;
import de.evoal.languages.model.base.DefinedFunctionName;
import de.evoal.languages.model.base.ExpressionType;
import de.evoal.languages.model.base.FunctionDefinition;
import de.evoal.languages.model.base.Import;
import de.evoal.languages.model.base.Instance;
import de.evoal.languages.model.base.InstanceType;
import de.evoal.languages.model.base.IntType;
import de.evoal.languages.model.base.IntegerLiteral;
import de.evoal.languages.model.base.LiteralType;
import de.evoal.languages.model.base.MultiplyDivideModuloExpression;
import de.evoal.languages.model.base.NotExpression;
import de.evoal.languages.model.base.OrExpression;
import de.evoal.languages.model.base.Parantheses;
import de.evoal.languages.model.base.PartialComparisonExpression;
import de.evoal.languages.model.base.PowerOfExpression;
import de.evoal.languages.model.base.RealLiteral;
import de.evoal.languages.model.base.RealType;
import de.evoal.languages.model.base.StringLiteral;
import de.evoal.languages.model.base.StringType;
import de.evoal.languages.model.base.TypeDefinition;
import de.evoal.languages.model.base.UnaryAddOrSubtractExpression;
import de.evoal.languages.model.base.VoidType;
import de.evoal.languages.model.base.XorExpression;
import de.evoal.languages.model.base.dsl.services.BaseLanguageGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class BaseLanguageSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private BaseLanguageGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == BasePackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case BasePackage.ADD_OR_SUBTRACT_EXPRESSION:
				sequence_AddOrSubtractExpressionRule(context, (AddOrSubtractExpression) semanticObject); 
				return; 
			case BasePackage.AND_EXPRESSION:
				sequence_AndExpressionRule(context, (AndExpression) semanticObject); 
				return; 
			case BasePackage.ARRAY:
				sequence_ArrayRule(context, (Array) semanticObject); 
				return; 
			case BasePackage.ARRAY_TYPE:
				sequence_ArrayTypeRule(context, (ArrayType) semanticObject); 
				return; 
			case BasePackage.ATTRIBUTE:
				sequence_AttributeRule(context, (Attribute) semanticObject); 
				return; 
			case BasePackage.ATTRIBUTE_DEFINITION:
				sequence_AttributeDefinitionRule(context, (AttributeDefinition) semanticObject); 
				return; 
			case BasePackage.BOOLEAN_LITERAL:
				sequence_BooleanLiteralRule(context, (BooleanLiteral) semanticObject); 
				return; 
			case BasePackage.BOOLEAN_TYPE:
				sequence_BooleanTypeRule(context, (BooleanType) semanticObject); 
				return; 
			case BasePackage.CALL:
				sequence_CallRule(context, (Call) semanticObject); 
				return; 
			case BasePackage.COMPARISON_EXPRESSION:
				sequence_ComparisonExpressionRule(context, (ComparisonExpression) semanticObject); 
				return; 
			case BasePackage.CONSTANT_DEFINITION:
				sequence_ConstantDefinitionRule(context, (ConstantDefinition) semanticObject); 
				return; 
			case BasePackage.CONSTANT_REFERENCE:
				sequence_ConstantReferenceRule(context, (ConstantReference) semanticObject); 
				return; 
			case BasePackage.DATA_OR_INSTANCE_TYPE:
				sequence_DataOrInstanceTypeRule(context, (DataOrInstanceType) semanticObject); 
				return; 
			case BasePackage.DATA_TYPE:
				sequence_DataTypeRule(context, (DataType) semanticObject); 
				return; 
			case BasePackage.DEFINED_FUNCTION_NAME:
				sequence_FunctionNameRule(context, (DefinedFunctionName) semanticObject); 
				return; 
			case BasePackage.EXPRESSION_TYPE:
				sequence_ExpressionTypeRule(context, (ExpressionType) semanticObject); 
				return; 
			case BasePackage.FUNCTION_DEFINITION:
				sequence_FunctionDefinitionRule(context, (FunctionDefinition) semanticObject); 
				return; 
			case BasePackage.IMPORT:
				sequence_ImportRule(context, (Import) semanticObject); 
				return; 
			case BasePackage.INSTANCE:
				sequence_InstanceLiteralRule(context, (Instance) semanticObject); 
				return; 
			case BasePackage.INSTANCE_TYPE:
				sequence_InstanceTypeRule(context, (InstanceType) semanticObject); 
				return; 
			case BasePackage.INT_TYPE:
				sequence_IntTypeRule(context, (IntType) semanticObject); 
				return; 
			case BasePackage.INTEGER_LITERAL:
				sequence_IntegerLiteralRule(context, (IntegerLiteral) semanticObject); 
				return; 
			case BasePackage.LITERAL_TYPE:
				sequence_LiteralTypeRule(context, (LiteralType) semanticObject); 
				return; 
			case BasePackage.MULTIPLY_DIVIDE_MODULO_EXPRESSION:
				sequence_MultiplyDivideModuloExpressionRule(context, (MultiplyDivideModuloExpression) semanticObject); 
				return; 
			case BasePackage.NOT_EXPRESSION:
				sequence_NotExpressionRule(context, (NotExpression) semanticObject); 
				return; 
			case BasePackage.OR_EXPRESSION:
				sequence_OrExpressionRule(context, (OrExpression) semanticObject); 
				return; 
			case BasePackage.PARAMETER:
				sequence_ParameterRule(context, (de.evoal.languages.model.base.Parameter) semanticObject); 
				return; 
			case BasePackage.PARANTHESES:
				sequence_ParanthesesRule(context, (Parantheses) semanticObject); 
				return; 
			case BasePackage.PARTIAL_COMPARISON_EXPRESSION:
				sequence_PartialComparisonExpressionRule(context, (PartialComparisonExpression) semanticObject); 
				return; 
			case BasePackage.POWER_OF_EXPRESSION:
				sequence_PowerOfExpressionRule(context, (PowerOfExpression) semanticObject); 
				return; 
			case BasePackage.REAL_LITERAL:
				sequence_RealLiteralRule(context, (RealLiteral) semanticObject); 
				return; 
			case BasePackage.REAL_TYPE:
				sequence_RealTypeRule(context, (RealType) semanticObject); 
				return; 
			case BasePackage.STRING_LITERAL:
				sequence_StringLiteralRule(context, (StringLiteral) semanticObject); 
				return; 
			case BasePackage.STRING_TYPE:
				sequence_StringTypeRule(context, (StringType) semanticObject); 
				return; 
			case BasePackage.TYPE_DEFINITION:
				sequence_TypeDefinitionRule(context, (TypeDefinition) semanticObject); 
				return; 
			case BasePackage.UNARY_ADD_OR_SUBTRACT_EXPRESSION:
				sequence_UnaryAddOrSubtractExpressionRule(context, (UnaryAddOrSubtractExpression) semanticObject); 
				return; 
			case BasePackage.VOID_TYPE:
				sequence_VoidTypeRule(context, (VoidType) semanticObject); 
				return; 
			case BasePackage.XOR_EXPRESSION:
				sequence_XorExpressionRule(context, (XorExpression) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     AddOrSubtractExpressionRule returns AddOrSubtractExpression
	 *
	 * Constraint:
	 *     (leftOperand=MultiplyDivideModuloExpressionRule (operators+=AddOrSubtractOperatorRule operands+=MultiplyDivideModuloExpressionRule)*)
	 * </pre>
	 */
	protected void sequence_AddOrSubtractExpressionRule(ISerializationContext context, AddOrSubtractExpression semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AndExpressionRule returns AndExpression
	 *
	 * Constraint:
	 *     (subExpressions+=NotExpressionRule subExpressions+=NotExpressionRule*)
	 * </pre>
	 */
	protected void sequence_AndExpressionRule(ISerializationContext context, AndExpression semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ValueRule returns Array
	 *     ArrayRule returns Array
	 *
	 * Constraint:
	 *     (values+=ValueRule values+=ValueRule*)?
	 * </pre>
	 */
	protected void sequence_ArrayRule(ISerializationContext context, Array semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TypeRule returns ArrayType
	 *     ArrayTypeRule returns ArrayType
	 *
	 * Constraint:
	 *     elements=TypeRule
	 * </pre>
	 */
	protected void sequence_ArrayTypeRule(ISerializationContext context, ArrayType semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BasePackage.Literals.ARRAY_TYPE__ELEMENTS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BasePackage.Literals.ARRAY_TYPE__ELEMENTS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getArrayTypeRuleAccess().getElementsTypeRuleParserRuleCall_1_0(), semanticObject.getElements());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AttributeDefinitionRule returns AttributeDefinition
	 *
	 * Constraint:
	 *     (name=StringOrId type=TypeRule initialisation=ExpressionRule?)
	 * </pre>
	 */
	protected void sequence_AttributeDefinitionRule(ISerializationContext context, AttributeDefinition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AttributeRule returns Attribute
	 *
	 * Constraint:
	 *     (definition=[AttributeDefinition|StringOrId] value=ExpressionRule)
	 * </pre>
	 */
	protected void sequence_AttributeRule(ISerializationContext context, Attribute semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BasePackage.Literals.ATTRIBUTE__DEFINITION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BasePackage.Literals.ATTRIBUTE__DEFINITION));
			if (transientValues.isValueTransient(semanticObject, BasePackage.Literals.ATTRIBUTE__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BasePackage.Literals.ATTRIBUTE__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAttributeRuleAccess().getDefinitionAttributeDefinitionStringOrIdParserRuleCall_0_0_1(), semanticObject.eGet(BasePackage.Literals.ATTRIBUTE__DEFINITION, false));
		feeder.accept(grammarAccess.getAttributeRuleAccess().getValueExpressionRuleParserRuleCall_2_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ValueRule returns BooleanLiteral
	 *     LiteralRule returns BooleanLiteral
	 *     BooleanLiteralRule returns BooleanLiteral
	 *
	 * Constraint:
	 *     value?='true'?
	 * </pre>
	 */
	protected void sequence_BooleanLiteralRule(ISerializationContext context, BooleanLiteral semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TypeRule returns BooleanType
	 *     BooleanTypeRule returns BooleanType
	 *
	 * Constraint:
	 *     {BooleanType}
	 * </pre>
	 */
	protected void sequence_BooleanTypeRule(ISerializationContext context, BooleanType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ValueRule returns Call
	 *     CallRule returns Call
	 *
	 * Constraint:
	 *     (function=FunctionNameRule (parameters+=ExpressionRule parameters+=ExpressionRule*)?)
	 * </pre>
	 */
	protected void sequence_CallRule(ISerializationContext context, Call semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ComparisonExpressionRule returns ComparisonExpression
	 *
	 * Constraint:
	 *     (leftOperand=AddOrSubtractExpressionRule comparison+=PartialComparisonExpressionRule*)
	 * </pre>
	 */
	protected void sequence_ComparisonExpressionRule(ISerializationContext context, ComparisonExpression semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ConstantDefinitionRule returns ConstantDefinition
	 *
	 * Constraint:
	 *     (type=TypeRule name=StringOrId value=ExpressionRule)
	 * </pre>
	 */
	protected void sequence_ConstantDefinitionRule(ISerializationContext context, ConstantDefinition semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BasePackage.Literals.CONSTANT_DEFINITION__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BasePackage.Literals.CONSTANT_DEFINITION__TYPE));
			if (transientValues.isValueTransient(semanticObject, BasePackage.Literals.CONSTANT_DEFINITION__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BasePackage.Literals.CONSTANT_DEFINITION__NAME));
			if (transientValues.isValueTransient(semanticObject, BasePackage.Literals.CONSTANT_DEFINITION__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BasePackage.Literals.CONSTANT_DEFINITION__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getConstantDefinitionRuleAccess().getTypeTypeRuleParserRuleCall_1_0(), semanticObject.getType());
		feeder.accept(grammarAccess.getConstantDefinitionRuleAccess().getNameStringOrIdParserRuleCall_2_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getConstantDefinitionRuleAccess().getValueExpressionRuleParserRuleCall_4_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ValueRule returns ConstantReference
	 *     ReferenceRule returns ConstantReference
	 *     ConstantReferenceRule returns ConstantReference
	 *
	 * Constraint:
	 *     definition=[ConstantDefinition|QualifiedName]
	 * </pre>
	 */
	protected void sequence_ConstantReferenceRule(ISerializationContext context, ConstantReference semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BasePackage.Literals.CONSTANT_REFERENCE__DEFINITION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BasePackage.Literals.CONSTANT_REFERENCE__DEFINITION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getConstantReferenceRuleAccess().getDefinitionConstantDefinitionQualifiedNameParserRuleCall_0_1(), semanticObject.eGet(BasePackage.Literals.CONSTANT_REFERENCE__DEFINITION, false));
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TypeRule returns DataOrInstanceType
	 *     DataOrInstanceTypeRule returns DataOrInstanceType
	 *
	 * Constraint:
	 *     instance=InstanceTypeRule?
	 * </pre>
	 */
	protected void sequence_DataOrInstanceTypeRule(ISerializationContext context, DataOrInstanceType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TypeRule returns DataType
	 *     DataTypeRule returns DataType
	 *
	 * Constraint:
	 *     {DataType}
	 * </pre>
	 */
	protected void sequence_DataTypeRule(ISerializationContext context, DataType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TypeRule returns ExpressionType
	 *     ExpressionTypeRule returns ExpressionType
	 *
	 * Constraint:
	 *     {ExpressionType}
	 * </pre>
	 */
	protected void sequence_ExpressionTypeRule(ISerializationContext context, ExpressionType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     FunctionDefinitionRule returns FunctionDefinition
	 *
	 * Constraint:
	 *     (type=TypeRule name=StringOrId (parameters+=ParameterRule parameters+=ParameterRule*)?)
	 * </pre>
	 */
	protected void sequence_FunctionDefinitionRule(ISerializationContext context, FunctionDefinition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     FunctionNameRule returns DefinedFunctionName
	 *
	 * Constraint:
	 *     definition=[FunctionDefinition|QualifiedName]
	 * </pre>
	 */
	protected void sequence_FunctionNameRule(ISerializationContext context, DefinedFunctionName semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BasePackage.Literals.DEFINED_FUNCTION_NAME__DEFINITION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BasePackage.Literals.DEFINED_FUNCTION_NAME__DEFINITION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getFunctionNameRuleAccess().getDefinitionFunctionDefinitionQualifiedNameParserRuleCall_0_1(), semanticObject.eGet(BasePackage.Literals.DEFINED_FUNCTION_NAME__DEFINITION, false));
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ImportRule returns Import
	 *
	 * Constraint:
	 *     (language=STRING importedNamespace=QualifiedName)
	 * </pre>
	 */
	protected void sequence_ImportRule(ISerializationContext context, Import semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BasePackage.Literals.IMPORT__LANGUAGE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BasePackage.Literals.IMPORT__LANGUAGE));
			if (transientValues.isValueTransient(semanticObject, BasePackage.Literals.IMPORT__IMPORTED_NAMESPACE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BasePackage.Literals.IMPORT__IMPORTED_NAMESPACE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getImportRuleAccess().getLanguageSTRINGTerminalRuleCall_1_0(), semanticObject.getLanguage());
		feeder.accept(grammarAccess.getImportRuleAccess().getImportedNamespaceQualifiedNameParserRuleCall_3_0(), semanticObject.getImportedNamespace());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ValueRule returns Instance
	 *     LiteralRule returns Instance
	 *     InstanceLiteralRule returns Instance
	 *
	 * Constraint:
	 *     (definition=[TypeDefinition|QualifiedName] attributes+=AttributeRule*)
	 * </pre>
	 */
	protected void sequence_InstanceLiteralRule(ISerializationContext context, Instance semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TypeRule returns InstanceType
	 *     InstanceTypeRule returns InstanceType
	 *
	 * Constraint:
	 *     definition=[TypeDefinition|QualifiedName]
	 * </pre>
	 */
	protected void sequence_InstanceTypeRule(ISerializationContext context, InstanceType semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BasePackage.Literals.INSTANCE_TYPE__DEFINITION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BasePackage.Literals.INSTANCE_TYPE__DEFINITION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getInstanceTypeRuleAccess().getDefinitionTypeDefinitionQualifiedNameParserRuleCall_2_0_1(), semanticObject.eGet(BasePackage.Literals.INSTANCE_TYPE__DEFINITION, false));
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TypeRule returns IntType
	 *     IntTypeRule returns IntType
	 *
	 * Constraint:
	 *     {IntType}
	 * </pre>
	 */
	protected void sequence_IntTypeRule(ISerializationContext context, IntType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ValueRule returns IntegerLiteral
	 *     LiteralRule returns IntegerLiteral
	 *     NumberLiteralRule returns IntegerLiteral
	 *     IntegerLiteralRule returns IntegerLiteral
	 *
	 * Constraint:
	 *     (literal=INT factor=FactorRule?)
	 * </pre>
	 */
	protected void sequence_IntegerLiteralRule(ISerializationContext context, IntegerLiteral semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TypeRule returns LiteralType
	 *     LiteralTypeRule returns LiteralType
	 *
	 * Constraint:
	 *     {LiteralType}
	 * </pre>
	 */
	protected void sequence_LiteralTypeRule(ISerializationContext context, LiteralType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     MultiplyDivideModuloExpressionRule returns MultiplyDivideModuloExpression
	 *
	 * Constraint:
	 *     (leftOperand=PowerOfExpressionRule (operators+=MultiplyDivideModuloOperatorRule operands+=PowerOfExpressionRule)*)
	 * </pre>
	 */
	protected void sequence_MultiplyDivideModuloExpressionRule(ISerializationContext context, MultiplyDivideModuloExpression semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     NotExpressionRule returns NotExpression
	 *
	 * Constraint:
	 *     (negated?='!'? operand=ComparisonExpressionRule)
	 * </pre>
	 */
	protected void sequence_NotExpressionRule(ISerializationContext context, NotExpression semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ExpressionRule returns OrExpression
	 *     OrExpressionRule returns OrExpression
	 *
	 * Constraint:
	 *     (subExpressions+=XorExpressionRule subExpressions+=XorExpressionRule*)
	 * </pre>
	 */
	protected void sequence_OrExpressionRule(ISerializationContext context, OrExpression semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ParameterRule returns Parameter
	 *
	 * Constraint:
	 *     (type=TypeRule name=StringOrId)
	 * </pre>
	 */
	protected void sequence_ParameterRule(ISerializationContext context, de.evoal.languages.model.base.Parameter semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BasePackage.Literals.PARAMETER__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BasePackage.Literals.PARAMETER__TYPE));
			if (transientValues.isValueTransient(semanticObject, BasePackage.Literals.PARAMETER__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BasePackage.Literals.PARAMETER__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getParameterRuleAccess().getTypeTypeRuleParserRuleCall_0_0(), semanticObject.getType());
		feeder.accept(grammarAccess.getParameterRuleAccess().getNameStringOrIdParserRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ValueRule returns Parantheses
	 *     ParanthesesRule returns Parantheses
	 *
	 * Constraint:
	 *     subExpression=ExpressionRule
	 * </pre>
	 */
	protected void sequence_ParanthesesRule(ISerializationContext context, Parantheses semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BasePackage.Literals.PARANTHESES__SUB_EXPRESSION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BasePackage.Literals.PARANTHESES__SUB_EXPRESSION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getParanthesesRuleAccess().getSubExpressionExpressionRuleParserRuleCall_1_0(), semanticObject.getSubExpression());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     PartialComparisonExpressionRule returns PartialComparisonExpression
	 *
	 * Constraint:
	 *     (operator=ComparisonOperatorRule subExpression=AddOrSubtractExpressionRule)
	 * </pre>
	 */
	protected void sequence_PartialComparisonExpressionRule(ISerializationContext context, PartialComparisonExpression semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BasePackage.Literals.PARTIAL_COMPARISON_EXPRESSION__OPERATOR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BasePackage.Literals.PARTIAL_COMPARISON_EXPRESSION__OPERATOR));
			if (transientValues.isValueTransient(semanticObject, BasePackage.Literals.PARTIAL_COMPARISON_EXPRESSION__SUB_EXPRESSION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BasePackage.Literals.PARTIAL_COMPARISON_EXPRESSION__SUB_EXPRESSION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPartialComparisonExpressionRuleAccess().getOperatorComparisonOperatorRuleEnumRuleCall_0_0(), semanticObject.getOperator());
		feeder.accept(grammarAccess.getPartialComparisonExpressionRuleAccess().getSubExpressionAddOrSubtractExpressionRuleParserRuleCall_1_0(), semanticObject.getSubExpression());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     PowerOfExpressionRule returns PowerOfExpression
	 *
	 * Constraint:
	 *     (leftOperand=UnaryAddOrSubtractExpressionRule rightOperand=PowerOfExpressionRule?)
	 * </pre>
	 */
	protected void sequence_PowerOfExpressionRule(ISerializationContext context, PowerOfExpression semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ValueRule returns RealLiteral
	 *     LiteralRule returns RealLiteral
	 *     NumberLiteralRule returns RealLiteral
	 *     RealLiteralRule returns RealLiteral
	 *
	 * Constraint:
	 *     (literal=DOUBLE factor=FactorRule?)
	 * </pre>
	 */
	protected void sequence_RealLiteralRule(ISerializationContext context, RealLiteral semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TypeRule returns RealType
	 *     RealTypeRule returns RealType
	 *
	 * Constraint:
	 *     {RealType}
	 * </pre>
	 */
	protected void sequence_RealTypeRule(ISerializationContext context, RealType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ValueRule returns StringLiteral
	 *     LiteralRule returns StringLiteral
	 *     StringLiteralRule returns StringLiteral
	 *
	 * Constraint:
	 *     value=STRING
	 * </pre>
	 */
	protected void sequence_StringLiteralRule(ISerializationContext context, StringLiteral semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, BasePackage.Literals.STRING_LITERAL__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, BasePackage.Literals.STRING_LITERAL__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getStringLiteralRuleAccess().getValueSTRINGTerminalRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TypeRule returns StringType
	 *     StringTypeRule returns StringType
	 *
	 * Constraint:
	 *     {StringType}
	 * </pre>
	 */
	protected void sequence_StringTypeRule(ISerializationContext context, StringType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TypeDefinitionRule returns TypeDefinition
	 *
	 * Constraint:
	 *     (abstract?='abstract'? name=StringOrId superType=[TypeDefinition|QualifiedName]? attributes+=AttributeDefinitionRule*)
	 * </pre>
	 */
	protected void sequence_TypeDefinitionRule(ISerializationContext context, TypeDefinition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     UnaryAddOrSubtractExpressionRule returns UnaryAddOrSubtractExpression
	 *
	 * Constraint:
	 *     (operators+=AddOrSubtractOperatorRule* subExpression=ValueRule)
	 * </pre>
	 */
	protected void sequence_UnaryAddOrSubtractExpressionRule(ISerializationContext context, UnaryAddOrSubtractExpression semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TypeRule returns VoidType
	 *     VoidTypeRule returns VoidType
	 *
	 * Constraint:
	 *     {VoidType}
	 * </pre>
	 */
	protected void sequence_VoidTypeRule(ISerializationContext context, VoidType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     XorExpressionRule returns XorExpression
	 *
	 * Constraint:
	 *     (subExpressions+=AndExpressionRule subExpressions+=AndExpressionRule*)
	 * </pre>
	 */
	protected void sequence_XorExpressionRule(ISerializationContext context, XorExpression semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
