/**
 * generated by Xtext 2.25.0
 */
package de.evoal.languages.model.dl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Definition Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <!-- begin-model-doc -->
 * Root element of the model allowing to define instances, functions
 * and data.
 * <!-- end-model-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.evoal.languages.model.dl.DefinitionModel#getTypes <em>Types</em>}</li>
 *   <li>{@link de.evoal.languages.model.dl.DefinitionModel#getFunctions <em>Functions</em>}</li>
 * </ul>
 *
 * @see de.evoal.languages.model.dl.DlPackage#getDefinitionModel()
 * @model
 * @generated
 */
public interface DefinitionModel extends EObject {
	/**
	 * Returns the value of the '<em><b>Types</b></em>' containment reference list.
	 * The list contents are of type {@link de.evoal.languages.model.dl.TypeDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * List of all available types.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Types</em>' containment reference list.
	 * @see de.evoal.languages.model.dl.DlPackage#getDefinitionModel_Types()
	 * @model containment="true" ordered="false"
	 * @generated
	 */
	EList<TypeDefinition> getTypes();

	/**
	 * Returns the value of the '<em><b>Functions</b></em>' containment reference list.
	 * The list contents are of type {@link de.evoal.languages.model.dl.FunctionDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * List of all available functions in this definition model.
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Functions</em>' containment reference list.
	 * @see de.evoal.languages.model.dl.DlPackage#getDefinitionModel_Functions()
	 * @model containment="true" ordered="false"
	 *        annotation="http://www.eclipse.org/OCL/Collection nullFree='false'"
	 * @generated
	 */
	EList<FunctionDefinition> getFunctions();

} // DefinitionModel
