/**
 * generated by Xtext 2.25.0
 */
package de.evoal.languages.model.dl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * <!-- begin-model-doc -->
 * The definition language allows us to define types and functions for
 * configuration purposes.
 * <!-- end-model-doc -->
 * @see de.evoal.languages.model.dl.DlFactory
 * @model kind="package"
 *        annotation="http://www.eclipse.org/OCL/Import el='platform:/resource/de.evoal.languages.model.base/model/model.ecore#/'"
 * @generated
 */
public interface DlPackage extends EPackage {
	/**
	 * The package name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNAME = "dl";

	/**
	 * The package namespace URI.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNS_URI = "https://www.evoal.de/languages/dl/1.0.0";

	/**
	 * The package namespace name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNS_PREFIX = "dl";

	/**
	 * The singleton instance of the package.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	DlPackage eINSTANCE = de.evoal.languages.model.dl.impl.DlPackageImpl.init();

	/**
	 * The meta object id for the '{@link de.evoal.languages.model.dl.impl.DefinitionModuleImpl <em>Definition Module</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see de.evoal.languages.model.dl.impl.DefinitionModuleImpl
	 * @see de.evoal.languages.model.dl.impl.DlPackageImpl#getDefinitionModule()
	 * @generated
	 */
	int DEFINITION_MODULE = 0;

	/**
	 * The feature id for the '<em><b>Imports</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DEFINITION_MODULE__IMPORTS = 0;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DEFINITION_MODULE__NAME = 1;

	/**
	 * The feature id for the '<em><b>Types</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DEFINITION_MODULE__TYPES = 2;

	/**
	 * The feature id for the '<em><b>Functions</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DEFINITION_MODULE__FUNCTIONS = 3;

	/**
	 * The feature id for the '<em><b>Constants</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DEFINITION_MODULE__CONSTANTS = 4;

	/**
	 * The number of structural features of the '<em>Definition Module</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DEFINITION_MODULE_FEATURE_COUNT = 5;


	/**
	 * Returns the meta object for class '{@link de.evoal.languages.model.dl.DefinitionModule <em>Definition Module</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Definition Module</em>'.
	 * @see de.evoal.languages.model.dl.DefinitionModule
	 * @generated
	 */
	EClass getDefinitionModule();

	/**
	 * Returns the meta object for the containment reference list '{@link de.evoal.languages.model.dl.DefinitionModule#getImports <em>Imports</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Imports</em>'.
	 * @see de.evoal.languages.model.dl.DefinitionModule#getImports()
	 * @see #getDefinitionModule()
	 * @generated
	 */
	EReference getDefinitionModule_Imports();

	/**
	 * Returns the meta object for the attribute '{@link de.evoal.languages.model.dl.DefinitionModule#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see de.evoal.languages.model.dl.DefinitionModule#getName()
	 * @see #getDefinitionModule()
	 * @generated
	 */
	EAttribute getDefinitionModule_Name();

	/**
	 * Returns the meta object for the containment reference list '{@link de.evoal.languages.model.dl.DefinitionModule#getTypes <em>Types</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Types</em>'.
	 * @see de.evoal.languages.model.dl.DefinitionModule#getTypes()
	 * @see #getDefinitionModule()
	 * @generated
	 */
	EReference getDefinitionModule_Types();

	/**
	 * Returns the meta object for the containment reference list '{@link de.evoal.languages.model.dl.DefinitionModule#getFunctions <em>Functions</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Functions</em>'.
	 * @see de.evoal.languages.model.dl.DefinitionModule#getFunctions()
	 * @see #getDefinitionModule()
	 * @generated
	 */
	EReference getDefinitionModule_Functions();

	/**
	 * Returns the meta object for the containment reference list '{@link de.evoal.languages.model.dl.DefinitionModule#getConstants <em>Constants</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Constants</em>'.
	 * @see de.evoal.languages.model.dl.DefinitionModule#getConstants()
	 * @see #getDefinitionModule()
	 * @generated
	 */
	EReference getDefinitionModule_Constants();

	/**
	 * Returns the factory that creates the instances of the model.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the factory that creates the instances of the model.
	 * @generated
	 */
	DlFactory getDlFactory();

	/**
	 * <!-- begin-user-doc -->
	 * Defines literals for the meta objects that represent
	 * <ul>
	 *   <li>each class,</li>
	 *   <li>each feature of each class,</li>
	 *   <li>each enum,</li>
	 *   <li>and each data type</li>
	 * </ul>
	 * <!-- end-user-doc -->
	 * @generated
	 */
	interface Literals {
		/**
		 * The meta object literal for the '{@link de.evoal.languages.model.dl.impl.DefinitionModuleImpl <em>Definition Module</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see de.evoal.languages.model.dl.impl.DefinitionModuleImpl
		 * @see de.evoal.languages.model.dl.impl.DlPackageImpl#getDefinitionModule()
		 * @generated
		 */
		EClass DEFINITION_MODULE = eINSTANCE.getDefinitionModule();

		/**
		 * The meta object literal for the '<em><b>Imports</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference DEFINITION_MODULE__IMPORTS = eINSTANCE.getDefinitionModule_Imports();

		/**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute DEFINITION_MODULE__NAME = eINSTANCE.getDefinitionModule_Name();

		/**
		 * The meta object literal for the '<em><b>Types</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference DEFINITION_MODULE__TYPES = eINSTANCE.getDefinitionModule_Types();

		/**
		 * The meta object literal for the '<em><b>Functions</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference DEFINITION_MODULE__FUNCTIONS = eINSTANCE.getDefinitionModule_Functions();

		/**
		 * The meta object literal for the '<em><b>Constants</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference DEFINITION_MODULE__CONSTANTS = eINSTANCE.getDefinitionModule_Constants();

	}

} //DlPackage
