/*
 * generated by Xtext 2.25.0
 */
package de.evoal.languages.model.dl.dsl.validation;

import org.eclipse.xtext.validation.Check;

import de.evoal.languages.model.dl.DefinitionModule;
import de.evoal.languages.model.dl.DlPackage;
import de.evoal.languages.model.utils.validator.ModuleValidator;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class DefinitionLanguageValidator extends AbstractDefinitionLanguageValidator {
	
//	public static final String INVALID_NAME = "invalidName";
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					InstanceDefinitionLanguagePackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	
	
	@Check
	public void checkModule(final DefinitionModule module) {
		ModuleValidator.check(module, module.getName(), "dl", msg -> error(msg, module, DlPackage.Literals.DEFINITION_MODULE__NAME));
	}

}
