import "definitions" from de.evoal.optimisation.core;
import "definitions" from de.evoal.optimisation.hc.optimisation;

module de.evoal.optimisation.sa.optimisation {

    /**
    * simulated annealing algorithm is a metaheuristic optimisation
    * algorithm that seeks new solutions from a set of neighbours
    * and accepts these solutions according to an acceptance probability
    * function. This probability is affected by the temperature, which is
    * decremented according to cooling schedule.
    */
	type 'simulated-annealing-algorithm' extends 'algorithm' {
    	'number-of-iterations' : int;
    	'neighbour-choosing-strategy' : instance 'choosing-strategy';
        'initial-temperature' : real;
        'cooling-schedule' : instance 'cooling-strategy';
        'acceptance-probability' : instance 'probability-acceptance-function';
	}

    /**
    * Cooling strategies determine how temperature is decreased in each iteration
    */
	abstract type 'cooling-strategy' {}

    /**
    * T(k) = T_0 - (k * T_0/#iterations)
    */
	type 'linear-cooling' extends 'cooling-strategy' {}

    /**
    * T(k) = T(k-1) * cooling_rate
    */
    type 'geometric-cooling' extends 'cooling-strategy' {
        'cooling-rate' : real;
    }

    /**
    * T(k) = T_0/log(k+1)
    */
    type 'logarithmic-cooling' extends 'cooling-strategy' {}

    /**
    * T(k) = T_0 * exp(-k^(1/N))
    */
    type 'exponential-cooling' extends 'cooling-strategy' {}

    /**
    * T(k) = T(k-1) - (rate*k)
    */
    type 'arithmetic-cooling' extends 'cooling-strategy' {
        'rate' : real;
    }

    /**
    * Determines probability of accepting neighbouring solutions based
    * on fitness and temperature.
    */
    abstract type 'probability-acceptance-function' {}

    /**
    * Exponential acceptance function determines acceptance probability according to formula:
    * P(f(s), f(s'), T) = exp(max( (f(s')-f(s)/T(k)), 0) for maximisation
    * P(f(s), f(s'), T) = exp(max( -(f(s')-f(s)/T(k)), 0) for minimisation
    */
    type 'exponential-probability' extends 'probability-acceptance-function' {}

}
