/**
 * generated by Xtext 2.25.0
 */
package de.evoal.languages.model.generator;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>References</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.evoal.languages.model.generator.GeneratorReferences#getGenerators <em>Generators</em>}</li>
 * </ul>
 *
 * @see de.evoal.languages.model.generator.GeneratorPackage#getGeneratorReferences()
 * @model
 * @generated
 */
public interface GeneratorReferences extends EObject {
	/**
	 * Returns the value of the '<em><b>Generators</b></em>' reference list.
	 * The list contents are of type {@link de.evoal.languages.model.generator.GeneratorDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Generators</em>' reference list.
	 * @see de.evoal.languages.model.generator.GeneratorPackage#getGeneratorReferences_Generators()
	 * @model
	 * @generated
	 */
	EList<GeneratorDefinition> getGenerators();

} // GeneratorReferences
