/**
 * generated by Xtext 2.25.0
 */
package de.evoal.languages.model.generator;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see de.evoal.languages.model.generator.GeneratorFactory
 * @model kind="package"
 *        annotation="http://www.eclipse.org/OCL/Import dl='platform:/resource/de.evoal.languages.model.dl/model/model.ecore#/' ecore='http://www.eclipse.org/emf/2002/Ecore' ins='platform:/resource/de.evoal.languages.model.instance/model/model.ecore#/'"
 * @generated
 */
public interface GeneratorPackage extends EPackage {
	/**
	 * The package name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNAME = "generator";

	/**
	 * The package namespace URI.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNS_URI = "https://www.evoal.de/languages/generator/1.0.0";

	/**
	 * The package namespace name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNS_PREFIX = "generator";

	/**
	 * The singleton instance of the package.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	GeneratorPackage eINSTANCE = de.evoal.languages.model.generator.impl.GeneratorPackageImpl.init();

	/**
	 * The meta object id for the '{@link de.evoal.languages.model.generator.impl.ConfigurationImpl <em>Configuration</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see de.evoal.languages.model.generator.impl.ConfigurationImpl
	 * @see de.evoal.languages.model.generator.impl.GeneratorPackageImpl#getConfiguration()
	 * @generated
	 */
	int CONFIGURATION = 0;

	/**
	 * The feature id for the '<em><b>Uses</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CONFIGURATION__USES = 0;

	/**
	 * The feature id for the '<em><b>Pipelines</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CONFIGURATION__PIPELINES = 1;

	/**
	 * The feature id for the '<em><b>Statements</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CONFIGURATION__STATEMENTS = 2;

	/**
	 * The number of structural features of the '<em>Configuration</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int CONFIGURATION_FEATURE_COUNT = 3;

	/**
	 * The meta object id for the '{@link de.evoal.languages.model.generator.impl.UseImpl <em>Use</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see de.evoal.languages.model.generator.impl.UseImpl
	 * @see de.evoal.languages.model.generator.impl.GeneratorPackageImpl#getUse()
	 * @generated
	 */
	int USE = 1;

	/**
	 * The feature id for the '<em><b>Import URI</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int USE__IMPORT_URI = 0;

	/**
	 * The number of structural features of the '<em>Use</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int USE_FEATURE_COUNT = 1;

	/**
	 * The meta object id for the '{@link de.evoal.languages.model.generator.impl.PipelineDefinitionImpl <em>Pipeline Definition</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see de.evoal.languages.model.generator.impl.PipelineDefinitionImpl
	 * @see de.evoal.languages.model.generator.impl.GeneratorPackageImpl#getPipelineDefinition()
	 * @generated
	 */
	int PIPELINE_DEFINITION = 2;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int PIPELINE_DEFINITION__NAME = 0;

	/**
	 * The feature id for the '<em><b>Definitions</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int PIPELINE_DEFINITION__DEFINITIONS = 1;

	/**
	 * The number of structural features of the '<em>Pipeline Definition</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int PIPELINE_DEFINITION_FEATURE_COUNT = 2;

	/**
	 * The meta object id for the '{@link de.evoal.languages.model.generator.impl.StatementImpl <em>Statement</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see de.evoal.languages.model.generator.impl.StatementImpl
	 * @see de.evoal.languages.model.generator.impl.GeneratorPackageImpl#getStatement()
	 * @generated
	 */
	int STATEMENT = 3;

	/**
	 * The number of structural features of the '<em>Statement</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int STATEMENT_FEATURE_COUNT = 0;

	/**
	 * The meta object id for the '{@link de.evoal.languages.model.generator.impl.ForStatementImpl <em>For Statement</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see de.evoal.languages.model.generator.impl.ForStatementImpl
	 * @see de.evoal.languages.model.generator.impl.GeneratorPackageImpl#getForStatement()
	 * @generated
	 */
	int FOR_STATEMENT = 4;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FOR_STATEMENT__NAME = STATEMENT_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>Range</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FOR_STATEMENT__RANGE = STATEMENT_FEATURE_COUNT + 1;

	/**
	 * The feature id for the '<em><b>Statements</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FOR_STATEMENT__STATEMENTS = STATEMENT_FEATURE_COUNT + 2;

	/**
	 * The number of structural features of the '<em>For Statement</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int FOR_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 3;

	/**
	 * The meta object id for the '{@link de.evoal.languages.model.generator.impl.RangeImpl <em>Range</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see de.evoal.languages.model.generator.impl.RangeImpl
	 * @see de.evoal.languages.model.generator.impl.GeneratorPackageImpl#getRange()
	 * @generated
	 */
	int RANGE = 5;

	/**
	 * The number of structural features of the '<em>Range</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int RANGE_FEATURE_COUNT = 0;

	/**
	 * The meta object id for the '{@link de.evoal.languages.model.generator.impl.CounterRangeImpl <em>Counter Range</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see de.evoal.languages.model.generator.impl.CounterRangeImpl
	 * @see de.evoal.languages.model.generator.impl.GeneratorPackageImpl#getCounterRange()
	 * @generated
	 */
	int COUNTER_RANGE = 6;

	/**
	 * The feature id for the '<em><b>Start</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int COUNTER_RANGE__START = RANGE_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>End</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int COUNTER_RANGE__END = RANGE_FEATURE_COUNT + 1;

	/**
	 * The number of structural features of the '<em>Counter Range</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int COUNTER_RANGE_FEATURE_COUNT = RANGE_FEATURE_COUNT + 2;

	/**
	 * The meta object id for the '{@link de.evoal.languages.model.generator.impl.PipelineArrayImpl <em>Pipeline Array</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see de.evoal.languages.model.generator.impl.PipelineArrayImpl
	 * @see de.evoal.languages.model.generator.impl.GeneratorPackageImpl#getPipelineArray()
	 * @generated
	 */
	int PIPELINE_ARRAY = 7;

	/**
	 * The feature id for the '<em><b>References</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int PIPELINE_ARRAY__REFERENCES = RANGE_FEATURE_COUNT + 0;

	/**
	 * The number of structural features of the '<em>Pipeline Array</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int PIPELINE_ARRAY_FEATURE_COUNT = RANGE_FEATURE_COUNT + 1;

	/**
	 * The meta object id for the '{@link de.evoal.languages.model.generator.impl.PipelineReferenceImpl <em>Pipeline Reference</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see de.evoal.languages.model.generator.impl.PipelineReferenceImpl
	 * @see de.evoal.languages.model.generator.impl.GeneratorPackageImpl#getPipelineReference()
	 * @generated
	 */
	int PIPELINE_REFERENCE = 8;

	/**
	 * The feature id for the '<em><b>Pipeline</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int PIPELINE_REFERENCE__PIPELINE = 0;

	/**
	 * The number of structural features of the '<em>Pipeline Reference</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int PIPELINE_REFERENCE_FEATURE_COUNT = 1;

	/**
	 * The meta object id for the '{@link de.evoal.languages.model.generator.impl.ApplyStatementImpl <em>Apply Statement</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see de.evoal.languages.model.generator.impl.ApplyStatementImpl
	 * @see de.evoal.languages.model.generator.impl.GeneratorPackageImpl#getApplyStatement()
	 * @generated
	 */
	int APPLY_STATEMENT = 9;

	/**
	 * The feature id for the '<em><b>File</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int APPLY_STATEMENT__FILE = STATEMENT_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>Count</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int APPLY_STATEMENT__COUNT = STATEMENT_FEATURE_COUNT + 1;

	/**
	 * The feature id for the '<em><b>Pipelines</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int APPLY_STATEMENT__PIPELINES = STATEMENT_FEATURE_COUNT + 2;

	/**
	 * The number of structural features of the '<em>Apply Statement</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int APPLY_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 3;


	/**
	 * Returns the meta object for class '{@link de.evoal.languages.model.generator.Configuration <em>Configuration</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Configuration</em>'.
	 * @see de.evoal.languages.model.generator.Configuration
	 * @generated
	 */
	EClass getConfiguration();

	/**
	 * Returns the meta object for the containment reference list '{@link de.evoal.languages.model.generator.Configuration#getUses <em>Uses</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Uses</em>'.
	 * @see de.evoal.languages.model.generator.Configuration#getUses()
	 * @see #getConfiguration()
	 * @generated
	 */
	EReference getConfiguration_Uses();

	/**
	 * Returns the meta object for the containment reference list '{@link de.evoal.languages.model.generator.Configuration#getPipelines <em>Pipelines</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Pipelines</em>'.
	 * @see de.evoal.languages.model.generator.Configuration#getPipelines()
	 * @see #getConfiguration()
	 * @generated
	 */
	EReference getConfiguration_Pipelines();

	/**
	 * Returns the meta object for the containment reference list '{@link de.evoal.languages.model.generator.Configuration#getStatements <em>Statements</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Statements</em>'.
	 * @see de.evoal.languages.model.generator.Configuration#getStatements()
	 * @see #getConfiguration()
	 * @generated
	 */
	EReference getConfiguration_Statements();

	/**
	 * Returns the meta object for class '{@link de.evoal.languages.model.generator.Use <em>Use</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Use</em>'.
	 * @see de.evoal.languages.model.generator.Use
	 * @generated
	 */
	EClass getUse();

	/**
	 * Returns the meta object for the attribute '{@link de.evoal.languages.model.generator.Use#getImportURI <em>Import URI</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Import URI</em>'.
	 * @see de.evoal.languages.model.generator.Use#getImportURI()
	 * @see #getUse()
	 * @generated
	 */
	EAttribute getUse_ImportURI();

	/**
	 * Returns the meta object for class '{@link de.evoal.languages.model.generator.PipelineDefinition <em>Pipeline Definition</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Pipeline Definition</em>'.
	 * @see de.evoal.languages.model.generator.PipelineDefinition
	 * @generated
	 */
	EClass getPipelineDefinition();

	/**
	 * Returns the meta object for the attribute '{@link de.evoal.languages.model.generator.PipelineDefinition#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see de.evoal.languages.model.generator.PipelineDefinition#getName()
	 * @see #getPipelineDefinition()
	 * @generated
	 */
	EAttribute getPipelineDefinition_Name();

	/**
	 * Returns the meta object for the containment reference list '{@link de.evoal.languages.model.generator.PipelineDefinition#getDefinitions <em>Definitions</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Definitions</em>'.
	 * @see de.evoal.languages.model.generator.PipelineDefinition#getDefinitions()
	 * @see #getPipelineDefinition()
	 * @generated
	 */
	EReference getPipelineDefinition_Definitions();

	/**
	 * Returns the meta object for class '{@link de.evoal.languages.model.generator.Statement <em>Statement</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Statement</em>'.
	 * @see de.evoal.languages.model.generator.Statement
	 * @generated
	 */
	EClass getStatement();

	/**
	 * Returns the meta object for class '{@link de.evoal.languages.model.generator.ForStatement <em>For Statement</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>For Statement</em>'.
	 * @see de.evoal.languages.model.generator.ForStatement
	 * @generated
	 */
	EClass getForStatement();

	/**
	 * Returns the meta object for the attribute '{@link de.evoal.languages.model.generator.ForStatement#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see de.evoal.languages.model.generator.ForStatement#getName()
	 * @see #getForStatement()
	 * @generated
	 */
	EAttribute getForStatement_Name();

	/**
	 * Returns the meta object for the containment reference '{@link de.evoal.languages.model.generator.ForStatement#getRange <em>Range</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Range</em>'.
	 * @see de.evoal.languages.model.generator.ForStatement#getRange()
	 * @see #getForStatement()
	 * @generated
	 */
	EReference getForStatement_Range();

	/**
	 * Returns the meta object for the containment reference list '{@link de.evoal.languages.model.generator.ForStatement#getStatements <em>Statements</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Statements</em>'.
	 * @see de.evoal.languages.model.generator.ForStatement#getStatements()
	 * @see #getForStatement()
	 * @generated
	 */
	EReference getForStatement_Statements();

	/**
	 * Returns the meta object for class '{@link de.evoal.languages.model.generator.Range <em>Range</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Range</em>'.
	 * @see de.evoal.languages.model.generator.Range
	 * @generated
	 */
	EClass getRange();

	/**
	 * Returns the meta object for class '{@link de.evoal.languages.model.generator.CounterRange <em>Counter Range</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Counter Range</em>'.
	 * @see de.evoal.languages.model.generator.CounterRange
	 * @generated
	 */
	EClass getCounterRange();

	/**
	 * Returns the meta object for the attribute '{@link de.evoal.languages.model.generator.CounterRange#getStart <em>Start</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Start</em>'.
	 * @see de.evoal.languages.model.generator.CounterRange#getStart()
	 * @see #getCounterRange()
	 * @generated
	 */
	EAttribute getCounterRange_Start();

	/**
	 * Returns the meta object for the attribute '{@link de.evoal.languages.model.generator.CounterRange#getEnd <em>End</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>End</em>'.
	 * @see de.evoal.languages.model.generator.CounterRange#getEnd()
	 * @see #getCounterRange()
	 * @generated
	 */
	EAttribute getCounterRange_End();

	/**
	 * Returns the meta object for class '{@link de.evoal.languages.model.generator.PipelineArray <em>Pipeline Array</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Pipeline Array</em>'.
	 * @see de.evoal.languages.model.generator.PipelineArray
	 * @generated
	 */
	EClass getPipelineArray();

	/**
	 * Returns the meta object for the containment reference list '{@link de.evoal.languages.model.generator.PipelineArray#getReferences <em>References</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>References</em>'.
	 * @see de.evoal.languages.model.generator.PipelineArray#getReferences()
	 * @see #getPipelineArray()
	 * @generated
	 */
	EReference getPipelineArray_References();

	/**
	 * Returns the meta object for class '{@link de.evoal.languages.model.generator.PipelineReference <em>Pipeline Reference</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Pipeline Reference</em>'.
	 * @see de.evoal.languages.model.generator.PipelineReference
	 * @generated
	 */
	EClass getPipelineReference();

	/**
	 * Returns the meta object for the reference '{@link de.evoal.languages.model.generator.PipelineReference#getPipeline <em>Pipeline</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference '<em>Pipeline</em>'.
	 * @see de.evoal.languages.model.generator.PipelineReference#getPipeline()
	 * @see #getPipelineReference()
	 * @generated
	 */
	EReference getPipelineReference_Pipeline();

	/**
	 * Returns the meta object for class '{@link de.evoal.languages.model.generator.ApplyStatement <em>Apply Statement</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Apply Statement</em>'.
	 * @see de.evoal.languages.model.generator.ApplyStatement
	 * @generated
	 */
	EClass getApplyStatement();

	/**
	 * Returns the meta object for the attribute '{@link de.evoal.languages.model.generator.ApplyStatement#getFile <em>File</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>File</em>'.
	 * @see de.evoal.languages.model.generator.ApplyStatement#getFile()
	 * @see #getApplyStatement()
	 * @generated
	 */
	EAttribute getApplyStatement_File();

	/**
	 * Returns the meta object for the attribute '{@link de.evoal.languages.model.generator.ApplyStatement#getCount <em>Count</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Count</em>'.
	 * @see de.evoal.languages.model.generator.ApplyStatement#getCount()
	 * @see #getApplyStatement()
	 * @generated
	 */
	EAttribute getApplyStatement_Count();

	/**
	 * Returns the meta object for the containment reference list '{@link de.evoal.languages.model.generator.ApplyStatement#getPipelines <em>Pipelines</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Pipelines</em>'.
	 * @see de.evoal.languages.model.generator.ApplyStatement#getPipelines()
	 * @see #getApplyStatement()
	 * @generated
	 */
	EReference getApplyStatement_Pipelines();

	/**
	 * Returns the factory that creates the instances of the model.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the factory that creates the instances of the model.
	 * @generated
	 */
	GeneratorFactory getGeneratorFactory();

	/**
	 * <!-- begin-user-doc -->
	 * Defines literals for the meta objects that represent
	 * <ul>
	 *   <li>each class,</li>
	 *   <li>each feature of each class,</li>
	 *   <li>each enum,</li>
	 *   <li>and each data type</li>
	 * </ul>
	 * <!-- end-user-doc -->
	 * @generated
	 */
	interface Literals {
		/**
		 * The meta object literal for the '{@link de.evoal.languages.model.generator.impl.ConfigurationImpl <em>Configuration</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see de.evoal.languages.model.generator.impl.ConfigurationImpl
		 * @see de.evoal.languages.model.generator.impl.GeneratorPackageImpl#getConfiguration()
		 * @generated
		 */
		EClass CONFIGURATION = eINSTANCE.getConfiguration();

		/**
		 * The meta object literal for the '<em><b>Uses</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference CONFIGURATION__USES = eINSTANCE.getConfiguration_Uses();

		/**
		 * The meta object literal for the '<em><b>Pipelines</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference CONFIGURATION__PIPELINES = eINSTANCE.getConfiguration_Pipelines();

		/**
		 * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference CONFIGURATION__STATEMENTS = eINSTANCE.getConfiguration_Statements();

		/**
		 * The meta object literal for the '{@link de.evoal.languages.model.generator.impl.UseImpl <em>Use</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see de.evoal.languages.model.generator.impl.UseImpl
		 * @see de.evoal.languages.model.generator.impl.GeneratorPackageImpl#getUse()
		 * @generated
		 */
		EClass USE = eINSTANCE.getUse();

		/**
		 * The meta object literal for the '<em><b>Import URI</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute USE__IMPORT_URI = eINSTANCE.getUse_ImportURI();

		/**
		 * The meta object literal for the '{@link de.evoal.languages.model.generator.impl.PipelineDefinitionImpl <em>Pipeline Definition</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see de.evoal.languages.model.generator.impl.PipelineDefinitionImpl
		 * @see de.evoal.languages.model.generator.impl.GeneratorPackageImpl#getPipelineDefinition()
		 * @generated
		 */
		EClass PIPELINE_DEFINITION = eINSTANCE.getPipelineDefinition();

		/**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute PIPELINE_DEFINITION__NAME = eINSTANCE.getPipelineDefinition_Name();

		/**
		 * The meta object literal for the '<em><b>Definitions</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference PIPELINE_DEFINITION__DEFINITIONS = eINSTANCE.getPipelineDefinition_Definitions();

		/**
		 * The meta object literal for the '{@link de.evoal.languages.model.generator.impl.StatementImpl <em>Statement</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see de.evoal.languages.model.generator.impl.StatementImpl
		 * @see de.evoal.languages.model.generator.impl.GeneratorPackageImpl#getStatement()
		 * @generated
		 */
		EClass STATEMENT = eINSTANCE.getStatement();

		/**
		 * The meta object literal for the '{@link de.evoal.languages.model.generator.impl.ForStatementImpl <em>For Statement</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see de.evoal.languages.model.generator.impl.ForStatementImpl
		 * @see de.evoal.languages.model.generator.impl.GeneratorPackageImpl#getForStatement()
		 * @generated
		 */
		EClass FOR_STATEMENT = eINSTANCE.getForStatement();

		/**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute FOR_STATEMENT__NAME = eINSTANCE.getForStatement_Name();

		/**
		 * The meta object literal for the '<em><b>Range</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference FOR_STATEMENT__RANGE = eINSTANCE.getForStatement_Range();

		/**
		 * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference FOR_STATEMENT__STATEMENTS = eINSTANCE.getForStatement_Statements();

		/**
		 * The meta object literal for the '{@link de.evoal.languages.model.generator.impl.RangeImpl <em>Range</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see de.evoal.languages.model.generator.impl.RangeImpl
		 * @see de.evoal.languages.model.generator.impl.GeneratorPackageImpl#getRange()
		 * @generated
		 */
		EClass RANGE = eINSTANCE.getRange();

		/**
		 * The meta object literal for the '{@link de.evoal.languages.model.generator.impl.CounterRangeImpl <em>Counter Range</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see de.evoal.languages.model.generator.impl.CounterRangeImpl
		 * @see de.evoal.languages.model.generator.impl.GeneratorPackageImpl#getCounterRange()
		 * @generated
		 */
		EClass COUNTER_RANGE = eINSTANCE.getCounterRange();

		/**
		 * The meta object literal for the '<em><b>Start</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute COUNTER_RANGE__START = eINSTANCE.getCounterRange_Start();

		/**
		 * The meta object literal for the '<em><b>End</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute COUNTER_RANGE__END = eINSTANCE.getCounterRange_End();

		/**
		 * The meta object literal for the '{@link de.evoal.languages.model.generator.impl.PipelineArrayImpl <em>Pipeline Array</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see de.evoal.languages.model.generator.impl.PipelineArrayImpl
		 * @see de.evoal.languages.model.generator.impl.GeneratorPackageImpl#getPipelineArray()
		 * @generated
		 */
		EClass PIPELINE_ARRAY = eINSTANCE.getPipelineArray();

		/**
		 * The meta object literal for the '<em><b>References</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference PIPELINE_ARRAY__REFERENCES = eINSTANCE.getPipelineArray_References();

		/**
		 * The meta object literal for the '{@link de.evoal.languages.model.generator.impl.PipelineReferenceImpl <em>Pipeline Reference</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see de.evoal.languages.model.generator.impl.PipelineReferenceImpl
		 * @see de.evoal.languages.model.generator.impl.GeneratorPackageImpl#getPipelineReference()
		 * @generated
		 */
		EClass PIPELINE_REFERENCE = eINSTANCE.getPipelineReference();

		/**
		 * The meta object literal for the '<em><b>Pipeline</b></em>' reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference PIPELINE_REFERENCE__PIPELINE = eINSTANCE.getPipelineReference_Pipeline();

		/**
		 * The meta object literal for the '{@link de.evoal.languages.model.generator.impl.ApplyStatementImpl <em>Apply Statement</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see de.evoal.languages.model.generator.impl.ApplyStatementImpl
		 * @see de.evoal.languages.model.generator.impl.GeneratorPackageImpl#getApplyStatement()
		 * @generated
		 */
		EClass APPLY_STATEMENT = eINSTANCE.getApplyStatement();

		/**
		 * The meta object literal for the '<em><b>File</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute APPLY_STATEMENT__FILE = eINSTANCE.getApplyStatement_File();

		/**
		 * The meta object literal for the '<em><b>Count</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute APPLY_STATEMENT__COUNT = eINSTANCE.getApplyStatement_Count();

		/**
		 * The meta object literal for the '<em><b>Pipelines</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference APPLY_STATEMENT__PIPELINES = eINSTANCE.getApplyStatement_Pipelines();

	}

} //GeneratorPackage
