import "definitions" from de.evoal.optimisation.core;

module de.evoal.optimisation.local_search.optimisation {
	/**
	 * Optimisation algorithm that implements local search strategies, such as
	 *   * Hill Climbing
	 *   * Simulated Annealing
	 *   * Threshold Accepting
	 */
	type 'local-search' extends 'algorithm' {
		/**
		 * Maximum number of iterations. This parameter does not work as a stopping 
		 *   criterion.
		 */
    	'number-of-iterations' : int;

		/**
		 * Strategy for selecting neighbours.
		 */
    	'neighbour-choosing-strategy' : instance 'choosing-strategy';

		/**
		 * Strategy for accepting new solution candidates.
		 */
		'accepting-strategy' : instance 'accepting-strategy';		
	}
	
	/**
	 * Base type for all accepting strategies.
	 */
	abstract type 'accepting-strategy' {
	}

	/**
	 * The hill climber only accepts better results.
	 */
    type 'hill-climber' extends 'accepting-strategy' {
    }

    /**
     * Accepts worser candidates based on a threshold. The threshold decreases over time.
     */
    type 'threshold-accepting' extends 'accepting-strategy' {
    	/**
    	 * The threshold value to start with.
    	 */
        'initial-threshold' : real;
        
        /**
         * The function for decreasing the threshold after every iteration.
         */
        'decreasing-function' : instance 'decreasing-strategy';
    }

    /**
     * Simulated annealing is an acceptance probability function. The probability is affected
     *   by the temperature, which decreases according to a cooling schedule.
     */
    type 'simulated-annealing' extends 'accepting-strategy'{
    	/**
    	 * The temperature value to start with.
    	 */
        'initial-temperature' : real;

        /**
         * The function for decreasing the temperature after every iteration.
         */
        'decreasing-function' : instance 'decreasing-strategy';
        
        /**
         * The acceptance function based on the probability.
         */
        'acceptance-probability' : instance 'probability-acceptance-function';
    }

    /**
    * Neighbour choosing strategy for hill-climbing algorithm
    */
	abstract type 'choosing-strategy' {
	}

    /**
    * This strategy tries moving the given step size
    * in all possible directions until improvement is found
    */
	type 'manual-strategy' extends 'choosing-strategy' {
	    /**
	    * specify a step size for each variable of the
	    * search space.
	    */
    	'step-size' : array instance variable;
	}

    /**
    * Cooling strategies determine how temperature is decreased in each iteration
    */
    abstract type 'decreasing-strategy' {}

    /**
    * T(k) = T_0 - (k * T_0/#iterations)
    */
    type 'linear-decrease' extends 'decreasing-strategy' {}

    /**
    * T(k) = T(k-1) * cooling_rate
    */
    type 'geometric-decrease' extends 'decreasing-strategy' {
        'decrease-rate' : real;
    }

    /**
    * T(k) = T_0/log(k+1)
    */
    type 'logarithmic-decrease' extends 'decreasing-strategy' {}

    /**
    * T(k) = T_0 * exp(-k^(1/N))
    */
    type 'exponential-decrease' extends 'decreasing-strategy' {}

    /**
    * T(k) = T(k-1) - (rate*k)
    */
    type 'arithmetic-decrease' extends 'decreasing-strategy' {
        'rate' : real;
    }

    /**
    * Determines probability of accepting neighbouring solutions based
    * on fitness and temperature.
    */
    abstract type 'probability-acceptance-function' {}

    /**
    * Exponential acceptance function determines acceptance probability according to formula:
    * P(f(s), f(s'), T) = exp(max( (f(s')-f(s)/T(k)), 0) for maximisation
    * P(f(s), f(s'), T) = exp(max( -(f(s')-f(s)/T(k)), 0) for minimisation
    */
    type 'exponential-probability' extends 'probability-acceptance-function' {}

}
