/*
 * generated by Xtext 2.29.0
 * (c) EvoAl Project
 */
package de.evoal.languages.model.mll.dsl.scoping;

import de.evoal.languages.model.generator.dsl.scoping.GeneratorDSLScopeProvider;

public abstract class AbstractMachineLearningLanguageScopeProvider extends GeneratorDSLScopeProvider {
}
