grammar de.evoal.languages.model.mll.dsl.MachineLearningLanguage with de.evoal.languages.model.base.dsl.BaseLanguage

import "https://www.evoal.de/languages/mll/1.0.0" 
import "https://www.evoal.de/languages/ddl/1.0.0" as ddl
import "https://www.evoal.de/languages/base/1.0.0" as base
import "https://www.evoal.de/languages/base/definitions/1.0.0" as defs

MachineLearningModuleRule returns MachineLearningModule:
	(imports += ImportRule)*

	"module" name = QualifiedName "{"
		(definitions+=SurrogateDefinitionRule)*
		(statements += StatementRule)*
	"}"
;

SurrogateDefinitionRule returns SurrogateDefinition: 
	"prediction" name = StringOrId
	"maps"
		inputs += [defs::DataDescription|QualifiedName] ("," inputs += [defs::DataDescription|QualifiedName])* 
	"to"
		outputs += [defs::DataDescription|QualifiedName] ("," outputs += [defs::DataDescription|QualifiedName])* 

	"using"
		(layers += SurrogateLayerDefinitionRule)+
;

SurrogateLayerDefinitionRule returns SurrogateLayerDefinition:
	"layer" name = StringOrId
	"with"
		(functions += PartialSurrogateFunctionDefinitionRule)+
;
		
PartialSurrogateFunctionDefinitionRule returns PartialSurrogateFunctionDefinition:
	"function" definition = [defs::TypeDefinition|QualifiedName]
	"mapping"
		inputs += [defs::DataDescription|QualifiedName] ("," inputs += [defs::DataDescription|QualifiedName])* 
	"to"
		outputs += [defs::DataDescription|QualifiedName] ("," outputs += [defs::DataDescription|QualifiedName])* 
	("with" "parameters"
		((attributes+= BaseLanguage::AttributeRule)+ ))?
;

PredictStatementRule returns PredictStatement:
	"predict" surrogate = [SurrogateDefinition|QualifiedName]
		'from' trainingData = STRING
		('and' 'measure'
			(statements += CallStatementRule)*
		 'end'
		)?
		'and' 'store' 'to' modelFilename = STRING;

      
StatementRule returns Statement:
	CallStatementRule | ForStatementRule | PredictStatementRule;
	
ForStatementRule returns ForStatement:
	'for' name = ID 'in' range = RangeRule 'loop'
		(statements += StatementRule)*
	'end'
;

RangeRule returns Range:
	CounterRangeRule | LiteralRangeRule	
;

CounterRangeRule returns CounterRange:
	'[' start = INT 'to' end = INT ']'
;

LiteralRangeRule returns LiteralRange:
	'[' elements += LiteralRule (',' elements += LiteralRule)* ']'
;

BlockStatementRule returns BlockStatement:
	{BlockStatement}
	'begin'
	    (statements += StatementRule)*
	'end'
;

CallStatementRule returns CallStatement:
	call = CallRule ';'
;

