grammar de.evoal.languages.model.mll.dsl.MachineLearningLanguage with de.evoal.languages.model.instance.dsl.InstanceLanguage

import "https://www.evoal.de/languages/mll/1.0.0" 
import "https://www.evoal.de/languages/ddl/1.0.0" as ddl
import "https://www.evoal.de/languages/base/1.0.0" as base

MachineLearningConfigurationRule returns MachineLearningConfiguration:
	(imports += ImportRule)*

	(definitions+=SurrogateDefinitionRule)*
	(statements += StatementRule)*
;

SurrogateDefinitionRule returns SurrogateDefinition: 
	"prediction" name = STRING
	"maps"
		inputs += [ddl::DataDescription|StringOrId] ("," inputs += [ddl::DataDescription|StringOrId])* 
	"to"
		outputs += [ddl::DataDescription|StringOrId] ("," outputs += [ddl::DataDescription|StringOrId])* 

	"using"
		(layers += SurrogateLayerDefinitionRule)+
;

SurrogateLayerDefinitionRule returns SurrogateLayerDefinition:
	"layer" name = STRING
	"with"
		(functions += PartialSurrogateFunctionDefinitionRule)+
;
		
PartialSurrogateFunctionDefinitionRule returns PartialSurrogateFunctionDefinition:
	"function" name = [base::TypeDefinition|StringOrId]
	"mapping"
		inputs += [ddl::DataDescription|StringOrId] ("," inputs += [ddl::DataDescription|StringOrId])* 
	"to"
		outputs += [ddl::DataDescription|StringOrId] ("," outputs += [ddl::DataDescription|StringOrId])* 
	("with" "parameters"
		((parameters += BaseLanguage::AttributeRule)+ ))?
;

PredictStatementRule returns PredictStatement:
	"predict" surrogate = [SurrogateDefinition|StringOrId]
		'from' trainingData = STRING
		('and' 'measure'
			(statements += CallStatementRule)*
		 'end'
		)?
		'and' 'store' 'to' modelFilename = STRING;

      
StatementRule returns Statement:
	CallStatementRule | ForStatementRule | PredictStatementRule;
	
ForStatementRule returns ForStatement:
	'for' name = ID 'in' range = RangeRule 'loop'
		(statements += StatementRule)*
	'end'
;

RangeRule returns Range:
	CounterRangeRule | StringLiterRangeRule	
;

CounterRangeRule returns CounterRange:
	'[' start = INT 'to' end = INT ']'
;

StringLiterRangeRule returns StringLiteralRange:
	'[' elements += StringLiteralRule (',' elements += StringLiteralRule)* ']'
;

BlockStatementRule returns BlockStatement:
	{BlockStatement}
	'begin'
	    (statements += StatementRule)*
	'end'
;

CallStatementRule returns CallStatement:
	call = CallRule ';'
;

