/*
 * generated by Xtext 2.25.0
 * (c) EvolAl Project
 */
package de.evoal.languages.model.ddl.dsl.validation;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EStructuralFeature;
import org.eclipse.xtext.util.Triple;
import org.eclipse.xtext.validation.Check;

import de.evoal.languages.model.base.Expression;
import de.evoal.languages.model.ddl.DataDescriptionModule;
import de.evoal.languages.model.ddl.DdlPackage;
import de.evoal.languages.model.utils.validator.ModuleValidator;
import de.evoal.languages.model.utils.validator.ScaleValidator;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class DataDescriptionLanguageValidator extends AbstractDataDescriptionLanguageValidator {
	
//	public static final String INVALID_NAME = "invalidName";
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					DataDescriptionLanguagePackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	
	
	@Check
	public void checkModule(final DataDescriptionModule module) {
		ModuleValidator.check(module, module.getName(), "ddl", msg -> error(msg, module, DdlPackage.Literals.DATA_DESCRIPTION_MODULE__NAME));
	}
	
	private void errorConsumer(final Triple<String, EObject, EStructuralFeature> data) {
		error(data.getFirst(), data.getSecond(), data.getThird());
	}
	
	public void checkConstraint(final Expression expression) {
		ScaleValidator.check(expression, this::errorConsumer);
	}

}
