import "definitions" from 'de.evoal.optimisation.core';
import "definitions" from 'de.evoal.pipeline.benchmarks';

module 'de.evoal.pipeline.optimisation' {
	/**
	 * A combination of known optimisation functions for benchmarking purposes.
	 */
	type 'benchmark-function' extends 'optimisation-function' {
	    /**
         * The binding of benchmark functions to the generated data.
         */
	     benchmarks : array instance 'benchmark-configuration';
	}

    /**
     * States the benchmark function to use and which data it generates.
     */
	type 'benchmark-configuration' {
	    /**
	     * Benchmark function to use during evaluation.
	     */
	    function : instance benchmark;

	    /**
	     * The data the benchmark will read.
	     */
	    'reads' : array data;

	    /**
	     * The data the benchmark will generate.
	     */
	    'writes' : array data;
	}
}
