/*
 * generated by Xtext 2.41.0
 * (c) EvoAl Project
 */
package de.evoal.languages.model.base.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class BaseLanguageAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/evoal/languages/model/base/dsl/parser/antlr/internal/InternalBaseLanguage.tokens");
	}
}
