<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ddl" nsURI="https://www.evoal.de/languages/ddl/1.0.0" nsPrefix="ddl">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="dl" value="platform:/resource/de.evoal.languages.model.dl/model/model.ecore#/"/>
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
    <details key="el" value="platform:/resource/de.evoal.languages.model.base/model/model.ecore#/"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="DataDescriptionModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="uses" ordered="false" upperBound="-1"
        eType="#//Use" containment="true">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" ordered="false"
        upperBound="-1" eType="#//DataTypeDefinition" containment="true">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="descriptions" ordered="false"
        upperBound="-1" eType="#//DataDescription" containment="true">
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" ordered="false"
        upperBound="-1" eType="ecore:EClass ../../de.evoal.languages.model.base/model/model.ecore#//Expression"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List of global constraints"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Use">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importURI" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ScaleType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The scale of a variable or a data type."/>
    </eAnnotations>
    <eLiterals name="Nominal" literal="nominal"/>
    <eLiterals name="Ordinal" literal="ordinal"/>
    <eLiterals name="Cardinal" literal="cardinal"/>
    <eLiterals name="Quotient" literal="quotient"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RepresentationType">
    <eLiterals name="Real" literal="real"/>
    <eLiterals name="Integer" value="1" literal="integer"/>
    <eLiterals name="Boolean" value="2" literal="boolean"/>
    <eLiterals name="String" value="3" literal="string"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataTypeDefinition">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A data type that allows reuse of information."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scale" eType="#//ScaleType"
        transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Scale of the data type."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Name of the data type, e.g., Newton."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Optional description of the data type."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" ordered="false"
        upperBound="-1" eType="ecore:EClass ../../de.evoal.languages.model.base/model/model.ecore#//Expression"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List of constraints for this data type"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataDescription" abstract="true">
    <eOperations name="getScale" eType="#//ScaleType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Returns the associated scale if existing."/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Name of the described data."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" ordered="false"
        upperBound="-1" eType="ecore:EClass ../../de.evoal.languages.model.base/model/model.ecore#//Expression"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List of constraints for this data description"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/OCL/Collection">
        <details key="nullFree" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="representation" lowerBound="1"
        eType="#//RepresentationType" defaultValueLiteral="real"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedDataDescription" eSuperTypes="#//DataDescription">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A typed data description."/>
    </eAnnotations>
    <eOperations name="getScale" eType="#//ScaleType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getType() == null ? null : getType().getScale();"/>
        <details key="documentation" value="Returns the scale of the associated data type."/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//DataTypeDefinition">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The type associated to this data description."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UntypedDataDescription" eSuperTypes="#//DataDescription">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An untyped data description."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scale" eType="#//ScaleType"
        transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Scale of the data description."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataReference" eSuperTypes="../../de.evoal.languages.model.base/model/model.ecore#//ValueReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" lowerBound="1"
        eType="#//DataDescription"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelfReference" eSuperTypes="../../de.evoal.languages.model.base/model/model.ecore#//ValueReference"/>
</ecore:EPackage>
