/*
y * generated by Xtext 2.25.0
 */
package de.evoal.languages.model.dl.dsl;

import org.eclipse.xtext.resource.IDefaultResourceDescriptionStrategy;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

import de.evoal.languages.model.dl.dsl.scoping.DefinitionLanguageLocalScopeProvider;
import de.evoal.languages.model.dl.dsl.scoping.DefinitionLanguageResourceDescriptionStrategy;
import de.evoal.languages.model.utils.converter.ValueConverterService;

import org.eclipse.xtext.conversion.IValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DefinitionLanguageRuntimeModule extends AbstractDefinitionLanguageRuntimeModule {

    /*
     * If you enable this strategy, the NamesAreUniqueValidator will not
     * work as expected.
     */
    public Class<? extends IDefaultResourceDescriptionStrategy> bindIDefaultResourceDescriptionStrategy() {
            return  DefinitionLanguageResourceDescriptionStrategy.class;
    }
    
	@Override
	public void configureIScopeProviderDelegate(com.google.inject.Binder binder) {
		binder.bind(org.eclipse.xtext.scoping.IScopeProvider.class)
				.annotatedWith(
						com.google.inject.name.Names
								.named(AbstractDeclarativeScopeProvider.NAMED_DELEGATE))
				.to(DefinitionLanguageLocalScopeProvider.class);
	}

	@Override
    public Class<? extends IValueConverterService> bindIValueConverterService() {
            return ValueConverterService.class;
    }
}
