grammar de.evoal.languages.model.dl.dsl.DefinitionLanguage with de.evoal.languages.model.base.dsl.BaseLanguage

import "https://www.evoal.de/languages/dl/1.0.0"


DefinitionModelRule returns DefinitionModel:
	(imports += ImportRule)*
	'module' name = QualifiedName '{'
		((types += TypeDefinitionRule ) | (functions += FunctionDefinitionRule ) | constants += ConstantDefinitionRule)*
	'}'
;

ImportRule returns Import:
	'import' importedNamespace = QualifiedName ';'
;
