<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>de.evoal</groupId>
        <artifactId>releng.parent</artifactId>
        <version>0.9.0-SNAPSHOT</version>

        <relativePath>../de.evoal.releng.parent</relativePath>
    </parent>

    <artifactId>releng.jacoco</artifactId>
    <packaging>pom</packaging>

    <name>EvoAl - JaCoCo</name>

    <dependencies>
        <dependency>
            <groupId>${parent.groupId}</groupId>
            <artifactId>core.arff</artifactId>
            <version>${parent.version}</version>
        </dependency>
        <dependency>
            <groupId>${parent.groupId}</groupId>
            <artifactId>core.ea</artifactId>
            <version>${parent.version}</version>
        </dependency>
        <dependency>
            <groupId>${parent.groupId}</groupId>
            <artifactId>core.junit</artifactId>
            <version>${parent.version}</version>
        </dependency>
        <dependency>
            <groupId>${parent.groupId}</groupId>
            <artifactId>core.main</artifactId>
            <version>${parent.version}</version>
        </dependency>
        <dependency>
            <groupId>${parent.groupId}</groupId>
            <artifactId>generator.main</artifactId>
            <version>${parent.version}</version>
        </dependency>
        <dependency>
            <groupId>${parent.groupId}</groupId>
            <artifactId>surrogate.api</artifactId>
            <version>${parent.version}</version>
        </dependency>
        <dependency>
            <groupId>${parent.groupId}</groupId>
            <artifactId>surrogate.simple</artifactId>
            <version>${parent.version}</version>
        </dependency>
        <dependency>
            <groupId>${parent.groupId}</groupId>
            <artifactId>surrogate.svr</artifactId>
            <version>${parent.version}</version>
        </dependency>
        <dependency>
            <groupId>${parent.groupId}</groupId>
            <artifactId>approximative.density</artifactId>
            <version>${parent.version}</version>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>jacoco</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.jacoco</groupId>
                        <artifactId>jacoco-maven-plugin</artifactId>
                        <version>0.8.10</version>
                        <executions>
                            <execution>
                                <phase>verify</phase>
                                <goals>
                                    <goal>report-aggregate</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>