<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="base" nsURI="https://www.evoal.de/languages/base/1.0.0" nsPrefix="base">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&#xA;General import statement for all languages.&#xA;"/>
    </eAnnotations>
    <eOperations name="getFilename" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="String result = getImportedNamespace();&#xA;&#xA;// turn into path&#xA;result = result.replace('.', '/');&#xA;&#xA;// append file ending&#xA;switch(getLanguage()) {&#xA;    case &quot;data&quot;:&#xA;        result += &quot;.ddl&quot;;&#xA;        break;&#xA;&#xA;  case &quot;surrogate&quot;:&#xA;        result += &quot;.mll&quot;;&#xA;        break;&#xA;&#xA;    case &quot;definitions&quot;:&#xA;        result += &quot;.dl&quot;;&#xA;        break;&#xA;    case &quot;optimisation&quot;:&#xA;    case &quot;optimization&quot;:&#xA;        result += &quot;.ol&quot;;&#xA;        break;&#xA;}&#xA;&#xA;return result;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
