<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>de.evoal</groupId>
		<artifactId>core.plugin</artifactId>
		<version>${revision}</version>
	</parent>

	<artifactId>generator.main</artifactId>
	<name>EvoAl - Plugins - Generator - Main</name>

	<dependencies>
		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.generator</artifactId>
			<version>${evoal.languages.version}</version>
		</dependency>

		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.pipeline</artifactId>
			<version>${evoal.languages.version}</version>
		</dependency>

		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.dynamic</artifactId>
			<version>${evoal.languages.version}</version>
		</dependency>

		<dependency>
			<groupId>de.evoal.languages</groupId>
			<artifactId>de.evoal.languages.model.generator.dsl</artifactId>
			<version>${evoal.languages.version}</version>
		</dependency>

		<dependency>
			<groupId>de.evoal</groupId>
			<artifactId>optimisation.api</artifactId>
			<version>${project.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
            		<groupId>net.objecthunter</groupId>
            		<artifactId>exp4j</artifactId>
            		<version>0.4.8</version>
        	</dependency>	
	</dependencies>
</project>
